[라흐] 레벨3 -회고 글쓰기 미션 제출합니다.
woowacourse/woowa-writing-2 pull request #128
Opened 2020-08-23 14:54 UTC by Hamliet

안녕하세요 라흐입니다! 글이 조금 늦었네요 ㅠㅠ 
리뷰 잘 부탁드립니다!! 😄 

[여기](https://github.com/Hamliet/woowa-writing-2/blob/hamliet/LEVEL3.md)서 편하게 읽으세요!

2020-08-23 16:51 UTC, JinJuMoon requested changes
안녕하세요, 라흐! 무늬입니다 😄 
솔직담백한 글 잘읽었습니다 👍 
레벨 3동안 많은 고민과 성장을 거쳐온 라흐를 볼 수 있었어요.
간단한 코멘트 남겼으니 가볍게 확인해주세요~

2020-08-23 16:51 UTC, JinJuMoon commented on LEVEL3.md
> +처음에는 굉장히 비효율적이라고 생각했는데, 다 같이 자신의 의견을 말하는 것이 아니라 한 사람의 의견을 깊이 일대일로 듣다 보니까 서로의 생각을 더 깊이 알 수 있었다.
생각지 못한 장점이네요! 😄

2020-08-23 16:51 UTC, JinJuMoon commented on LEVEL3.md
> +하지만 서로의 생각을 명확하게 알고 있지 못했고 나중에 가서야 서로 생각이 다른 것을 알게 되어 문제가 생겼었다.
```suggestion
하지만 서로의 생각을 명확하게 알고 있지 못했고 나중에 가서야 서로 생각이 다른 것을 알게 되어 문제가 생겼다.
```
과거를 나타내는 선어말어미는 한 개로 충분할 것 같아요!

2020-08-23 16:51 UTC, JinJuMoon commented on LEVEL3.md
> +- 받아들이는 방식의 차이
마크다운이 렌더링 되면서 소제목이 문장과 합쳐지네요 😢

2020-08-23 16:51 UTC, JinJuMoon commented on LEVEL3.md
> +나 같은 경우는 어느 정도의 근거가 필요하지만 감정에 설득도 되고 다수의 의견을 따르는 등 여러 모습들을 조금씩 갖고 있었다.
공감되는 부분이예요!

2020-08-23 16:51 UTC, JinJuMoon commented on LEVEL3.md
> +남은 1주일뿐만 아니라 방학기간, 레벨 4까지 지금까지 한 성장보다 훨씬 많은 성장을 이루고 싶다.
지금처럼 한번 더 성장한 라흐의 모습, 기대할게요 👍

2020-08-23 16:51 UTC, JinJuMoon commented on LEVEL3.md
> + 나는 지금까지 한 프로젝트를 이렇게 깊이 있게 해본 적이 없었다. 공모전에 참여했을 때도 내가 맡은 부분만 열심히 했을 뿐 다른 파트가 하는 일은 나서서 알려고 하지 않았다.
뒷 문장을 읽기 전까지는 '한' 이라는 단어가 '하다'라는 뜻인지 '하나의'라는 뜻인지 모호한 것 같아요. '하나의 프로젝트'와 같은 표현은 어떨까요?

2020-08-23 19:26 UTC, Hamliet commented on LEVEL3.md
> +하지만 서로의 생각을 명확하게 알고 있지 못했고 나중에 가서야 서로 생각이 다른 것을 알게 되어 문제가 생겼었다.
수정하도록 하겠습니다!! :)

2020-08-23 19:29 UTC, Hamliet commented on LEVEL3.md
> +- 받아들이는 방식의 차이
수정하겠습니다! 감사해요 ㅎㅎ

2020-08-23 19:30 UTC, Hamliet commented on LEVEL3.md
> + 나는 지금까지 한 프로젝트를 이렇게 깊이 있게 해본 적이 없었다. 공모전에 참여했을 때도 내가 맡은 부분만 열심히 했을 뿐 다른 파트가 하는 일은 나서서 알려고 하지 않았다.
그렇네요! 수정하겠습니다 😄

2020-08-23 19:42 UTC, jjj0611 requested changes
라흐 글 잘 읽었습니다.
특별했던 LEVEL3의 시간을 통해 더 성장한 라흐를 볼 수 있었어요!
간단하게 고려해볼만한 부분들을 남겼으니 참고해보시고, 라흐가 더 좋다고 여기는 방향으로 반영해주시면 좋을 것 같아요!
더불어 워니가 강의 자료에 올려준 맞춤법 검사기를 한 번 돌려보는 것도 좋은 방향일 것 같아요!

LEVEL3 너무 고생하셨고, 남은 기간도 잘 마무리 하여 더 성장하는 LEVEL4가 됩시다!

2020-08-23 19:42 UTC, jjj0611 commented on LEVEL3.md
> +원인이 무엇일까 생각해보면 의견 전달 방식, 서로 받아들이는 방식, 서로를 납득시키는 방식이 서로 달라 의견 충돌이 많았던 것 같다.
```suggestion
원인이 무엇일까 생각해보면 의견 전달 방식, 서로 받아들이는 방식, 서로를 납득시키는 방식이 달라 의견 충돌이 많았던 것 같다.
```

2020-08-23 19:42 UTC, jjj0611 commented on LEVEL3.md
> +나는 이번 팀 프로젝트에서 겪었던 이런 어려움들을 공유하고 어떤 노력들을 했는지 공유하고자 한다.
```suggestion
이번 팀 프로젝트에서 겪었던 어려움을 공유하고 어떤 노력들을 했는지 공유하고자 한다.
```

2020-08-23 19:42 UTC, jjj0611 commented on LEVEL3.md
> +소통의 관점에서 이번 프로젝트는 '다양한 성향의 사람들이 갈등 상황을 겪을 때 나는 무엇을 해야 하는가?'에 대한 고민을 많이 할 수 있었던 프로젝트였다.
정말 필요한 고민인 것 같아요!

2020-08-23 19:42 UTC, jjj0611 commented on LEVEL3.md
> +기술 관점에서 이번 프로젝트는 '무엇이든 나도 해낼 수 있다'는 자신감을 얻게 해준 프로젝트였다.
정말 중요한 부분인 것 같아요!
라흐에게 특별한 LEVEL3는 성장할 수 있는 좋은 시간이었네요 :)

2020-08-23 19:42 UTC, jjj0611 approved these changes

2020-08-23 19:59 UTC, Hamliet commented on LEVEL3.md
> +원인이 무엇일까 생각해보면 의견 전달 방식, 서로 받아들이는 방식, 서로를 납득시키는 방식이 서로 달라 의견 충돌이 많았던 것 같다.
서로를 두 번 썼었네요..! 수정하겠습니다!! 감사해요 :)

2020-08-23 20:02 UTC, Hamliet commented on LEVEL3.md
> +나는 이번 팀 프로젝트에서 겪었던 이런 어려움들을 공유하고 어떤 노력들을 했는지 공유하고자 한다.
확실히 제이가 추천해주신 문장이 더 좋네요! 수정하도록 하겠습니다. 😄 
(부산대 맞춤법 검사기가 아니라 네이버 맞춤법 검사기를 썼었는데, 확실히 부산대 맞춤법 검사기가 성능이 좋을 것 같아요 😅)

2020-08-24 07:08 UTC, KimGyeong approved these changes
안녕하세요 라흐! 어떻게 보면 팀에 대한 글 같기도, 어떻게 보면 라흐 본인에 대한 글을 쓰신 것 같아요. 그만큼 팀에 대한 배려심이 큰 것일까요? 레벨 3 동안 많은 부분 어려웠던 것으로 보여요. 그럼으로 인해서 본인이 성장할 수 있는 기회였을 것이라고 생각하면 좋을 것 같습니다. 레벨 4에는 조금은 덜 힘든 시간들을 보냈으면 좋겠어요. 화이팅입니다! Approve 하겠습니다.

2020-08-24 07:08 UTC, KimGyeong commented on LEVEL3.md
> +팀 내 회고 시간에 어떤 크루가 '나는 A라는 의도로 말했다.'라고 이야기했고 다른 크루는 '나는 B라고 받아들였다'라고 이야기를 했는데, 그 의미가 완전 달랐던 것에서 놀랐다.
```suggestion
팀 내 회고 시간에 어떤 크루가 '나는 A라는 의도로 말했다.'라고 이야기했고 다른 크루는 '나는 B라고 받아들였다'라고 이야기를 했는데, 그 의미가 완전히 다른 것에서 놀랐다.
```
이렇게 이야기하는 것이 좀 더 부드러운 느낌이 드는데 어떠신가요?

2020-08-24 09:18 UTC, JinJuMoon approved these changes
수고하셨습니다~ 이만 어프루브할게요! 👍

2020-08-24 10:26 UTC, Hamliet commented on LEVEL3.md
> +팀 내 회고 시간에 어떤 크루가 '나는 A라는 의도로 말했다.'라고 이야기했고 다른 크루는 '나는 B라고 받아들였다'라고 이야기를 했는데, 그 의미가 완전 달랐던 것에서 놀랐다.
그렇네요! 반영하도록 하겠습니다!!

2020-08-24 10:42 UTC, joseph415 approved these changes
라흐 간단한 코맨트 달았습니다! 레벨3기간동안 정말 고생많으셨습니다!
그만큼 더 큰 성장이 있을거라 생각합니다! 더 큰 역경이 있어도 더 잘 버티실 수 있을거라고 생각되네요!
남은 기간도 마무리 잘해서 레벨4때 좋은 모습으로 봐요💯

2020-08-24 10:42 UTC, joseph415 commented on LEVEL3.md
> +한 크루는 말 그대로 표면적인 의미 그대로의 A를 이야기했는데 다른 크루는 그 말에서 B라는 의도를 갖고 말을 했다고 해석했기 때문이다.
위 문장과 아래 문장이 같은 내용에 대한 반복되서 나타나는 것 같아요!

```
한 크루는 말 그대로 표면적인 의미 그대로의 A를 이야기했는데 다른 크루는 그 말에서 B라는 의도를 갖고 말을 했다고 해석했기 때문이다.
```
이 부분은 없어도 충분히 의미를 전달해주지 않을 까 생각 되어요! 예시에 대한 원인이라고 생각드는데 그 부분은 앞에서 똑같이 말해주신것 같아서 조심스럽게 제 의견 남겨요!

2020-08-24 10:42 UTC, joseph415 commented on LEVEL3.md
> +사전에 이야기했던 내용을 서로 다르게 받아들였고 같은 생각을 하고 있다고 생각했는데 나중에 보니 서로 다른 이야기를 하고 있었다.
같은 내용이 계속 반복되어서 문장이 길어진 것 같은데 이런 식으로 핵심 내용만 담기면 어떨까요?
```suggestion
같은 생각을 하고 있다고 생각했는데 사전에 이야기했던 내용을 서로 다르게 받아들이고 있었다.
```

2020-08-24 11:02 UTC, Hamliet commented on LEVEL3.md
> +한 크루는 말 그대로 표면적인 의미 그대로의 A를 이야기했는데 다른 크루는 그 말에서 B라는 의도를 갖고 말을 했다고 해석했기 때문이다.
세 문장을 보니 정말 그렇네요! 반영하겠습니다 :)

2020-08-24 11:04 UTC, Hamliet commented on LEVEL3.md
> +사전에 이야기했던 내용을 서로 다르게 받아들였고 같은 생각을 하고 있다고 생각했는데 나중에 보니 서로 다른 이야기를 하고 있었다.
좋은 것 같습니다!! 😄

2020-08-25 10:17 UTC, eastjun approved these changes
원치 않는 갈등을 스스로 겪어보고자 하는 사람은 없을꺼에요. 하지만 때로는 그 경험이 앞으로 마주할 수 있는 갈등상황에서 겪게될 실수를 미리 경험해본 것이라고 생각이 들어요. 원치 않았던 경험이라고 덮으려 하지 않고, 이렇게 드러내서 다른 크루들에게도 이야기를 공유해줘서 고마워요. 분명히 이 경험을 통해 팀원들과 라흐는 소통과, 갈등 해결 과정에서 서로의 특징 등을 깊이있게 성찰한 계기였을꺼에요. 이 경험이 더 큰 성장으로 나아가는 점으로 생각해주세요. 너무 고생하셨습니다.

2020-08-25 10:17 UTC, merged