[유안] 레벨 1 글쓰기 제출합니다
woowacourse/woowa-writing-2 pull request #13
Opened 2020-03-30 08:31 UTC by KimSeongGyu1

2020-03-30 09:04 UTC, woonjangahn requested changes
안녕하세요 유안! 리뷰를 맡은 호돌입니다! 🐯
요구사항에 맞게 잘 구현해주셨어요! 💯

우테코에 임하는 유안의 비장한 각오가 느껴지는 글이네요!
아쉬운 점이 있어 몇 가지 피드백 남기니, 원래 의도를 해치지 않는 선에서 선택적으로 반영 부탁드려요!

2020-03-30 09:04 UTC, woonjangahn commented on 레벨1.md
> +내가 지금까지 받아온 교육들은 전부 의심하지 않고 잘 이해하는 것에 가장 큰 가치를 두었다. 그들은 지식을 이해하기 쉬운 형태로 가공해서 전달하는 것에만 집중했다. 우아한 테크코스에서는 기존의 지식을 의심하고 고민하는 것에 가치를 둔다. 이곳에서는 방향성만 잡아주고 지식을 필요이상으로 가공해서 떠먹여주지 않는다.
`필요이상` -> `필요 이상`!

2020-03-30 09:04 UTC, woonjangahn commented on 레벨1.md
> +새삼스럽지만 정말 좋은 환경속에 운좋게 들어왔다고 생각한다. 좋은 방향으로 성장할 수 있도록 계속 유도해준다. 대놓고 가르쳐주거나 이끌어주지는 않지만 앞으로 사회에서 살아갈 것을 생각하면 오히려 좋다.
`환경속에` ->`환경 속에` `운좋게` -> `운 좋게`!
전체적으로 맞춤법을 [여기](http://www.jobkorea.co.kr/service/user/Tool/SpellCheck)를 통해 수정해주세요!

2020-03-30 09:04 UTC, woonjangahn commented on 레벨1.md
> +앞으로 남은 기간동안 충분히 생각하며 좋은 환경을 최대한 누려보려고 한다. 이 과정이 모두 끝났을 때 나만의 발전한 생각을 가지게 되기를 바란다.
>'능동형' 문장을 쓰도록 한다.
글 속에서 생동감을 살릴 수 있도록 한다.

`가지게 되기를` 보단 `가지길`이 낫죠!

2020-03-30 09:04 UTC, woonjangahn commented on 레벨1.md
> +성장하기 위해서는 충분히 생각하고 고민해보는 것이 중요하다고 생각한다. 그래서 다시 생각을 충분히 하기 위해 무엇이 필요한지 생각해보았다.
인트로가 멋있네요 💯

2020-03-30 09:04 UTC, woonjangahn commented on 레벨1.md
> +군대는 지적인 성장을 이루기에는 내 경험 중 최악의 환경이었다. 그 환경에 대한 반발심인지 지적 성장에 대한 열정이 어느때 보다 강했었다.
어떤 일을 겪었는지 궁금해요 😞

2020-03-30 09:04 UTC, woonjangahn commented on 레벨1.md
> +열정을 되찾기 위해 군대에서 가장 열정을 불러일으켜 주었던 책을 다시 샀다. 그 때만큼의 열정을 계속 유지할 수는 없겠지만 꾸준히 읽으면서 열정을 죽이지 않으려 한다.
무슨 책인가요? 크루들에게도 공유해주세요! 📖

2020-03-30 09:04 UTC, woonjangahn commented on 레벨1.md
> +내가 그동안 느꼈던 뿌듯함은 대부분 이해하기 쉬운 형태로 가공해주지 않은 지식을 습득했다는 것에서 왔었다. 온전한 나만의 생각을 했던 시간은 거의 없었다. 생각을 너무 하지 않아서, 그동안 생각을 하지 않았단 것마저 글을 쓰면서 깨달았다.
그런데 제가 페어를 할 때 유안의 모습은 우테코 크루들 중 그 누구보다도 생각이 깊어보였습니다!

2020-03-30 09:04 UTC, woonjangahn commented on 레벨1.md
> +지금도 매일 생각의 재료로 사용할 지식들은 충분히 접하고 있다. 그런데 그때만큼 계속 생각하지 않는 이유는 열정의 차이라고 생각한다.
멋진 표현이네요 생각의 재료라니 💯

2020-03-30 09:23 UTC, ttkmw reviewed
인상적인 글이었습니다. 글을 읽고, 개인적으로 9개월 후 유안이 크게 성장해 있을 것이라고 확신했습니다. 유안이 열정있다는 것과 자기객관화를 하려고 노력한다는 것을 느꼈기 때문입니다.

생각의 재료, 생각의 계기라는 키워드가 기억에 남습니다. 유안은 현재 열정이 부족한 상태로 글을 썼다고 했지만, 저는 열정적이라고 느꼈어요. 어쩌면 생각의 계기가 있기 전까지는 열정이 부족한 상태였지만, 생각의 계기를 통해 열정이 생겼을 수도 있겠다는 생각이 듭니다. 이러한 맥락에서 생각의 계기를 능동적으로 찾는 것이 중요할 것 같습니다. 우테코 미션이 생각의 계기가 될 수 있을 것 같고요!

글 잘 읽었고, 피드백 남겨드렸으니 확인후 공감되시는 것을 선택적으로 반영해주시면 감사하겠습니다~

2020-03-30 09:23 UTC, p-vibe commented on 레벨1.md
> +내가 지금까지 받아온 교육들은 전부 의심하지 않고 잘 이해하는 것에 가장 큰 가치를 두었다. 그들은 지식을 이해하기 쉬운 형태로 가공해서 전달하는 것에만 집중했다. 우아한 테크코스에서는 기존의 지식을 의심하고 고민하는 것에 가치를 둔다. 이곳에서는 방향성만 잡아주고 지식을 필요이상으로 가공해서 떠먹여주지 않는다.
```suggestion
내가 지금까지 받아온 교육들은 전부 의심하지 않고 잘 이해하는 것에 가장 큰 가치를 두었다. 그들은 지식을 이해하기 쉬운 형태로 가공해서 전달하는 것에만 집중했다. 우아한 테크코스에서는 기존의 지식을 의심하고 고민하는 것에 가치를 둔다. 이곳에서는 방향성만 잡아주고 지식을 필요 이상으로 가공해서 떠먹여주지 않는다.
```

"그들"의 지칭이 애매한 것 같습니다. 맥락상 "이전 교육에서의 선생님들"을 뜻하는 것 같은데, "교육들"로 오해받을 수 있을 것 같아요. 의미를 명확히 해주시면 좋을 것 같습니다~! 그리고 띄어쓰기 수정해주시면 좋을 것 같아요.

2020-03-30 09:23 UTC, p-vibe commented on 레벨1.md
> +이런 환경 속에서 학습을 하다보니 나도 기존의 지식을 의심하고 충분히 고민하며 학습하고 있다고 생각했다. 하지만 level 1이 끝날 때 쯤 글을 작성하기 위해 내가 그동안 했던 생각들을 되돌아보니 그렇지 않다는 것을 깨달았다.
```suggestion
이런 환경 속에서 학습을 하다보니 기존의 지식을 의심하고 충분히 고민하며 학습하고 있다고 생각했다. 하지만 level 1이 끝날 때 쯤 글을 작성하기 위해 그동안 했던 생각들을 되돌아보니 그렇지 않다는 것을 깨달았다.
```
"나도", "내가" 는 없어도 될 것 같습니다!

2020-03-30 09:23 UTC, p-vibe commented on 레벨1.md
> +군대는 지적인 성장을 이루기에는 내 경험 중 최악의 환경이었다. 그 환경에 대한 반발심인지 지적 성장에 대한 열정이 어느때 보다 강했었다.
```suggestion
군대는 지적인 성장을 이루기에는 내 경험 중 최악의 환경이었다. 그 환경에 대한 반발심인지 지적 성장에 대한 열정이 어느 때보다 강했었다.
```

띄어쓰기 수정부탁해요~

2020-03-30 09:23 UTC, p-vibe commented on 레벨1.md
> +반면 우아한 테크코스의 성장에 좋은 환경은 나에게 안정감을 주었다. 그리고 안정감은 지속될 수록 간절함과 열정을 죽이고 있었다.
```suggestion
반면 우아한 테크코스의 성장에 좋은 환경은 나에게 안정감을 주었다. 그리고 안정감은 지속될수록 간절함과 열정을 죽이고 있었다.
```
띄어쓰기 수정 부탁해요~

2020-03-30 09:23 UTC, p-vibe commented on 레벨1.md
> +열정을 되찾기 위해 군대에서 가장 열정을 불러일으켜 주었던 책을 다시 샀다. 그 때만큼의 열정을 계속 유지할 수는 없겠지만 꾸준히 읽으면서 열정을 죽이지 않으려 한다.
```suggestion
열정을 되찾기 위해 군대에서 가장 열정을 불러일으켜 주었던 책을 다시 샀다. 그때만큼의 열정을 계속 유지할 수는 없겠지만 꾸준히 읽으면서 열정을 죽이지 않으려 한다.
```
띄어쓰기 수정 부탁해요~

2020-03-30 09:23 UTC, p-vibe commented on 레벨1.md
> +열정을 되찾기 위해 군대에서 가장 열정을 불러일으켜 주었던 책을 다시 샀다. 그 때만큼의 열정을 계속 유지할 수는 없겠지만 꾸준히 읽으면서 열정을 죽이지 않으려 한다.
여담인데, 제가 좋아하는 더콰이엇의 한번뿐인 인생이라는 노래에 "오랫동안 열정의 꽃에 물 주지 않았어 하지만 아직도 그 녀석은 죽지 않았어"라는 가사가 있는데요^^;;
느낌상 오래 쉬더라도 유안의 열정은 쉽게 죽지 않을 것 같다는 생각이 드네요.

2020-03-30 09:23 UTC, p-vibe commented on 레벨1.md
> +새삼스럽지만 정말 좋은 환경속에 운좋게 들어왔다고 생각한다. 좋은 방향으로 성장할 수 있도록 계속 유도해준다. 대놓고 가르쳐주거나 이끌어주지는 않지만 앞으로 사회에서 살아갈 것을 생각하면 오히려 좋다.
```suggestion
새삼스럽지만 정말 좋은 환경속에 운 좋게 들어왔다고 생각한다. 우테코는 좋은 방향으로 성장할 수 있도록 계속 유도해준다. 대놓고 가르쳐주거나 이끌어주지는 않지만 앞으로 사회에서 살아갈 것을 생각하면 오히려 좋다. 
```
띄어쓰기 수정 부탁해요~ 그리고 "좋은 방향으로~"의 문장에 주어가 들어가면 더 좋을 것 같습니다.

2020-04-01 08:01 UTC, ParkDooWon reviewed
안녕하세요 유안!
유안의 글 정말 잘 읽었습니다! :)
생각에 대한 이야기를 많이 써주셨는데, 평소에 저는 이런 생각조차 잘 하지않는다는 것을 이 글을 읽고 알았네요. 저도 생각을 좀 하고 살아봐야겠어요. 😅
글이 좋아서 피드백을 많이 드리지는 못했어요. 피드백 몇가지 확인 부탁드릴게요! 😄

2020-04-01 08:01 UTC, ParkDooWon commented on 레벨1.md
> +내가 지금까지 받아온 교육들은 전부 의심하지 않고 잘 이해하는 것에 가장 큰 가치를 두었다. 그들은 지식을 이해하기 쉬운 형태로 가공해서 전달하는 것에만 집중했다. 우아한 테크코스에서는 기존의 지식을 의심하고 고민하는 것에 가치를 둔다. 이곳에서는 방향성만 잡아주고 지식을 필요이상으로 가공해서 떠먹여주지 않는다.
```suggestion
내가 지금까지 받아온 교육들은 전부 의심하지 않고 잘 이해하는 것에 가장 큰 가치를 두었다. 그것들은 지식을 이해하기 쉬운 형태로 가공해서 전달하는 것에만 집중했다. 반면, 우아한 테크코스에서는 기존의 지식을 의심하고 고민하는 것에 가치를 둔다. 이곳에서는 방향성만 잡아주고 지식을 필요이상으로 가공해서 떠먹여주지 않는다.
```
1. `그들은`은 사람들을 말하는 것 같아요. 유안이 `교육들`을 말하는 것이라면 `그것들`은 이라고 하는 것이 나을 것 같아요. :)

2. 그리고 기존의 교육들과 비교되는 우테코 교육에 대한 이야기를 `반면`과 같은 접속사를 통해 이어주면 어떨까해요. :)

2020-04-01 08:01 UTC, ParkDooWon commented on 레벨1.md
> +반면 우아한 테크코스의 성장에 좋은 환경은 나에게 안정감을 주었다. 그리고 안정감은 지속될 수록 간절함과 열정을 죽이고 있었다.
주변 환경이 좋지않으면 열정이 생기고, 주변 환경이 좋으면 열정이 줄어드는거군요..
어려운 문제네요. 😢

2020-04-01 08:01 UTC, ParkDooWon commented on 레벨1.md
> +앞으로 남은 기간동안 충분히 생각하며 좋은 환경을 최대한 누려보려고 한다. 이 과정이 모두 끝났을 때 나만의 발전한 생각을 가지게 되기를 바란다.
```suggestion
앞으로 남은 기간동안 충분히 생각하며 좋은 환경을 최대한 누려보려고 한다. 이 과정이 모두 끝났을 때 나만의 발전한 생각을 가지기를 바란다.
```
요구사항에 따라 능동형으로 써주는 것이 더 좋을듯해요! :)

2020-04-02 02:08 UTC, KimSeongGyu1 commented on 레벨1.md
> +내가 지금까지 받아온 교육들은 전부 의심하지 않고 잘 이해하는 것에 가장 큰 가치를 두었다. 그들은 지식을 이해하기 쉬운 형태로 가공해서 전달하는 것에만 집중했다. 우아한 테크코스에서는 기존의 지식을 의심하고 고민하는 것에 가치를 둔다. 이곳에서는 방향성만 잡아주고 지식을 필요이상으로 가공해서 떠먹여주지 않는다.
교육들을 의도했었어요. 수정했어요.

2020-04-02 02:11 UTC, KimSeongGyu1 commented on 레벨1.md
> +이런 환경 속에서 학습을 하다보니 나도 기존의 지식을 의심하고 충분히 고민하며 학습하고 있다고 생각했다. 하지만 level 1이 끝날 때 쯤 글을 작성하기 위해 내가 그동안 했던 생각들을 되돌아보니 그렇지 않다는 것을 깨달았다.
'나도'는 강조를 위해 남기고 싶어서 남겼어요.

2020-04-02 05:04 UTC, ttkmw approved these changes
피드백 반영하신 것 확인했습니다.
저는 더이상 피드백할 것이 없어 어프루브합니다~

2020-04-02 05:19 UTC, ParkDooWon approved these changes
안녕하세요 유안! 피드백 반영하시느라 수고하셨어요!
더 이상 피드백 남길게 없네요. 정말 잘 쓰셨어요! 😄
approve 하겠습니다!

2020-04-03 01:57 UTC, KIMSIYOUNG approved these changes
안녕하세요 유안! 
지하철에서 잠깐 이야기했을 때도 느꼈지만 생각이 굉장히 깊은 분이신거 같아요.
깊은 생각속에 성장에 대한 갈망을 담고 있는 유안은 8개월뒤에 누구보다 빛나는 사람이 되지 않을까 예상해봅니다.
간단한 저의 생각들 남겼어요!ㅎㅎㅎ

2020-04-03 01:57 UTC, KIMSIYOUNG commented on 레벨1.md
> +성장하기 위해서는 충분히 생각하고 고민해보는 것이 중요하다고 생각한다. 그래서 다시 생각을 충분히 하기 위해 무엇이 필요한지 생각해보았다.
술에 취해 저와 같이 집을 가는 길에 유안은 누구보다 배움이 즐거워보였어요! 가공되지 않은 지식을 학습할 때도 아이처럼 즐거워 하는 모습을 가졌으니 행복한 10개월을 보내실 것 같아요.

2020-04-03 01:57 UTC, KIMSIYOUNG commented on 레벨1.md
> +지금도 매일 생각의 재료로 사용할 지식들은 충분히 접하고 있다. 그런데 그때만큼 계속 생각하지 않는 이유는 열정의 차이라고 생각한다.
열정의 차이라는 말 멋있어요!ㅎㅎㅎ
물론 유안이 생각하는 열정과 제 열정이 다를 수 도 있지만 조금 얘기하고 싶은 부분은 열정의 차이로 치부하기 시작하면 자신을 너무 몰아세우게 되는 것 같아요! 그러한 낭떠러지에서 성장하는 스타일이라면 문제가 없지만 그로 인해 지칠 수도 있다고 생각해요. 지금 불타오르는 열정은 꾸준히, 그리고 안정적으로 생각하는 연습을 하는 `습관`을 만드는데 소진하고 그 습관이 남은 기간을 지속하게 하는 것도 좋은 방법일 것 같아요ㅎㅎ

2020-04-03 01:57 UTC, KIMSIYOUNG commented on 레벨1.md
> +앞으로 남은 기간동안 충분히 생각하며 좋은 환경을 최대한 누려보려고 한다. 이 과정이 모두 끝났을 때 나만의 발전한 생각을 가지게 되기를 바란다.
유안은 충분히 할 수 있을것같아요ㅎㅎㅎㅎ 응원하겠습니다. 좋은 글 감사해요

2020-04-03 08:14 UTC, woonjangahn approved these changes
안녕하세요 유안! 피드백 반영해줘서 고맙습니다 💯 

평소의 침착한 유안의 모습이 글쓰기에도 잘 묻어난 것 같지만, 한편으로는 열정 넘치는 마라토너의 모습이 보였다고 해야할까요? 앞으로 8개월동안 더 성장할 유안의 모습이 기대되네요.

이만 Approve 하겠습니다. 좋은 글 읽게 해주셔서 감사합니다!

2020-06-10 07:31 UTC, woowahan-pjs approved these changes
오늘 유안의 열정은 어떤가요?

2020-06-10 07:31 UTC, merged