[빙봉] 레벨 3 - 회고 글쓰기 미션 제출합니다.
woowacourse/woowa-writing-2 pull request #131
Opened 2020-08-23 16:17 UTC by aegis1920

[여기](https://github.com/aegis1920/woowa-writing-2/blob/writing-aegis/LEVEL3.md)서 쉽게 보실 수 있어요 :)
피드백 부탁드립니다~ㅎㅎ

2020-08-23 16:53 UTC, fucct approved these changes
안녕하세요 빙봉! 디디입니다. 😄
길다면 길고 짧다면 짧은 기간이겠지만, 그동안 빙봉이 했던 걱정과 고민들이 글에 그대로 나타나네요. 
빙봉의 입장에서 읽으니깐 힘들었다는게 공감되는 글이었어요. 
그래도 성격도 실력도 좋은 갓 빙봉이라면 이겨낼 수 있을거라고 믿어요! 
남은 크루들과 똘똘 뭉쳐서 남은 기간동안 멋진 모습 보여줬으면 좋겠어요 👍
글 내용엔 딱히 어색하거나 이상하다고 느껴진 부분이 없어서 간단한 리뷰만 남겼습니다!
미리 approve 해놓도록 할게요. 좋은 글 잘 읽었습니다😊

2020-08-23 16:53 UTC, fucct commented on LEVEL3.md
> +팀 프로젝트는 대학교나 교육기관에서 꽤 쉽게 접할 수 있다. 나 또한 팀 프로젝트를 조금 경험해봤다. 레벨 3을 시작하기 전, 경험했던 팀 프로젝트를 떠올려봤다. 막상 떠올려보니 제대로 된 프로젝트 하나 개발한 경험이 없었다. 하더라도 배포도 못 하고 로컬에서 하다가 끝나거나 다른 친구가 먼저 취업해 프로젝트 자체가 흐지부지됐었다. 그래서 우테코 팀 프로
팀 프로젝트라는 단어가 반복되고 있는데, 생략하는 것도 나쁘지 않아 보여요! 😄

2020-08-23 16:53 UTC, fucct commented on LEVEL3.md
> +그 이후 팀원들과 함께 코치님들과 상담을 했고 갈등을 해소하는 데 도움을 주셨다. 도움을 주신 것에는 정말 너무나 감사하다. 다만 가끔 '이게 최선의 방법일까?'라는 생각이 들기도 한다. 기간이 짧게 정해진 우테코가 아니라 회사였다면 갈등 해결을 위해 다른 대안이 있지 않았을까?
빙봉의 가슴앓이가 느껴지는 문단이네요.. 😭 고생하신 게 느껴져서 마음이 아프네요..

2020-08-23 16:53 UTC, fucct commented on LEVEL3.md
> +> 4. 최고의 복지는 좋은 동료이며, 나 자신이 좋은 동료가 되기 위해 노력하자
최고의 복지는 연봉......이 아닌 동료군요!👍

2020-08-23 18:10 UTC, jnsorn requested changes
빙봉! 또 만났네요! 글 잘 읽었습니다! ㅎㅎ 어색하다고 느껴지는 부분에 코멘트 남겼으니 참고해주세요!

2020-08-23 18:10 UTC, jnsorn commented on LEVEL3.md
> +팀 프로젝트는 대학교나 교육기관에서 꽤 쉽게 접할 수 있다. 나 또한 팀 프로젝트를 조금 경험해봤다. 레벨 3을 시작하기 전, 경험했던 팀 프로젝트를 떠올려봤다. 막상 떠올려보니 제대로 된 프로젝트 하나 개발한 경험이 없었다. 하더라도 배포도 못 하고 로컬에서 하다가 끝나거나 다른 친구가 먼저 취업해 프로젝트 자체가 흐지부지됐었다. 그래서 우테코 팀 프로
디디와 같은 의견입니다!
```suggestion
팀 프로젝트는 대학교나 교육기관에서 꽤 쉽게 접할 수 있다. 나 또한 조금 경험해봤다. 레벨 3을 시작하기 전, 경험했던 팀 프로젝트를 떠올려봤다. 막상 떠올려보니 제대로 된 프로젝트 하나 개발한 경험이 없었다. 하더라도 배포도 못 하고 로컬에서 하다가 끝나거나 다른 친구가 먼저 취업해 프로젝트 자체가 흐지부지됐었다. 그래서 우테코 팀 프로젝트는 좀 더 신경 쓰고 제대로 하고 싶은 마음이 들었다.
```

추가로 `막상 떠올려보니 제대로 된 프로젝트 하나 개발한 경험이 없었다` 이 부분이 조금 어색하게 느껴져요!

2020-08-23 18:10 UTC, jnsorn commented on LEVEL3.md
> +정도가 될 것 같다. 나는 이 문장을 읽고 그 역할을 비단 리더뿐만 아니라 팀원들도 이런 생각을 하고 있으면 좋겠다는 생각이 들었다.
👍🏽

2020-08-23 18:10 UTC, jnsorn commented on LEVEL3.md
> +열정이 너무 과했던 걸까? 우리는 방학 때부터 열정을 불태웠고, 너무 불태운 건지 조금씩 부딪히기 시작했다. 서로의 의견을 말하고 반박하면서 편안한 분위기였던 팀플레이 속 불안감, 불편함이 조금씩 자리 잡고 있었다.
```suggestion
열정이 너무 과했던 걸까? 우리는 방학 때부터 열정을 불태웠고, 너무 불태운 탓인지 조금씩 부딪히기 시작했다. 서로의 의견을 말하고 반박하면서 편안한 분위기였던 팀플레이 속 불안감, 불편함이 조금씩 생겨나고 있었다.
```
조금 바꿔봤는데 어떤가요! 🙏🏻

2020-08-23 18:10 UTC, jnsorn commented on LEVEL3.md
> +이런 불안감, 불편함을 감정 회고에서 풀도록 노력했다. '갈등은 자연스러운 것이니 두려워하지 말자'라는 피드백도 하고 감정적으로 격앙될 때는 직접적으로 "지금 감정이 너무 올라와 있다. 조금 낮춰도 될 것 같다"라고 이야기하고, 서로 피드백을 주고, 팀 문화에 피드백을 추가하고 서로의 갈등이 없어지길 바랐다.
문장을 한 번 끊어도 될 것 같아요!
```suggestion
이런 불안감, 불편함을 감정 회고에서 풀도록 노력했다. '갈등은 자연스러운 것이니 두려워하지 말자'라는 피드백도 하고 감정적으로 격앙될 때는 직접적으로 "지금 감정이 너무 올라와 있다. 조금 낮춰도 될 것 같다"라고 이야기했다. 서로 피드백을 주고, 팀 문화에 피드백을 추가하고 서로의 갈등이 없어지길 바랐다.
```

2020-08-23 18:10 UTC, jnsorn commented on LEVEL3.md
> +물론 나도 갈등이 없진 않았다. 나름대로 갈등을 해결하기 위해 당사자와 일대일로 이야기도 하고 서로 다른 가치관을 이해하고 감정적으로 쿨하게 풀었으나 나만 푼다고 되는 문제가 아니었다.
```suggestion
물론 나도 갈등이 없진 않았다. 나름대로 갈등을 해결하기 위해 당사자와 일대일로 이야기도 하고 서로 다른 가치관을 이해했다. 또, 감정적으로 쿨하게 풀기도 했다. 하지만 나만 푼다고 되는 문제가 아니었다.
```
여기도 호흡이 길어서 한 번 끊어봤는데 여전히 어색하네요 😭 감정적으로 쿨하게 풀었다는 게 조금 추상적이어서 그런걸까요..?

2020-08-23 18:10 UTC, jnsorn commented on LEVEL3.md
> +솔직히 뿌듯했던 일보다는 아쉬운 점이 먼저 생각났다. 개발도 그렇고 커뮤니케이션도 그렇고. "그때 이렇게 얘기했다면 어땠을까?", "어떻게 하면 더 좋은 피드백을 줄 수 있었을까?", 하고 생각이 든다. 원래 지난 일은 깔끔하게 잊는 편이지만 왠지 이번 팀 프로젝트는 기억에 오래 남을 것 같다.
저와 같은 감정을 느끼셨군요! 😣

2020-08-24 02:56 UTC, lowoon approved these changes
안녕하세요 빙봉!
글 잘 읽었습니다 💯 
빙봉의 고민과 힘들었던 감정이 잘 느껴지는 글이었어요.
크게 리뷰할 내용은 없었고, 전체적으로 글이 살짝 긴듯한 느낌이 드는 문장들이 있었는데 그부분만 분리하면 좋을 것 같습니다!
글쓰기 미션 수고하셨습니다.

2020-08-24 02:56 UTC, lowoon commented on LEVEL3.md
> +이런 불안감, 불편함을 감정 회고에서 풀도록 노력했다. '갈등은 자연스러운 것이니 두려워하지 말자'라는 피드백도 하고 감정적으로 격앙될 때는 직접적으로 "지금 감정이 너무 올라와 있다. 조금 낮춰도 될 것 같다"라고 이야기하고, 서로 피드백을 주고, 팀 문화에 피드백을 추가하고 서로의 갈등이 없어지길 바랐다.
문장이 살짝 긴 것같아요.

2020-08-24 02:56 UTC, lowoon commented on LEVEL3.md
> +> 4. 최고의 복지는 좋은 동료이며, 나 자신이 좋은 동료가 되기 위해 노력하자
좋은 말들인 것 같아요! 👍

2020-08-24 04:03 UTC, icyMojito reviewed
빙봉! 쿨라임입니다 😇
글쓰기 주제 - 회고에 맞게 진솔하니 좋은 글을 써주셨네요! 💯
빙봉의 선한 성품과 함께 진한 아쉬움이 잘 느껴졌어요. 
이번 프로젝트를 통해 여러 모로 성장한 빙봉이 될 거라는 것도요 😎👍🏻
피드백 살짝 남겨놨으니 참조해 주세요~ 
이번 글쓰기 미션도 고생 많으셨습니다 👏🏻👏🏻👏🏻

2020-08-24 04:03 UTC, icyMojito commented on LEVEL3.md
> +팀 프로젝트를 진행하기 전, '코딩 호러의 이펙티브 프로그래밍'이라는 책을 읽었다. 이 책에는 코드에 대한 이야기도 있지만 '프로그래머를 제대로 채용하는 방법'이라든지, '팀이 함께 일하려면 어떻게 해야 되는지' 등등 여러 내용이 들어있다. 여러 내용 중에 내게 깨달음을 줬던 문장이 있다.
```suggestion
팀 프로젝트를 진행하기 전, '코딩 호러의 이펙티브 프로그래밍'이라는 책을 읽었다. 이 책에는 코드에 대한 이야기도 있지만 '프로그래머를 제대로 채용하는 방법'이라든지, '팀이 함께 일하려면 어떻게 해야 되는지' 등등 여러 내용이 들어있다. 그 중에 내게 깨달음을 줬던 문장이 있다.
```
'여러 내용'이 중복돼서 한 번 바꿔봤는데 어떤가요 🙃?!

2020-08-24 04:03 UTC, icyMojito commented on LEVEL3.md
> +정도가 될 것 같다. 나는 이 문장을 읽고 그 역할을 비단 리더뿐만 아니라 팀원들도 이런 생각을 하고 있으면 좋겠다는 생각이 들었다.
```suggestion
정도가 될 것 같다. 이 문장을 읽고 리더뿐만 아니라 팀원들도 이런 생각을 하고 있으면 좋겠다는 생각이 들었다.
```
'나는'이 빠져도 좋을 듯 합니다~ 그리고 '그 역할을' 부분이 정확히 어떤 의미인지 잘 모르겠어서 빼봤어요!
리더라는 역할에 대해 리더와 팀원들도 그런 생각을 하고 있으면 좋겠다는 건지,
아니면 리더와 팀원들도 리더와 같은 마음가짐이었으면 좋겠다는 건지요 🤩
(이어지는 문장을 보면 후자이려나요?)

2020-08-24 04:03 UTC, icyMojito commented on LEVEL3.md
> +이런 불안감, 불편함을 감정 회고에서 풀도록 노력했다. '갈등은 자연스러운 것이니 두려워하지 말자'라는 피드백도 하고 감정적으로 격앙될 때는 직접적으로 "지금 감정이 너무 올라와 있다. 조금 낮춰도 될 것 같다"라고 이야기하고, 서로 피드백을 주고, 팀 문화에 피드백을 추가하고 서로의 갈등이 없어지길 바랐다.
서로 피드백을 주고, 팀 문화에 피드백을 추가하고 서로의 갈등이 없어지길 바랐다.
-> (1안) 서로 피드백을 주고, 팀 문화에 피드백을 추가하면서 서로의 갈등이 없어지길 바랐다.
-> (2안) 팀 문화에 상호 간의 피드백을 추가해서 서로의 갈등이 없어지길 바랐다.

'피드백을 주고, 피드백을 추가하고'가 이어지는 게 살짝 어색해서 고쳐봤는데 빙봉 보기에도 괜찮을런지 모르겠어요 ☺️

2020-08-24 04:03 UTC, icyMojito commented on LEVEL3.md
> +물론 나도 갈등이 없진 않았다. 나름대로 갈등을 해결하기 위해 당사자와 일대일로 이야기도 하고 서로 다른 가치관을 이해하고 감정적으로 쿨하게 풀었으나 나만 푼다고 되는 문제가 아니었다.
```suggestion
물론 나도 갈등이 없진 않았다. 나름대로 갈등을 해결하기 위해 당사자와 일대일로 이야기도 하고 서로 다른 가치관을 이해하고자 노력했다. 그간 쌓였던 감정을 쿨하게 풀기도 했다. 하지만 나만 푼다고 되는 문제가 아니었다.
```
저도 이 문장 호흡이 길다 생각해서 나름대로 다듬어 봤어요, 검토 부탁드립니다아~

2020-08-24 04:58 UTC, aegis1920 commented on LEVEL3.md
> +팀 프로젝트는 대학교나 교육기관에서 꽤 쉽게 접할 수 있다. 나 또한 팀 프로젝트를 조금 경험해봤다. 레벨 3을 시작하기 전, 경험했던 팀 프로젝트를 떠올려봤다. 막상 떠올려보니 제대로 된 프로젝트 하나 개발한 경험이 없었다. 하더라도 배포도 못 하고 로컬에서 하다가 끝나거나 다른 친구가 먼저 취업해 프로젝트 자체가 흐지부지됐었다. 그래서 우테코 팀 프로
`막상 떠올려보니 제대로 된 프로젝트 하나 개발한 경험이 없었다` -> `생각해보니 제대로 된 프로젝트를 개발한 경험이 없었다.` 로 수정해보았습니다 :)

2020-08-24 05:04 UTC, aegis1920 commented on LEVEL3.md
> +열정이 너무 과했던 걸까? 우리는 방학 때부터 열정을 불태웠고, 너무 불태운 건지 조금씩 부딪히기 시작했다. 서로의 의견을 말하고 반박하면서 편안한 분위기였던 팀플레이 속 불안감, 불편함이 조금씩 자리 잡고 있었다.
`탓인지`로 수정했습니다! `자리 잡고 있다`는 개인적으로 어색한 부분이 없는 것 같긴하지만 `생겨나는` 게 문맥상 더 맞는 것 같아서 고쳤습니다 👍 조언 감사해요!

2020-08-24 05:05 UTC, aegis1920 commented on LEVEL3.md
> +열정이 너무 과했던 걸까? 우리는 방학 때부터 열정을 불태웠고, 너무 불태운 건지 조금씩 부딪히기 시작했다. 서로의 의견을 말하고 반박하면서 편안한 분위기였던 팀플레이 속 불안감, 불편함이 조금씩 자리 잡고 있었다.
`탓인지`로 수정했습니다! `자리 잡고` 부분은 그대로 가도 어색한 부분이 딱히 없는 것 같아서 그대로 가려고 합니다! 조언 감사해요! 👍

2020-08-24 05:07 UTC, aegis1920 commented on LEVEL3.md
> +이런 불안감, 불편함을 감정 회고에서 풀도록 노력했다. '갈등은 자연스러운 것이니 두려워하지 말자'라는 피드백도 하고 감정적으로 격앙될 때는 직접적으로 "지금 감정이 너무 올라와 있다. 조금 낮춰도 될 것 같다"라고 이야기하고, 서로 피드백을 주고, 팀 문화에 피드백을 추가하고 서로의 갈등이 없어지길 바랐다.
수정했어요! 감사합니다 👍

2020-08-24 05:17 UTC, aegis1920 commented on LEVEL3.md
> +물론 나도 갈등이 없진 않았다. 나름대로 갈등을 해결하기 위해 당사자와 일대일로 이야기도 하고 서로 다른 가치관을 이해하고 감정적으로 쿨하게 풀었으나 나만 푼다고 되는 문제가 아니었다.
다시 수정해봤습니닷!

2020-08-24 05:18 UTC, aegis1920 commented on LEVEL3.md
> +팀 프로젝트를 진행하기 전, '코딩 호러의 이펙티브 프로그래밍'이라는 책을 읽었다. 이 책에는 코드에 대한 이야기도 있지만 '프로그래머를 제대로 채용하는 방법'이라든지, '팀이 함께 일하려면 어떻게 해야 되는지' 등등 여러 내용이 들어있다. 여러 내용 중에 내게 깨달음을 줬던 문장이 있다.
좋은데요?? 👍

2020-08-24 05:25 UTC, aegis1920 commented on LEVEL3.md
> +정도가 될 것 같다. 나는 이 문장을 읽고 그 역할을 비단 리더뿐만 아니라 팀원들도 이런 생각을 하고 있으면 좋겠다는 생각이 들었다.
'리더는 사람들에게 번갈아 가며 질문을 던지고, 모든 사람의 의견을 구하고, 모두가 자기 목소리를 내게 해야 한다' 라고 했으니 팀원들도 그 행동(사람들에게 번갈아 가며 질문을 던지고, 모든 사람의 의견을 구하고, 모두가 자기 목소리를 내게 해야 한다)을 신경써줬으면 하는 생각에서 하는 말이었어요!

역할보다 행동이 더 이해하기 좋은 것 같아서 수정해봤습니다!

2020-08-24 05:29 UTC, aegis1920 commented on LEVEL3.md
> +이런 불안감, 불편함을 감정 회고에서 풀도록 노력했다. '갈등은 자연스러운 것이니 두려워하지 말자'라는 피드백도 하고 감정적으로 격앙될 때는 직접적으로 "지금 감정이 너무 올라와 있다. 조금 낮춰도 될 것 같다"라고 이야기하고, 서로 피드백을 주고, 팀 문화에 피드백을 추가하고 서로의 갈등이 없어지길 바랐다.
쿨라임이 제안한 것을 선택했습니다 👍

2020-08-24 05:30 UTC, aegis1920 commented on LEVEL3.md
> +물론 나도 갈등이 없진 않았다. 나름대로 갈등을 해결하기 위해 당사자와 일대일로 이야기도 하고 서로 다른 가치관을 이해하고 감정적으로 쿨하게 풀었으나 나만 푼다고 되는 문제가 아니었다.
수정해봤어요!

2020-08-24 05:39 UTC, icyMojito approved these changes
피드백 확인과 반영 고마워요 빙봉! 😆

2020-08-24 05:40 UTC, jnsorn approved these changes
수정본 확인 했습니다! 훨씬 읽기 편하고, 공감도 잘 되는 것  같아요!
특히, 소제목인 "감정은 갈등을 재귀 함수로 만드는 촉매제" 라는 표현이 인상 깊었어요!
초반엔 가볍고 즐겁게 시작되었다가, 글이 진행 될 수록 무겁고 어두워져서 몰입도있게 잘 읽었습니다.
이만 approve할게요!

2020-08-25 07:04 UTC, woowahanCU approved these changes
안녕하세요! 빙봉 
지난 기간 마음 고생했던 흔적들이 글의 횡간에 스며있네요 😭
성공한 프로젝트는 산출물을 남기지만, 
실패한 프로젝트는 다음을 위한 토양을 다지는 거 같아요.
저 역시 이전에 실패했던 프로젝트, 창업 등의 경험이 나중에 협업할 때 도움이 되더라구요.

물론 앞으로 레벨 4기간, 그리고 여러분의 의지가 있다면 그 이후로도 이 프로젝트는 이어지겠죠?
사실 프로젝트는 얼마나 꾸준히 사용자의 요구를 반영하며 개선되는가, 그래서 사용자가 기대한 부분을 충족하는가가 제일 중요하지요! 😬

이 시간들이 빙봉 자신에게도 유의미한 시간으로 갈무리하길 바래요~ 
레벨3 기간 목표한 바 잘 마무리하시고, 이후 계획도 차근차근 잘 진행하길! 😳
그동안 고생 많았어요 🙇🏻‍♂️ 
코로나가 좀 진정되면 같이 식사 한번 하지요! 🙏🏻

2020-08-25 07:05 UTC, merged