[엘리] 레벨3 - 회고 글쓰기 미션 제출합니다.
woowacourse/woowa-writing-2 pull request #132
Opened 2020-08-23 16:55 UTC by YebinK

2020-08-23 17:54 UTC, YejiAhn requested changes
팀장님ㅎㅎ 글쓰기 리뷰도 같은 팀이 되었군요!
순간순간의 기억들이 몽골몽골 피어올라서 좋네요 ~.~♥︎
간단한 코멘트 몇 개 달았습니다 확인해주세요 🙂

2020-08-23 17:54 UTC, YejiAhn commented on level3.md
> +10개의 최종 팀 안에 제 아이디어가 뽑힌 날, 눈앞이 깜깜했어요. 머릿속엔 "망했다, 튈까...? 아니지 그건 아니지.. 그럼 갈아엎을까?" 등 오만가지 생각이 들었어요. 저를 뽑아준 크루들에게 고맙기도 했지만 막막한 마음이 더 컸습니다. 솔직히 말하면, 제 아이디어가 뽑힐 거라고 전혀 생각하지 않았거든요. 가벼운 마음으로 적어냈던 기획서라 가볍게 떨어
ㅎㅎㅎ그랬어요? 우리 모든 팀원들의 1픽이었는데 말이쥬 🙃

2020-08-23 17:54 UTC, YejiAhn commented on level3.md
> +가장 먼저 한 일은 **팀장 없애기** 였어요. 어느샌가 팀원들 모두가 저에게 팀장이라고 부르고 있더군요...! ㅎㅎ 지금 생각해보면 아마도 제가 부끄러워 하니까 장난치려고 그랬던 것 같아요. 하지만 저는 모두가 팀장인 팀이 되고 싶었습니다. 여기서 팀장이란, 누군가에게 일을 시키는 사람이 아닙니다. 주인의식을 갖고 팀에 참여하는 사람이에요.
`하지만 저는 모두가 팀장인 팀이 되고 싶었습니다`
비문인 것 같아요!

2020-08-23 17:54 UTC, YejiAhn commented on level3.md
> +그래서 우리 팀을 만나고 **팀 프로젝트**에 대한 생각이 변했어요. 어쩌면 그동안 제 멋대로 다른 사람들을 재단하고 있었나봅니다.
팀프로젝트에 대한 생각이 어떻게 변했는지가 드러나면 더 좋을 것 같아요 🙂

2020-08-23 17:54 UTC, YejiAhn commented on level3.md
> +> 컨디션 이야기하는게 진부하면 정말 아무말이나 해보세요.
👍

2020-08-23 17:54 UTC, YejiAhn commented on level3.md
> +사실 요즘 깨어있는 시간 대부분을 팀 프로젝트 생각을 하면서 보내고 있어요. 그만큼 제가 우리 팀을 좋아한다는 것도 알았습니다. 이 노력을 팀원들이 전부 알아주고, 인정해주기 때문에 더욱 의욕이 생겨요. 이렇게 된 데에는 팀원 5명 전원의 노력이 담겨있지 않나 싶습니다. 레벨 1, 2 때는 새로운 기술을 매번 접하며 기술적인 발전을 많이 했다면, 레벨 3
팀워크 스킬에 대해서도 서술해주면 좋을것같네요!

2020-08-23 17:54 UTC, YejiAhn commented on level3.md
> +사실 요즘 깨어있는 시간 대부분을 팀 프로젝트 생각을 하면서 보내고 있어요. 그만큼 제가 우리 팀을 좋아한다는 것도 알았습니다. 이 노력을 팀원들이 전부 알아주고, 인정해주기 때문에 더욱 의욕이 생겨요. 이렇게 된 데에는 팀원 5명 전원의 노력이 담겨있지 않나 싶습니다. 레벨 1, 2 때는 새로운 기술을 매번 접하며 기술적인 발전을 많이 했다면, 레벨 3
저도 엘리가 있는 우리 팀이 참 좋아요 😃

2020-08-24 00:05 UTC, ordinCode approved these changes
엘리! 글을 읽는 동안에 엘리네 팀은 참 좋은 팀이라는 생각이 들었어요. 어떤 팀인지 궁금해짇더군요.
(물론 저희팀도 참 좋답니다!😉)

엘리가 성장하는데도 많이 도움이 되었던 경험이라 더 좋았던 것 같네요. 앞으로도 기대하겠습니다! 화이팅

2020-08-24 00:05 UTC, ordinCode commented on level3.md
> +잠시 옛날 이야기를 해볼게요. 우테코에 들어오기 전에는 **팀 프로젝트**라는 단어만 떠올리면 한숨부터 나왔어요. 대학교, 동아리 등 여러 팀 활동에서 제가 혼자 일을 도맡아 하는 경우가 많았거든요. 그래서 팀플이 끝나고 나면 결과물은 마음에 들지 몰라도, 팀원들과 친해졌다는 느낌은 받지 못했어요. 오히려 *다신 보지 말자* 라는 생각이 많이 들었죠. 이
저런ㅠㅠ

2020-08-24 00:05 UTC, ordinCode commented on level3.md
> +우리 팀은 각자 잘하는 분야가 달라요. 오구는 인프라 쪽에 관심이 많고, 우는 프론트엔드에 흥미를 느낍니다. 예지니어스는 처음 접하는 프레임워크를 사용하면서도 군더더기 없이 깔끔한 코드를 만들어내고, 레베카는 모든 예외상황까지 처리해 꼼꼼하게 코딩할 줄 알아요. 그래서 협업할 때 엄청난 시너지가 발생합니다. 서로 몰랐던 것에 대한 공유도 활발하고, 서로의
멋지네요

2020-08-24 09:47 UTC, taejinseok approved these changes
안녕하세요 엘리.
엘리의 모든 팀원들이 팀에 대한 애착이 강하게 느껴지는 마음 따뜻해지는 글 잘읽었습니다. 
특히 팀에 대한 감정의 변화가 너무 잘 드러났던것 같네요... 
Approve 하겠습니다. 남은 프로젝트 마무리 잘 하세요! 😀

2020-08-24 09:47 UTC, taejinseok commented on level3.md
> +제가 시작한 기획인만큼 **잘** 완성해야겠다는 생각이 강했어요. **잘**에는 많은 것들이 함축되어 있었습니다. 완성도 높은 코드, 사용성 좋은 서비스, 끈끈한 팀워크, 기술적인 배움 등 여러가지가 포함되어 있었어요. 팀이 결성된 초반에 혼자 너무 많은 생각을 했습니다. 그리고 그 생각이 곧 부담이 될 찰나였어요.
팀장이라는 무게감이 그대로 잘 드러나네요 ... 😂

2020-08-24 09:47 UTC, taejinseok commented on level3.md
> +제가 시작한 기획인만큼 **잘** 완성해야겠다는 생각이 강했어요. **잘**에는 많은 것들이 함축되어 있었습니다. 완성도 높은 코드, 사용성 좋은 서비스, 끈끈한 팀워크, 기술적인 배움 등 여러가지가 포함되어 있었어요. 팀이 결성된 초반에 혼자 너무 많은 생각을 했습니다. 그리고 그 생각이 곧 부담이 될 찰나였어요.
처음에 느꼈던 팀장의 무게감이 고스란히 드러나네요... 😂

2020-08-24 09:47 UTC, taejinseok commented on level3.md
> +팀과 전혀 관련 없는 이야기라도 합니다. 놀랍게도 생산성이 높아지기 시작했어요. 팀원들을 더 잘 이해할 수 있게 되었고, 점점 포비가 말했던 **심리적 안정감을 통해 어떠한 의견도 자유롭게 제시할 수 있는 분위기**가 되어갔습니다.
👍

2020-08-25 11:10 UTC, gracefulBrown approved these changes
데일리에 참여하면서 느꼈던 분위기가 글에서 나타나서 반갑네요🖐

매번 느끼는거지만 엘리는 팀을 정말 많이 생각하는거 같아요
글에서도 팀 프로젝트가 **나에게** 남긴 것이 아닌
팀 프로젝트가 **우리팀에게** 남긴 것인걸 봐도 알 수 있죠🤣

그러한 고민들이 팀장을 없애고 모두가 팀장인 팀을 만들었고
커뮤니케이션이 잘 되는 팀에 큰 기여를 하고 있는 것 같네요ㅎㅎ
(팀워크 효자상품에 쬐끔이라도 기여를 하게되어서 영광입니다ㅎㅎㅎㅎㅎ)

클래식과 함께하는 5000만원짜리 회고에 참여하지 못한게 아쉽네요ㅠ
다음에는 꼭 불러주세요ㅋㅋㅋ 
언젠가 될 지는 모를 워크샵을 기대하고 있겠습니다 :)

2020-08-25 11:10 UTC, merged