[우] 레벨1 - 기록 미션 제출합니다.
woowacourse/woowa-writing-2 pull request #32
Opened 2020-03-31 16:43 UTC by hwookim

잘부탁드립니다! ㅎㅎ

새벽 감성에 취해서 의식의 흐름대로 글을 작성했습니다.
많이 썼다고 생각했는데 다시 읽어보니 생각보다 짧네요...ㅠ
내일 스스로 퇴고하려고 하면 맘에 안들고 부끄러워 지울게 뻔해 새벽 감성에 취한 채로 PR까지 보냅니다.
많은 지적 부탁드려요!

2020-04-01 04:40 UTC, aegis1920 reviewed
안녕하세요 우! 빙봉입니다 :)
자신에 대해 깊은 생각이 느껴지는 글입니다 ㅎㅎ
피드백을 남겼으니 확인해주세요!

2020-04-01 04:40 UTC, aegis1920 commented on LEVEL1.md
> +사실, 때마다 그저 발 닿는 곳으로 걸어가며 살아온 덕분에 이유나 목표에 대한 깊은 고민이 없었다. 당장 먹을 점심 메뉴도 제대로 못 고르면서 먼 미래를 어떻게 생각하랴. 이런 생각으로 강물에 흐르듯 살아가고 있었다. 모터도 없이 결따라 흐르는 작은 나룻배가 지금의 나다.
마지막 문장의 표현이 너무 좋네요 👍

2020-04-01 04:40 UTC, aegis1920 commented on LEVEL1.md
> +## 그래서 뭘 해야하지?
전체적으로 '우아한 테크코스의 생활기' 보다는 의식적인 흐름이 많이 보이네요 :)
페어 프로그래밍이나 연극, 데일리 등등 우아한 테크코스에서 했던 일들을 주제로 생각해도 좋을 것 같아요!

2020-04-01 05:38 UTC, jamie9504 requested changes
읽어보았어요! 맞춤법을 잘 지키는 우!
뭔가 공감이 되는 포인트가 있어서 글이 잘 읽혔습니다!! :D

2020-04-01 05:38 UTC, jamie9504 commented on LEVEL1.md
> +## 그래서 뭘 해야하지?
`해야하지?` -> `해야 하지` 입니다!

2020-04-01 05:38 UTC, jamie9504 commented on LEVEL1.md
> +그러면 뭘 해야하나.
`해야하나.` -> `해야 하나.` 입니다!

2020-04-01 05:38 UTC, jamie9504 commented on LEVEL1.md
> +이런 생각을 하기엔 사실 할 게 많다. 지금 쓰는 글도 완성해야 하고, 들었던 강의들도 다시 한 번 정리해봐야 하고... 체스는 어떻게 웹을 적용할지 막막하기만 하다. 그런데도, 자꾸 할 게 없는 사람처럼 멍하게 된다. 정신을 차리고 나면 불안감에 휩싸인다.
`그런데도 자꾸 할 게 없는 사람처럼 멍해진다. 그리고 정신을 차리면 불안감에 휩싸인다.` 의 느낌은 어떨까요?(의견 제시)

2020-04-01 05:38 UTC, jamie9504 commented on LEVEL1.md
> +주변 크루들을 보면 다들 척척 해나가는 것 같다. 주어진 미션으로도 벅찬데, 스터디까지 하는 걸 보면 대단하기만 하다. 다들 어디론가 달려가는데 혼자서만 느긋하게 있던 건 아닐까.
오 이 생각은 저도 해본 적 있어요!

2020-04-01 10:46 UTC, KueNiYam reviewed
안녕하세요, 우!! 그니입니다. :)
문장이 전체적으로 깔끔하고 중간 중간 나오는 비유가 너무 좋아요. 💯 
개인적으로 삶은 계속해서 고민해야 하기에 매력적인 것 같아요.!

2020-04-01 15:17 UTC, hwookim commented on LEVEL1.md
> +## 그래서 뭘 해야하지?
주제를 보는 관점의 차이로 볼 수 있지 않을까요?
물론 과정도 서술할 수 있겠지만, 저는 생활한 후, 지금 제가 느낀 감정에 대해서 집중적으로 이야기 하고 싶었습니다.

그래도 확실히 너무 의식의 흐름대로만 흘러가긴 하네요....ㅠ
조금은 더 다듬어볼 수 있도록 고민하겠습니다!

2020-04-01 15:53 UTC, hwookim commented on LEVEL1.md
> +## 그래서 뭘 해야하지?
생각을 해보니, '생활기' 라는 말에는 빙봉의 의견이 확실히 부합한 것 같네요.
앞부분에는 전반적인 생활기를 적고, 뒷부분에는 지금 느낀 감정을 적는 방향으로 퇴고해보도록 하겠습니다.

2020-04-01 16:33 UTC, aegis1920 commented on LEVEL1.md
> +## 그래서 뭘 해야하지?
괜히 제가 부담을 준 것 같아 죄송할 따름입니다ㅜㅠ
말하신대로 앞 부분에는 생활기를 적고 뒷 부분에는 현재 글 그대로 가도 괜찮을 것 같아요 👍

2020-04-02 08:55 UTC, joseph415 approved these changes
안녕하세요 우! 서브웨이 입니다!
저는 빙봉과 다르게 의식의 흐름대로 쓴 글이 정말 좋게 느껴지네요!
많이 공감되고 잘 읽었습니다. 표현도 너무 좋고 읽기 좋은 글이라고 느껴지네요!
저는 여기서 approve하겠습니다!

2020-04-02 08:55 UTC, joseph415 commented on LEVEL1.md
> +주변 크루들을 보면 다들 척척 해나가는 것 같다. 주어진 미션으로도 벅찬데, 스터디까지 하는 걸 보면 대단하기만 하다. 다들 어디론가 달려가는데 혼자서만 느긋하게 있던 건 아닐까.
공감가는 부분이네요

2020-04-02 12:25 UTC, jnsorn reviewed
안녕하세요 우! 리뷰를 맡게 된 또링입니다.
글에서 우의 감정이 잘 느껴졌어요. 공감되는 부분도 많고, 감동받은 표현들도 많은 좋은 글이었습니다!
다만, 몇 가지 부분에 대해 저의 생각을 남겨두었으니 참고해주세요!

2020-04-02 12:25 UTC, jnsorn commented on LEVEL1.md
> +사실, 때마다 그저 발 닿는 곳으로 걸어가며 살아온 덕분에 이유나 목표에 대한 깊은 고민이 없었다. 당장 먹을 점심 메뉴도 제대로 못 고르면서 먼 미래를 어떻게 생각하랴. 이런 생각으로 강물에 흐르듯 살아가고 있었다. 모터도 없이 결따라 흐르는 작은 나룻배가 지금의 나다.
> 모터도 없이 결따라 흐르는 작은 나룻배가 지금의 나다.

마음에 드는 문장입니다👍

2020-04-02 12:25 UTC, jnsorn commented on LEVEL1.md
> +내가 해야 할 일이 뭔지에 대해 답할 수 없다면, 앞으로 해야 할 일은 그 대답을 찾는 것 아닐까.
> 내가 해야 할 일이 뭔지에 대해 답할 수 없다면, 앞으로 해야 할 일은 그 대답을 찾는 것 아닐까.

마음에 드는 문장입니다2 👍

2020-04-02 12:25 UTC, jnsorn commented on LEVEL1.md
> +물론 각자의 속도가 있고, 아직 자신의 페이스를 못 찾은 걸 거다. 코치들도 1기분들의 편지도, 남과 비교하며 초조해 하지 말라 하지 않았던가. 머리로는 괜찮다며 위로해 보지만 이미 생겨난 불안감은 계속 커져만 간다.
> 물론 각자의 속도가 있고, 아직 자신의 페이스를 못 찾은 걸 거다.

아직 자신의 페이스를 못 찾았다는 사람이 본인일까요 다른 크루들일까요? 애매하게 느껴져요🙂

2020-04-02 12:25 UTC, jnsorn commented on LEVEL1.md
> +물론 각자의 속도가 있고, 아직 자신의 페이스를 못 찾은 걸 거다. 코치들도 1기분들의 편지도, 남과 비교하며 초조해 하지 말라 하지 않았던가. 머리로는 괜찮다며 위로해 보지만 이미 생겨난 불안감은 계속 커져만 간다.
> 코치들도 1기분들의 편지도,

`1기들의`가 더 자연스러울 것 같아요!

2020-04-02 12:25 UTC, jnsorn commented on LEVEL1.md
> +불안감과 함께 생각이 많아졌다. 생각이 많아지다 보니 질문들이 자꾸 생겨났다. 답이 있을지는 모르겠다.
막막하고 불안한 감정이 잘 드러나네요 😥👍

2020-04-03 05:16 UTC, hwookim commented on LEVEL1.md
> +물론 각자의 속도가 있고, 아직 자신의 페이스를 못 찾은 걸 거다. 코치들도 1기분들의 편지도, 남과 비교하며 초조해 하지 말라 하지 않았던가. 머리로는 괜찮다며 위로해 보지만 이미 생겨난 불안감은 계속 커져만 간다.
적용했습니다!

2020-04-03 05:44 UTC, KueNiYam approved these changes

2020-04-03 06:08 UTC, aegis1920 approved these changes
안녕하세요 우! 빙봉입니다.
자신의 감정을 잘 전달한 글인 것 같아요 :)
피드백을 적용하니 글도 훨씬 깔끔해졌고요.
개인적으로 `모터도 없이 결따라 흐르는 작은 나룻배가 지금의 나다.` 표현이 너무 좋았어요
이만 approve 할게요! 수고하셨습니다~

2020-04-03 06:20 UTC, jamie9504 approved these changes
수정 확인 했습니다 :)

2020-04-03 06:29 UTC, jnsorn approved these changes
우, 또링입니다!
글 자체가 잘 읽히고 딱히 지적할만한 부분이 없어서 많이 코멘트를 못 남겼어요.😥

제가 마음에 드는 표현들 위주로 코멘트를 달아드렸는데,
우의 글을 읽으면서 정말 감정 묘사를 잘 하는 사람이라는 걸 알게 되었어요.

개인적으로 감정에 대해 말할 때 백 마디의의 구체적인 설명보다는 적절한 비유 하나가 더 심금을 울린다고 생각하는데, 우의 글이 딱 그랬던 것 같아요!

`고민하자.`

후회 없는 결정은 없다지만 우가 고민 끝에 내린 결정에는후회 대신 행복이 가득하길 응원하겠습니다😊

수고하셨어요. 이만 approve할게요!

2020-06-10 01:18 UTC, merged