[레벨1 - 기록] 동글 글쓰기 미션 제출합니다.
woowacourse/woowa-writing-2 pull request #46
Opened 2020-04-02 08:26 UTC by taejinseok

잘 부탁 드립니다 :)

2020-04-02 10:53 UTC, lxxjn0 requested changes
동글, 글 재밌게 읽었어요.

우리가 레벨 1동안 거쳤던 과정들을 조목조목 잘 설명해주어서 읽기 좋았네요!!
몇몇 문장과 띄어쓰기만 체크해뒀어요!! 확인 부탁드릴게요 👍

2020-04-02 10:53 UTC, lxxjn0 commented on level1.md
> +누군가와 함께 공부, 성장하고 싶은 바람은 우테코에 들어가고 싶은 절박함으로 변했다.
```suggestion
누군가와 함께 공부하며 성장하고 싶은 바람은 우테코에 들어가고 싶은 절박함으로 변했다.   
```

쉼표가 조금은 어색해서 `공부하며`로 고쳐봤어요!! 동글이 원하는 스타일대로 작성하시면 될 것 같아요.
참고하시라고 작성해두었습니다!!!

2020-04-02 10:53 UTC, lxxjn0 commented on level1.md
> +절박함 속에서 3개월의 선발과정 끝에 우테코 합격의 행운을 얻었다.
`절박함 속에서 3개월의 선발과정 끝에`라는 문장이 조금 어색한 것 같아요.

이 문장을 둘로 나눠보는 것도 좋을 것 같아요 :)

2020-04-02 10:53 UTC, lxxjn0 commented on level1.md
> +대표님의 말씀을 듣고 기대했던 이상의 환경 속에서 공부할 수 있다 확신했다.
`대표님의 말씀은 내가 품었던 기대를 확신으로 바꿔주었다.`와 같은 표현은 어떤가요?

2020-04-02 10:53 UTC, lxxjn0 commented on level1.md
> +    미션중, 생긴 궁금증은 직접 질문 대신 다른 크루들의 질문을 참조하며 해결했다.
```suggestion
    미션 중, 생긴 궁금증은 직접 질문 대신 다른 크루들의 질문을 참고하며 해결했다. 
```
띄어쓰기 체크해뒀어요!!
그리고 참조보다는 참고라는 단어가 더 적절한 것처럼 보이네요 :)

2020-04-02 11:04 UTC, jnsorn commented on level1.md
> +특히, 두 번째 페어 또링은 모든 내용을 노션을 통해 꼼꼼하게 정리했다.
😊😁😃😄😊☺

2020-04-02 12:06 UTC, LTTTTTE requested changes
안녕하세요 오구입니다.
우아한테크코스 한달 동안 동글이 노력한점과 아쉬웠던점을 솔직하게 잘적어주셨습니다.
읽으면서 어색했던 부분들 코멘트 남겨두었습니다.

2020-04-02 12:06 UTC, LTTTTTE commented on level1.md
> +우아한 테크코스(이하 우테코)에 지원하면서 가장 기대했던 것은 **함께 성장할 수 있는 환경**이었다.
저도 가장 기대했던 부분입니다

2020-04-02 12:06 UTC, LTTTTTE commented on level1.md
> +우테코는 임무 중심으로 이뤄지는데, 모든 미션은 페어와 진행한다. 즉, 페어 프로그래밍이 코스 과정에서 제일 큰 비중을 차지한다.
임무와 미션중 하나로 통일하면 좋을거 같아요

2020-04-02 12:06 UTC, LTTTTTE commented on level1.md
> +페어 프로그래밍에서 많은 것을 배울 방법을 고민했다.
이 문장만 봤을때 이해하기 힘든 문장 같아요

2020-04-02 12:06 UTC, LTTTTTE commented on level1.md
> +모든 페어들이 제각각 강점이 있었다. 페어가 사용하는 모르는 단축키 같은 사소한 것들도 흡수하고자 노력했다.
뒷문장을 읽었을때 어색했어요

2020-04-02 17:00 UTC, taejinseok commented on level1.md
> +    미션중, 생긴 궁금증은 직접 질문 대신 다른 크루들의 질문을 참조하며 해결했다.
국립국어원에서 찾아보니 
**참고**는   `살펴서 도움이 될 만한 재료로 삼음`,  
**참조**는 `참고로 비교하고 대조하여 봄`이라는 의미네요! 
문맥상 참고라는 단어가 적절하네요!  수정하겠습니다.

2020-04-03 03:44 UTC, dks301 reviewed
안녕하세요 동글 :)
시카입니다.

글이 전체적으로 간결해서 읽기가 편했습니다. 👍 
제가 읽다 어색한 부분만 코멘트 드렸어요 확인해주세요!

2020-04-03 03:44 UTC, dks301 commented on level1.md
> +대표님의 말씀을 듣고 기대했던 이상의 환경 속에서 공부할 수 있다 확신했다.
스티치의 피드백을 반영하면 의미가 없겠지만, `공부할 수 있다 확신했다.`를 그대로 가져가려면 문장이 어색해보여요.
```suggestion
대표님의 말씀을 듣고 기대했던 이상의 환경 속에서 공부할 수 있다고 확신했다.  
```
는 어떨까요?

2020-04-03 03:44 UTC, dks301 commented on level1.md
> +앞으로도 만날 페어로부터도 강점을 하나씩 흡수하도록 노력할 것이다. 더불어, 나만의 강점으로 페어들에게 좋은 영향을 미치고 싶다.
`페어로부터도`라는 표현이 뭔가 어색해보여요.
```suggestion
앞으로도 만날 페어들에게도 강점을 하나씩 흡수하도록 노력할 것이다. 더불어, 나만의 강점으로 페어들에게 좋은 영향을 미치고 싶다.   
```
는 어떨까요?

2020-04-03 04:19 UTC, JinJuMoon commented
안녕하세요, 동글!
동글의 생각이 잘 드러난 글이네요!
페어들의 장점을 흡수하는 모습이 인상적이였습니다👍
몇가지 피드백 남겼으니 동글이 공감하는 부분만 선택적으로 반영해주세요😄

2020-04-03 04:31 UTC, JinJuMoon approved these changes

2020-04-03 04:31 UTC, JinJuMoon commented on level1.md
> +    기록의 중요성을 인지한 뒤, 노션 페이지를 만들었다. 하지만 꾸준한 기록을 하지 않았다.
'꾸준히 기록하지 않았다'는 어떤가요? 문장이 보다 간결할 것 같아요!

2020-04-03 04:31 UTC, JinJuMoon commented on level1.md
> +우테코는 임무 중심으로 이뤄지는데, 모든 미션은 페어와 진행한다. 즉, 페어 프로그래밍이 코스 과정에서 제일 큰 비중을 차지한다.
저도 같은 생각이예요!😄

2020-04-03 04:31 UTC, JinJuMoon commented on level1.md
> +모든 페어들이 제각각 강점이 있었다. 페어가 사용하는 모르는 단축키 같은 사소한 것들도 흡수하고자 노력했다.
'제각각 강점이 있었다'를 '각자의 강점이 있었다'로 바꾸면 어떨까요? 현재 문맥에서는 각자의 라는 단어가 더 잘 어울리는 것 같아요!😄

2020-04-03 04:31 UTC, JinJuMoon commented on level1.md
> +    오늘부터는 하루의 느낀 점 한 줄 작성해야지.
'한 줄을 작성해야지'처럼 조사를 붙여주면 이해가 쉬울 것 같아요!

2020-04-03 06:22 UTC, JinJuMoon approved these changes
안녕하세요 동글 :)
무늬입니다.

동글의 솔직한 생각들이 잘 드러나는 글이었던 것 같아요!
페어의 장점을 흡수하려고 노력하는 동글의 모습이 참 인상적이네요. 👍 
그 외에도 우테코 생활에 대해 아쉬웠던 점을 회고하는 모습도 보기 좋았어요! 😄 

글을 더 이상 수정할 부분이 없네요 💯
저도 이만 approve할게요!

2020-04-03 06:31 UTC, taejinseok commented on level1.md
> +우테코는 임무 중심으로 이뤄지는데, 모든 미션은 페어와 진행한다. 즉, 페어 프로그래밍이 코스 과정에서 제일 큰 비중을 차지한다.
맞춤법 검사기를 돌리다가 저단어만 임무로 자동번역 됐네요.. 수정했습니다!

2020-04-03 06:33 UTC, taejinseok commented on level1.md
> +대표님의 말씀을 듣고 기대했던 이상의 환경 속에서 공부할 수 있다 확신했다.
이부분은 스티치의 피드백을 반영했어요! 
그래도 좋은 제안 주셔서 감사합니다!

2020-04-03 06:38 UTC, taejinseok commented on level1.md
> +    오늘부터는 하루의 느낀 점 한 줄 작성해야지.
조사가 들어가서 문장이 더 이해가 잘되는거 같네요! 
'그 수량이나 크기로 나뉘거나 되풀이됨' 의 뜻을 더하는 접미사  '씩'을 추가해 
`한 줄씩` 으로 변경했어요!

2020-04-03 07:17 UTC, LTTTTTE approved these changes
프리코스 시절 동글의 그 간절함이 우아한테크코스 10개월 과정 내내 유지될수 있다면, 이전의 동글보다 더 발전된 동글을 10개월뒤 볼수 있을꺼에요.
아쉬웠던 점들은 저랑 매우 공감이가서 다시 한번 생각에 잠기게 되는 글이네요.
노션정리 힘들지만 같이 꾸준히 해봐요!

글이 깔끔해서 approve 합니다

2020-04-03 08:20 UTC, lxxjn0 approved these changes
동글의 글 재밌게 읽었어요.
또링이 자기 이름 나왔다고 이모지 밑에 막 달아둔거 보니 참 웃기네요 :)

동글은 항상 푸근하고 좋은 인상을 지니고 있어서 친해지는데 어렵지 않았던 것 같아요!!
저도 페어들과 프로그래밍을 하면서 그들이 장점을 나도 가져보도록 노력하려고 했는데 쉽지 않네요.
그래서 동글이 이러한 부분에 대해 노력하는 모습이 정말 멋있어보여요.
앞으로 남은 8개월 모든 크루들의 장점을 다 흡수해서 멋진 개발자가 되길 기대할게요!!!

2020-04-03 08:20 UTC, dks301 approved these changes
안녕하세요 동글 :)
시카입니다.

수정한 글 잘봤습니다.
문장 사이가 잘 나뉘어 있어서 읽기 좋았어요! 💯 
환경에 대한건 저도 글에 쓰기도했고 공감도 많이되네요.
특히 '페어들의 장점을 하나씩 내 것으로 만들자'는 내용이 인상깊었어요
저도 한 번 도전해보고 싶습니다 😄 

이만 approve할게요!

2020-04-23 04:55 UTC, merged