[레벨1 - 기록] 디디 글쓰기 1단계 제출합니다.
woowacourse/woowa-writing-2 pull request #5
Opened 2020-03-23 08:12 UTC by fucct

감사합니다

2020-03-30 11:25 UTC, begaonnuri commented on writing.md
> +우아한 테크코스에 오기 전 프로그래밍은 학교 과제, 그 이상도 이하도 아니었다. 학교 수업을 듣다 보면 과제가 나온다. 과제를 하다보면 어느새 시험기간이다. 나름대로 열심히 공부하여 학점이란 보상으로 위안 삼았다. 하지만 그 과정에서 나는 내가 생각했던 개발자의 모습에선 멀어지고 있었다. 내가 입학할 때 생각했던 개발자는 무에서 유를 창조해내는 일종의 예
정말x100 공감되네요

2020-03-30 11:27 UTC, begaonnuri commented on writing.md
> +우아한 테크코스에 오기 전 프로그래밍은 학교 과제, 그 이상도 이하도 아니었다. 학교 수업을 듣다 보면 과제가 나온다. 과제를 하다보면 어느새 시험기간이다. 나름대로 열심히 공부하여 학점이란 보상으로 위안 삼았다. 하지만 그 과정에서 나는 내가 생각했던 개발자의 모습에선 멀어지고 있었다. 내가 입학할 때 생각했던 개발자는 무에서 유를 창조해내는 일종의 예
누나에게 💯 드리겠습니다

2020-03-30 11:31 UTC, begaonnuri commented on writing.md
> +사람은 적응의 동물이란 말이 사실 이였다. 낯설게만 느껴졌던 크루들도 어느새 나와 같은 길을 걷는 길동무로 느껴졌다. 처음 코드를 작성할 때 test 폴더에 먼저 손이 간다. 아침부터 저녁까지 시간을 순수하게 코딩에만 쏟는 날도 많아졌다. 처음 보는 사람에게 눈도 못 마주치던 내가 처음 보는 페어와 코드 설계를 하고 있다. 학교를 계속 다녔다면 상상도 못
다가갔을때 밀어내는 느낌이 없었는데, 의식적이였던거군요!
많은 고민이 있었을것같아요. 따봉 드리겠습니다👍🏻

2020-03-30 11:35 UTC, begaonnuri commented
디디, 글 잘 읽었습니다!
이번 미션은 딱히 피드백 드릴 점이 없네요 💯 
문장이 간결하고 이야기의 흐름을 따라갈 수 있어서 술술 읽혔습니다!

2020-03-30 11:41 UTC, begaonnuri approved these changes
디디, 글 잘 읽었습니다!
문장이 간결하고 이야기의 흐름을 따라갈 수 있어서 술술 읽혔습니다!
이번 미션은 딱히 피드백 드릴 점이 없네요 
이만, 머지할게요! 💯

2020-03-30 11:41 UTC, begaonnuri commented on writing.md
> +우아한 테크코스에 오기 전 프로그래밍은 학교 과제, 그 이상도 이하도 아니었다. 학교 수업을 듣다 보면 과제가 나온다. 과제를 하다보면 어느새 시험기간이다. 나름대로 열심히 공부하여 학점이란 보상으로 위안 삼았다. 하지만 그 과정에서 나는 내가 생각했던 개발자의 모습에선 멀어지고 있었다. 내가 입학할 때 생각했던 개발자는 무에서 유를 창조해내는 일종의 예
> 우아한 테크코스에 오기 전 프로그래밍은 학교 과제, 그 이상도 이하도 아니었다.

정말 공감되네요....

2020-03-30 11:41 UTC, begaonnuri commented on writing.md
> +우아한 테크코스에 오기 전 프로그래밍은 학교 과제, 그 이상도 이하도 아니었다. 학교 수업을 듣다 보면 과제가 나온다. 과제를 하다보면 어느새 시험기간이다. 나름대로 열심히 공부하여 학점이란 보상으로 위안 삼았다. 하지만 그 과정에서 나는 내가 생각했던 개발자의 모습에선 멀어지고 있었다. 내가 입학할 때 생각했던 개발자는 무에서 유를 창조해내는 일종의 예
누나에게 💯 드리겠습니다!

2020-03-30 11:41 UTC, begaonnuri commented on writing.md
> +사람은 적응의 동물이란 말이 사실 이였다. 낯설게만 느껴졌던 크루들도 어느새 나와 같은 길을 걷는 길동무로 느껴졌다. 처음 코드를 작성할 때 test 폴더에 먼저 손이 간다. 아침부터 저녁까지 시간을 순수하게 코딩에만 쏟는 날도 많아졌다. 처음 보는 사람에게 눈도 못 마주치던 내가 처음 보는 페어와 코드 설계를 하고 있다. 학교를 계속 다녔다면 상상도 못
다가갔을때 밀어내는 느낌이 없어서 몰랐는데, 의식적인 부분이였군요!
많은 고민이 있었을것같아요. 따봉 드리겠습니다! 👍

2020-03-30 11:41 UTC, begaonnuri commented on writing.md
> +나는 달릴 준비가 되었다.
달려가는 디디의 모습 기대하겠습니다!

2020-03-31 01:00 UTC, pci2676 requested changes
안녕하세요. 디디! 리뷰를 맡은 비밥입니다.
글에 몰입이 되서 재미있게 읽었습니다.
몇가지 부분에 대해 어색한 부분이 있어 리뷰하였습니다!
같이 열심히 해봐요!

2020-03-31 01:00 UTC, pci2676 commented on writing.md
> +우아한 테크코스에 오기 전 프로그래밍은 학교 과제, 그 이상도 이하도 아니었다. 학교 수업을 듣다 보면 과제가 나온다. 과제를 하다보면 어느새 시험기간이다. 나름대로 열심히 공부하여 학점이란 보상으로 위안 삼았다. 하지만 그 과정에서 나는 내가 생각했던 개발자의 모습에선 멀어지고 있었다. 내가 입학할 때 생각했던 개발자는 무에서 유를 창조해내는 일종의 예
디디는 처음부터 개발자가 꿈이었나보네요!
저는 입학 할 때 이런 생각을 가지지 못했었는데 대단하네요!

2020-03-31 01:00 UTC, pci2676 commented on writing.md
> +살면서 클린 코드라는 말을 처음 들어 봤다. 동작만 되면 되지. 저게 뭐가 중요해? 아는 만큼 보인다. 나는 아는게 없었다. 객체 지향에 대해 깊게 고민해본적 없었다. 같이 코드를 짜본적도  없다.  남들과 코드 설계에 대해 토론을 나눠 본 적도 없었다. 우아한 테크코스에선 이 모든 것을 동시에 했다. 첫 주부터 시작한 TDD부터 모든게 낯설었다. 코드를
연극! 저도 당황스러웠던 기억이 나네요!

2020-03-31 01:00 UTC, pci2676 commented on writing.md
> +사람은 적응의 동물이란 말이 사실 이였다. 낯설게만 느껴졌던 크루들도 어느새 나와 같은 길을 걷는 길동무로 느껴졌다. 처음 코드를 작성할 때 test 폴더에 먼저 손이 간다. 아침부터 저녁까지 시간을 순수하게 코딩에만 쏟는 날도 많아졌다. 처음 보는 사람에게 눈도 못 마주치던 내가 처음 보는 페어와 코드 설계를 하고 있다. 학교를 계속 다녔다면 상상도 못
```suggestion
사람은 적응의 동물이란 말이 사실이었다. 낯설게만 느껴졌던 크루들도 어느새 나와 같은 길을 걷는 길동무로 느껴졌다. 처음 코드를 작성할 때 test 폴더에 먼저 손이 간다. 아침부터 저녁까지 시간을 순수하게 코딩에만 쏟는 날도 많아졌다. 처음 보는 사람에게 눈도 못 마주치던 내가 처음 보는 페어와 코드 설계를 하고 있다. 학교를 계속 다녔다면 상상도 못할 일이다. 한 달 남짓한 시간 동안 나는 많이 변해 있었다.
```

사소한 오타가 있네요!

2020-03-31 01:00 UTC, pci2676 commented on writing.md
> +인상깊은 경험은 첫 번째로 기억은 개발 그 자체를 공부하는 환경이다. 학교는 개발을 가르치지 않는다. 내가 지금까지 학교에서 배운건 개발이 아닌 공학 이였다. 우아한 테크코스에서 가장 많이 배운 건 말 그대로 개발이 아닐까 싶다.
```suggestion
첫 번째 인상깊은 경험은 개발을 공부하는 환경이다. 학교는 개발을 가르치지 않는다. 내가 지금까지 학교에서 배운건 개발이 아닌 공학 이였다. 우아한 테크코스에서 가장 많이 배운 건 말 그대로 개발이 아닐까 싶다.
```

개발을 공부하는 환경에 대해 강조하려 한것인가요?
~은 ~은 이 두번 연속으로 나와서 헷갈렸어요.
위와 같이 바꿔도 의미전달은 충분히 되지 않을까요?
제 생각이랍니다!

2020-03-31 01:00 UTC, pci2676 commented on writing.md
> +세 번째는 크루들의 특징이다. 그 중 로또 게임 미션 때 페어였던 카일이 인상깊었다. 카일은 꼼꼼하고, 완벽한 설계를 추구한다. 끝까지 집중력을 잃지 않고 코딩을 한다. 지속적으로 부족한 점을 리팩토링한다. 한 줄 한 줄 보면서 문제점을 찾아낸다. 끊임없이 책을 읽는다. 모든 것이 나와 정반대여서 많은 걸 배웠다.
저도 카일과 페어해보고 싶네요!

2020-03-31 01:00 UTC, pci2676 commented on writing.md
> +마지막으로 코드 리뷰이다. 여태까지 내 코드를 보고 평가를 해준 사람은 거의 없었다. 있었다고 해봤자 제출한 과제의 컴파일 오류를 체크해주는 조교가 전부였다. 내가 짠 코드의 문제점을 바로바로 피드백 받을 수 있어 미션 마다 성장하는 기분이 들었다.
공감합니다! 하루하루 성장하는 기분이죠!

2020-03-31 01:32 UTC, fucct commented on writing.md
> +인상깊은 경험은 첫 번째로 기억은 개발 그 자체를 공부하는 환경이다. 학교는 개발을 가르치지 않는다. 내가 지금까지 학교에서 배운건 개발이 아닌 공학 이였다. 우아한 테크코스에서 가장 많이 배운 건 말 그대로 개발이 아닐까 싶다.
좋은 지적 감사합니다👍

2020-04-01 00:40 UTC, fucct commented on writing.md
> +사람은 적응의 동물이란 말이 사실 이였다. 낯설게만 느껴졌던 크루들도 어느새 나와 같은 길을 걷는 길동무로 느껴졌다. 처음 코드를 작성할 때 test 폴더에 먼저 손이 간다. 아침부터 저녁까지 시간을 순수하게 코딩에만 쏟는 날도 많아졌다. 처음 보는 사람에게 눈도 못 마주치던 내가 처음 보는 페어와 코드 설계를 하고 있다. 학교를 계속 다녔다면 상상도 못
어이쿠 감사합니다

2020-04-01 02:00 UTC, pci2676 approved these changes
같이 열심히 해봐요!

2020-04-01 02:37 UTC, ddaaac approved these changes
굉장히 공감되는 게 많은 글이었습니다. 비슷하게 생각했지만 저는 미처 다 표현하지 못했던 생각들도 글에 잘 녹여내신 것 같아요 :) 저도 같이 달려갈 수 있는 크루가 될 수 있도록 열심히 해야겠네요. 응원합니다!

(우리 루루도 많이 봐주세요 🐱)

2020-04-01 02:37 UTC, ddaaac commented on writing.md
> +우아한 테크코스에 오기 전 프로그래밍은 학교 과제, 그 이상도 이하도 아니었다. 학교 수업을 듣다 보면 과제가 나온다. 과제를 하다보면 어느새 시험기간이다. 나름대로 열심히 공부하여 학점이란 보상으로 위안 삼았다. 하지만 그 과정에서 나는 내가 생각했던 개발자의 모습에선 멀어지고 있었다. 내가 입학할 때 생각했던 개발자는 무에서 유를 창조해내는 일종의 예
제가 학교다니던 모습 같네요... 너무 공감됩니다 😢

2020-04-01 02:37 UTC, ddaaac commented on writing.md
> +우아한 테크코스에 대해 검색해 봤다. 개발자 교육이라고 한다. 방학 동안 한 두달 하나 보다. 지원했다. 이게 웬걸 무려 10개월이나 한단다. 덜컥 겁이 났다. 이 교육을 들으면 졸업은 언제하지? 친구들은 이미 다 취직했는데 난 뭐하는 거지? 이 나이 먹고 더 놀아도 되나? 3주차 프리 코스 까지 정말 고민을 많이 했던것 같다. 누나가 이만한 기회는 다시
```suggestion
누나의 이만한 기회는 다시 잡기 힘들다는 조언에 우아한 테크코스에 도전하기로 결심 했다.  
```
위와 같이 문장을 바꾸는게 조금 더 자연스러울 것 같아요!

2020-04-01 02:37 UTC, ddaaac commented on writing.md
> +사람은 적응의 동물이란 말이 사실이었다. 낯설게만 느껴졌던 크루들도 어느새 나와 같은 길을 걷는 길동무로 느껴졌다. 처음 코드를 작성할 때 test 폴더에 먼저 손이 간다. 아침부터 저녁까지 시간을 순수하게 코딩에만 쏟는 날도 많아졌다. 처음 보는 사람에게 눈도 못 마주치던 내가 처음 보는 페어와 코드 설계를 하고 있다. 학교를 계속 다녔다면 상상도 못할
저도 여기와서 이런 고민을 처음 해봤던게 기억나네요.
크루들을 길동무로 표현한 점이 인상깊습니다!  공감되네요 👍

2020-04-01 02:37 UTC, ddaaac commented on writing.md
> +세 번째는 크루들의 특징이다. 그 중 로또 게임 미션 때 페어였던 카일이 인상깊었다. 카일은 꼼꼼하고, 완벽한 설계를 추구한다. 끝까지 집중력을 잃지 않고 코딩을 한다. 지속적으로 부족한 점을 리팩토링한다. 한 줄 한 줄 보면서 문제점을 찾아낸다. 끊임없이 책을 읽는다. 모든 것이 나와 정반대여서 많은 걸 배웠다.
카일이랑 페어... 좋습니다...

2020-04-01 11:23 UTC, DunDung approved these changes
전체적으로 완전 공감가는 글이였습니다..!
공감가게 글을 쓰는 것도 능력인 것 같아요!
제 얘기를 잘 쓴 글로 읽는 듯한 기분이 들었습니다.
재미있게 읽었어요!

2020-04-01 11:23 UTC, DunDung commented on writing.md
> +우아한 테크코스에 오기 전 프로그래밍은 학교 과제, 그 이상도 이하도 아니었다. 학교 수업을 듣다 보면 과제가 나온다. 과제를 하다보면 어느새 시험기간이다. 나름대로 열심히 공부하여 학점이란 보상으로 위안 삼았다. 하지만 그 과정에서 나는 내가 생각했던 개발자의 모습에선 멀어지고 있었다. 내가 입학할 때 생각했던 개발자는 무에서 유를 창조해내는 일종의 예
>내가 입학할 때 생각했던 개발자는 무에서 유를 창조해내는 일종의 예술가였다. 내가 생각했던 개발자는 학점을 위해 코드를 베끼지 않는다. 내가 생각했던 개발자는 시험을 위해 코드를 외우지 않는다. 내가 생각했던 개발자는 취직을 위해 알고리즘 문제를 하루종일 풀지 않는다. 당시의 내 모습이 그랬다.

디디 모습 == 제 모습
공감이 많이 되네요..

2020-04-01 11:23 UTC, DunDung commented on writing.md
> +우아한 테크코스에 대해 검색해 봤다. 개발자 교육이라고 한다. 방학 동안 한 두달 하나 보다. 지원했다. 이게 웬걸 무려 10개월이나 한단다. 덜컥 겁이 났다. 이 교육을 들으면 졸업은 언제하지? 친구들은 이미 다 취직했는데 난 뭐하는 거지? 이 나이 먹고 더 놀아도 되나? 3주차 프리 코스 까지 정말 고민을 많이 했던것 같다. 이만한 기회는 다시 잡기
저도 프리코스를 하면서 고민을 했던 기억이 나네요..

디디는 누나에게 밥이라도 한 번 사야 될 듯 합니다..!

2020-04-01 11:23 UTC, DunDung commented on writing.md
> +살면서 클린 코드라는 말을 처음 들어 봤다. 동작만 되면 되지. 저게 뭐가 중요해? 아는 만큼 보인다. 나는 아는게 없었다. 객체 지향에 대해 깊게 고민해본적 없었다. 같이 코드를 짜본적도  없다.  남들과 코드 설계에 대해 토론을 나눠 본 적도 없었다. 우아한 테크코스에선 이 모든 것을 동시에 했다. 첫 주부터 시작한 TDD부터 모든게 낯설었다. 코드를
`동작만 되면 되지.` -> 제 생각에는 `동작만 하면 되지` 가 더 자연스러운 것 같아요!

2020-04-01 11:23 UTC, DunDung commented on writing.md
> +살면서 클린 코드라는 말을 처음 들어 봤다. 동작만 되면 되지. 저게 뭐가 중요해? 아는 만큼 보인다. 나는 아는게 없었다. 객체 지향에 대해 깊게 고민해본적 없었다. 같이 코드를 짜본적도  없다.  남들과 코드 설계에 대해 토론을 나눠 본 적도 없었다. 우아한 테크코스에선 이 모든 것을 동시에 했다. 첫 주부터 시작한 TDD부터 모든게 낯설었다. 코드를
>나는 아는게 없었다. 객체 지향에 대해 깊게 고민해본적 없었다. 같이 코드를 짜본적도  없다.  남들과 코드 설계에 대해 토론을 나눠 본 적도 없었다. 우아한 테크코스에선 이 모든 것을 동시에 했다.

저도 공감되네요.. 전공자인데 왜 이런 걸 안했을까요ㅠㅠㅠ

2020-04-01 11:23 UTC, DunDung commented on writing.md
> +사람은 적응의 동물이란 말이 사실이었다. 낯설게만 느껴졌던 크루들도 어느새 나와 같은 길을 걷는 길동무로 느껴졌다. 처음 코드를 작성할 때 test 폴더에 먼저 손이 간다. 아침부터 저녁까지 시간을 순수하게 코딩에만 쏟는 날도 많아졌다. 처음 보는 사람에게 눈도 못 마주치던 내가 처음 보는 페어와 코드 설계를 하고 있다. 학교를 계속 다녔다면 상상도 못할
> 처음 코드를 작성할 때 test 폴더에 먼저 손이 간다.

TDD를 잘하시는 군요.. 닉값... 👍

2020-04-01 11:23 UTC, DunDung commented on writing.md
> +첫번째 인상깊은 경험은 개발 그 자체를 공부하는 환경이다. 학교는 개발을 가르치지 않는다. 내가 지금까지 학교에서 배운건 개발이 아닌 공학 이였다. 우아한 테크코스에서 가장 많이 배운 건 말 그대로 개발이 아닐까 싶다.
학교에서 배운건 개발이 아니라 공학이였다는 말, 정말 공감됩니다!

2020-04-01 11:23 UTC, DunDung commented on writing.md
> +마지막으로 코드 리뷰이다. 여태까지 내 코드를 보고 평가를 해준 사람은 거의 없었다. 있었다고 해봤자 제출한 과제의 컴파일 오류를 체크해주는 조교가 전부였다. 내가 짠 코드의 문제점을 바로바로 피드백 받을 수 있어 미션 마다 성장하는 기분이 들었다.
학교에서는 코드를 보지않고, 돌아가는지만 확인해주죠...
성장하는 기분까지도 너무 공감됩니다.

2020-04-01 11:23 UTC, DunDung commented on writing.md
> +고작 한 달이 지났다. 다른 사람들이 보는 난 병아리에 불과하다. 그러나 나는 분명 한 달 전과 다르다. 내 안에선 개발자 라는 목적지가 생겼다. 꿈을 향해 달려갈 트랙이 있다. 함께 달려갈 러닝 메이트들이 있다.
제가 볼때 디디는 벌써 수탉입니다.
같이 목적지를 향해 열심히 뛰어보아요..!

2020-04-03 09:56 UTC, gracefulBrown approved these changes
담백한 문체로 작성해주었네요! 몰입감 있게 읽었습니다 :) 달릴 준비가 된 디디를 응원할게요~ㅎㅎ

2020-04-03 09:56 UTC, gracefulBrown commented on writing.md
> +두 번째는 자유이다. 학교에선 최대한 짧은 시간에 효율적으로 지식을 전달한다. 전달하는 지식도 교수님의 마음이다. 성취도를 평가하는 방식도 교수님 마음이다. 하지만 우아한 테크코스는 다르다. 미션을 던져주고 자유롭게 공부한다. 심지어 공부 하는 것도 자유이다. 공부한 내용을 바탕으로 코드를 짜는 방식도 자유이다. 여기선 무엇이든 할 수 있다.
> 여기선 무엇이든 할 수 있다.

울림이 있는 문장이네요ㅎㅎ

2020-06-10 01:13 UTC, merged