[레벨1 - 기록] 오렌지 글쓰기 미션 제출합니다.
woowacourse/woowa-writing-2 pull request #50
Opened 2020-04-02 12:15 UTC by YerinCho

긴 글 읽어 주셔서 감사합니다 :)

https://github.com/woowacourse/woowa-writing-2/compare/yerincho...YerinCho:yerincho?diff=unified&expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8

2020-04-02 13:20 UTC, chomily requested changes
안녕하세요 오렌지 😊  쪼밀리입니다!

글 잘 읽었어요.
바쁜 와중에 글 쓰느라 수고 많았어요!
오렌지의 말이 들리는 것 같았어요 ㅎㅎ
피드백 남겨두었으니 확인하시고,
궁금한 것 있으면 얘기해주세요 :)

2020-04-02 13:20 UTC, SujinEmilyCho commented on README.md
> +두근두근, 드디어 숫자야구게임이 시작됐다. 첫 언어는 C, 수업의 과제만 해 왔기 때문에 주 언어도 C. 객체지향? 알지만 잘 몰랐다. MVC 디자인패턴? 들어 본 적도 없었다. 클래스를 다섯 개 이상 만들어서 구현해 본 적도 없었다. API를 사용할 줄도 몰랐고, 스트림을 써대는데 이게 무슨 말인지. 머리가 핑핑 돌았다. 자존심이 상했지만 다른 사람의
띄어쓰기 `참고할 수밖에` 입니다 :)

2020-04-02 13:20 UTC, SujinEmilyCho commented on README.md
> +2019년 10월, 학교에서 알고리즘 수업을 듣고 건물을 나오려는 순간, 게시판에 붙어있는 포스터를 발견한다. ``와! 재밌겠다!`. 그전까지 취업과 내 진로는 안갯속을 헤쳐나가듯 보이지 않고 까마득했다. 사실 지금도 명확하진 않다. 정말 뭐하고 먹고 살아야 하지? 많이 부족한 전공지식, 그저 그런 학점, 심지어 개발 경험은 제로에 가까웠다. 내가 해봤던
작은 따옴표가 2개 잘 못 들어갔어요 !

2020-04-02 13:20 UTC, SujinEmilyCho commented on README.md
> +2019년 10월, 학교에서 알고리즘 수업을 듣고 건물을 나오려는 순간, 게시판에 붙어있는 포스터를 발견한다. ``와! 재밌겠다!`. 그전까지 취업과 내 진로는 안갯속을 헤쳐나가듯 보이지 않고 까마득했다. 사실 지금도 명확하진 않다. 정말 뭐하고 먹고 살아야 하지? 많이 부족한 전공지식, 그저 그런 학점, 심지어 개발 경험은 제로에 가까웠다. 내가 해봤던
python 오타났어요!

2020-04-02 13:20 UTC, SujinEmilyCho commented on README.md
> +두근두근, 드디어 숫자야구게임이 시작됐다. 첫 언어는 C, 수업의 과제만 해 왔기 때문에 주 언어도 C. 객체지향? 알지만 잘 몰랐다. MVC 디자인패턴? 들어 본 적도 없었다. 클래스를 다섯 개 이상 만들어서 구현해 본 적도 없었다. API를 사용할 줄도 몰랐고, 스트림을 써대는데 이게 무슨 말인지. 머리가 핑핑 돌았다. 자존심이 상했지만 다른 사람의
지원서 이야기를 하다가 갑자기 숫자야구게임으로 연결되니 흐름이 어색해요!
중간에 완충할 수 있는 단어를 추가해서 연결해보아요!

2020-04-02 13:20 UTC, SujinEmilyCho commented on README.md
> +그렇지만, 나만의 그런 이유로 이들의 열정을 무시하기란 어려웠다. 오히려 뜨거운 분위기가 내 온몸을 감싸 돌았다. 크루들의 열정은 충분한 영향력이며, 누군가가 귀 바로 옆에서 계속 말하는 듯한 자극이다. 누군가의 모습이 나에게 멋져 보이고, 성장 촉진제가 된다면 나도 모르게 따라 한다. 여기서 닉네임을 언급하긴 부끄럽지만, 많은 크루들이 나에게 그런 존재
나만의 그런 이유가 무엇일까요 ? 😊

2020-04-02 13:20 UTC, SujinEmilyCho commented on README.md
> +앞에서 말했다시피, 스트레스받는 것을 매우 싫어하는 사람이다. 이에 깊게 생각하려 하지 않는다. 항상 단순하게 생각하고 즉흥적으로 행동한다. 무언가를 하려고 하면 곧잘 따라 하고 이해도도 높지만, 스스로의 기준으로 봤을 때는 끈기와 열정이 부족한 사람이다. 여기서도 마찬가지다. 매일매일 남아서 공부하는 크루들, 이미 많은 것을 알고 온 열정적인 크루들 투
끈기와 열정에 대해서 이야기하다가, 그러나 나는 첫 발걸음을 뗐고 부족한 사람일 뿐이다라고 결론이 나는게 어색해요...!

2020-04-02 13:20 UTC, SujinEmilyCho commented on README.md
> +그렇지만, 나만의 그런 이유로 이들의 열정을 무시하기란 어려웠다. 오히려 뜨거운 분위기가 내 온몸을 감싸 돌았다. 크루들의 열정은 충분한 영향력이며, 누군가가 귀 바로 옆에서 계속 말하는 듯한 자극이다. 누군가의 모습이 나에게 멋져 보이고, 성장 촉진제가 된다면 나도 모르게 따라 한다. 여기서 닉네임을 언급하긴 부끄럽지만, 많은 크루들이 나에게 그런 존재
그들과 나를 비교하지'는' 않는다.
'는'이 추가되면 의미가 더 정확히 전달될 것 같아요 :)

2020-04-02 13:20 UTC, SujinEmilyCho commented on README.md
> +나도 그들 같은 열정맨이 되기엔 한없이 부족하다. 그러나 크루들과 함께 지낼 남은 날들이 기대된다. 우아한 테크코스가 끝난 후의 모습이 기대된다. 우아한 테크코스는 학습적 성장은 물론, 어리고 철없는 오렌지의 정신적 성장의 원동력이 되기에 충분하다. 덕분에 항상 스스로를 되돌아보고 반성한다.
앞으로 남은 날들도 화이팅입니다 😆

2020-04-03 01:18 UTC, lowoon approved these changes
안녕하세요 오렌지! 로운이에요.
글 잘읽었습니다!
항상 에너지 넘치는 오렌지인데 글 읽다가 열정 부분에서 놀랐네요.
간단한 피드백 남겼습니다.
궁금한 점 있으면 얘기해주세요.

2020-04-03 01:18 UTC, lowoon commented on README.md
> +2019년 10월, 학교에서 알고리즘 수업을 듣고 건물을 나오려는 순간, 게시판에 붙어있는 포스터를 발견한다. ``와! 재밌겠다!`. 그전까지 취업과 내 진로는 안갯속을 헤쳐나가듯 보이지 않고 까마득했다. 사실 지금도 명확하진 않다. 정말 뭐하고 먹고 살아야 하지? 많이 부족한 전공지식, 그저 그런 학점, 심지어 개발 경험은 제로에 가까웠다. 내가 해봤던
저만 그런건지 모르겠는게 pyqt 가 뭔지 모르겠어요;;;;

2020-04-03 01:18 UTC, lowoon commented on README.md
> +
링크로 가서 읽으면 지원서가 강조가 되있네요??

2020-04-03 01:18 UTC, lowoon commented on README.md
> +그때 오렌지의 머리가 얼마나 새하얀 눈밭 같았는지. 그런 실력으로 오프라인 코딩테스트를 보러 갔다. 큰 기대는 하지 않았다. 엉망진창 설계도를 갖고 돌아가도록 기능만 구현했다. 오렌지는 운이 좋은 사람이다. 그런 나사 빠진 실력을 갖추고도 오프라인 코딩테스트를 통과했다.
오렌지의 머리가 어땠는지 궁금하네요!

2020-04-03 01:33 UTC, YerinCho commented on README.md
> +2019년 10월, 학교에서 알고리즘 수업을 듣고 건물을 나오려는 순간, 게시판에 붙어있는 포스터를 발견한다. ``와! 재밌겠다!`. 그전까지 취업과 내 진로는 안갯속을 헤쳐나가듯 보이지 않고 까마득했다. 사실 지금도 명확하진 않다. 정말 뭐하고 먹고 살아야 하지? 많이 부족한 전공지식, 그저 그런 학점, 심지어 개발 경험은 제로에 가까웠다. 내가 해봤던
파이썬 gui 모듈 라이브러리 입니당.  . !

2020-04-03 01:34 UTC, yebink reviewed
안녕하세요 오렌지!
글 잘 읽었어요:)
몇 가지 코멘트 남겨뒀으니 확인 부탁드려요!

2020-04-03 01:34 UTC, YebinK commented on README.md
> +2019년 10월, 학교에서 알고리즘 수업을 듣고 건물을 나오려는 순간, 게시판에 붙어있는 포스터를 발견한다. ``와! 재밌겠다!`. 그전까지 취업과 내 진로는 안갯속을 헤쳐나가듯 보이지 않고 까마득했다. 사실 지금도 명확하진 않다. 정말 뭐하고 먹고 살아야 하지? 많이 부족한 전공지식, 그저 그런 학점, 심지어 개발 경험은 제로에 가까웠다. 내가 해봤던
저도 모르겠어요! 부연설명을 해주면 좋을 것 같네요!

2020-04-03 01:34 UTC, YebinK commented on README.md
> +두근두근, 드디어 숫자야구게임이 시작됐다. 첫 언어는 C, 수업의 과제만 해 왔기 때문에 주 언어도 C. 객체지향? 알지만 잘 몰랐다. MVC 디자인패턴? 들어 본 적도 없었다. 클래스를 다섯 개 이상 만들어서 구현해 본 적도 없었다. API를 사용할 줄도 몰랐고, 스트림을 써대는데 이게 무슨 말인지. 머리가 핑핑 돌았다. 자존심이 상했지만 다른 사람의
`첫 언어는 C` 이 부분이 오렌지의 첫 언어가 C 였다는건지, 숫자야구게임의 첫 언어가 C였다는건지 헷갈려요!
좀 더 명확히 해주면 좋을 것 같아요 :)

2020-04-03 01:34 UTC, YebinK commented on README.md
> +두근두근, 드디어 숫자야구게임이 시작됐다. 첫 언어는 C, 수업의 과제만 해 왔기 때문에 주 언어도 C. 객체지향? 알지만 잘 몰랐다. MVC 디자인패턴? 들어 본 적도 없었다. 클래스를 다섯 개 이상 만들어서 구현해 본 적도 없었다. API를 사용할 줄도 몰랐고, 스트림을 써대는데 이게 무슨 말인지. 머리가 핑핑 돌았다. 자존심이 상했지만 다른 사람의
`처음 하는 언어인 자바로 하는 프리코스까지`

하는 하는 이 중복되어 조금 어색하네요. 어순을 바꾸거나 다른 단어로 대체하면 좋을 것 같아요!

2020-04-03 01:34 UTC, YebinK commented on README.md
> +앞에서 말했다시피, 스트레스받는 것을 매우 싫어하는 사람이다. 이에 깊게 생각하려 하지 않는다. 항상 단순하게 생각하고 즉흥적으로 행동한다. 무언가를 하려고 하면 곧잘 따라 하고 이해도도 높지만, 스스로의 기준으로 봤을 때는 끈기와 열정이 부족한 사람이다. 여기서도 마찬가지다. 매일매일 남아서 공부하는 크루들, 이미 많은 것을 알고 온 열정적인 크루들 투
`따라 하고` -> `따라하고`
띄어쓰기 지켜주세요!

2020-04-03 01:34 UTC, YebinK commented on README.md
> +오렌지는 무슨 뜻이에요? 왜 오렌지예요? 지금도 종종 듣는다. 별 뜻 없다. 자칭(==타칭) 상큼이라서 오렌지일 뿐이다. 오렌지의 삶도 마찬가지다. 큰 의미를 두지 않고, 스트레스를 받지 말자는 마인드로 삶을 살아간다. 말재주도 없고 재미도 없지만, 오렌지의 이야기를 해 보려고 한다.
=이 아닌 ==을 사용하시다니..! 개발자스럽네요! 걱정 안 해도 되겠어요!

2020-04-03 06:03 UTC, YerinCho commented on README.md
> +두근두근, 드디어 숫자야구게임이 시작됐다. 첫 언어는 C, 수업의 과제만 해 왔기 때문에 주 언어도 C. 객체지향? 알지만 잘 몰랐다. MVC 디자인패턴? 들어 본 적도 없었다. 클래스를 다섯 개 이상 만들어서 구현해 본 적도 없었다. API를 사용할 줄도 몰랐고, 스트림을 써대는데 이게 무슨 말인지. 머리가 핑핑 돌았다. 자존심이 상했지만 다른 사람의
글을 줄인다고 문단을 날렸더니 연결이. . . :( 중간에 문단 하나 추가했어요 ~!

2020-04-03 06:09 UTC, YerinCho commented on README.md
> +
일부러 처음 썼다고 강조를 하려는 의도이긴 합니다!

2020-04-03 06:27 UTC, yebink approved these changes
피드백 반영 잘하셨어요!
이만 머지할게요! 💯

2020-04-03 07:58 UTC, KS-KIM reviewed
안녕하세요, 오렌지. 알트입니다 😊

다른 분들이 피드백 많이 남기셔서 간단한 코멘트만 남겼습니다. 확인 부탁드려요~

2020-04-03 07:58 UTC, KS-KIM commented on README.md
> + 그렇지만, 부족하다는 그런 이유로 이들의 열정을 모른 척 하고 살 수는 없었다. 오히려 뜨거운 분위기가 내 온몸을 감싸 돌았다. 크루들의 열정은 충분한 영향력이며, 누군가가 귀 바로 옆에서 계속 말하는 듯한 자극이다. 누군가의 모습이 나에게 멋져 보이고, 성장 촉진제가 된다면 나도 모르게 따라한다. 여기서 닉네임을 언급하긴 부끄럽지만, 많은 크루들이 나
```suggestion
 그렇지만, 부족하다는 그런 이유로 이들의 열정을 모른 척하고 살 수는 없었다. 오히려 뜨거운 분위기가 내 온몸을 감싸 돌았다. 크루들의 열정은 충분한 영향력이며, 누군가가 귀 바로 옆에서 계속 말하는 듯한 자극이다. 누군가의 모습이 나에게 멋져 보이고, 성장 촉진제가 된다면 나도 모르게 따라한다. 여기서 닉네임을 언급하긴 부끄럽지만, 많은 크루들이 나에게 그런 존재였다. 그들과 나를 비교하지는 않는다. 하지만 그들의 열정은 서서히 꺼져가는 내 열정을 다시 불태웠다.
```

2020-04-03 07:58 UTC, KS-KIM commented on README.md
> + 두근두근, 드디어 프리코스가 시작됐다. C로 첫 프로그래밍을 시작했고, 평소엔 수업의 과제만 해 왔기 때문에 주 언어도 C였다. 객체지향? 알지만 잘 몰랐다. MVC 디자인패턴? 들어 본 적도 없었다. 클래스를 다섯 개 이상 만들어서 구현해 본 적도 없었다. API를 사용할 줄도 몰랐고, 스트림을 써대는데 이게 무슨 말인지. 머리가 핑핑 돌았다. 자존심
시험기간에 프리코스까지 병행하느라 고생하셨어요 👍👍

2020-04-03 07:58 UTC, KS-KIM commented on README.md
> + 그 때 오렌지의 실력은 얼마나 새하얀 눈밭 같았는지. 부족한 점 밖에 보이지 않는다. 그런 실력으로 오프라인 코딩테스트를 보러 갔다. 큰 기대는 하지 않았다. 엉망진창 설계도를 갖고 돌아가도록 기능만 구현했다. 오렌지는 운이 좋은 사람이다. 그런 나사 빠진 실력을 갖추고도 오프라인 코딩테스트를 통과했다.
운도 실력이죠 😁

2020-04-03 08:00 UTC, YerinCho commented on README.md
> + 그 때 오렌지의 실력은 얼마나 새하얀 눈밭 같았는지. 부족한 점 밖에 보이지 않는다. 그런 실력으로 오프라인 코딩테스트를 보러 갔다. 큰 기대는 하지 않았다. 엉망진창 설계도를 갖고 돌아가도록 기능만 구현했다. 오렌지는 운이 좋은 사람이다. 그런 나사 빠진 실력을 갖추고도 오프라인 코딩테스트를 통과했다.
고마워요 ~~ ㅎㅎ :)

2020-04-03 08:03 UTC, KS-KIM approved these changes
고생하셨어요!!! 이만 머지하겠습니다😆

2020-04-03 11:38 UTC, chomily approved these changes
고생하셨어요~ 머지하겠습니다 :)

2020-04-06 08:39 UTC, pobiconan approved these changes
우테코 지원 과정, 프리코스, 레벨 1 과정에서의 감정의 흐름을 온전히 느낄 수 있어 좋네요. 💯 

아직 주변의 크루들에 비해 열정적이지 않을 수 있는데요.
무엇인가에 열정적이 되려면 일정 수준의 역량이 쌓였을 때 가능한 느낌이 들어요.
오렌지도 꾸준히 성장하면서 역량을 쌓고 있으니 조만간 다른 크루들과 어깨를 나란히 할 거라 생각해요.
어리고 철없는 오렌지의 정신적 성장의 원동력이 되는 우테코가 되기를 기대합니다.

2020-04-06 08:39 UTC, merged