[럿고] 레벨1 글쓰기 미션 제출합니다.
woowacourse/woowa-writing-2 pull request #51
Opened 2020-04-02 13:58 UTC by ksy90101

리뷰어 분들! 제가 너무 늦었네요 ㅠㅠ 
부족한 글 잘 읽어 주시고 피드백 남겨주시면 감사하겠습니다~

2020-04-02 14:18 UTC, toneyparky reviewed
럿고..! 글쓰기 미션 제출하느라 고생 많았어요.

럿고의 생각이 담긴 글 잘 읽고 피드백 남겨봤습니다.

럿고의 변화된 마음가짐이 돋보이네요.

응원합니다!!

조급함 없이 함께 나아가죠😊👍

2020-04-02 14:18 UTC, toneyparky commented on README.md
> +그러나 그 길을 점점 걷다 보니 점점 나와 맞지 않는 길이라고 생각하고, 다시 방황의 시간이 찾아왔다.
> 그러나 그 길을 걷다 보니 점점 나와 맞지 않는 길이라고 생각했고, 다시 방황의 시간이 찾아왔다.

`점점`을 한 번만 사용해도 충분하게 의미 전달이 되네요..!

강조의 목적으로 사용하신게 아니라면 한 번으로도 충분할 거 같아요!

2020-04-02 14:18 UTC, toneyparky commented on README.md
> +그래서 프로그래밍에 대해서 몇 일을 찾아보고, 계획을 세우기 시작했다.
> 그래서 프로그래밍에 대해서 며칠을 찾아보고, 계획을 세우기 시작했다.

저도 헷갈려서 찾아봤던 맞춤법이네요..!

수정하시면 바른 글을 쓰는 데에 도움이 될 듯해요😊

2020-04-02 14:18 UTC, toneyparky commented on README.md
> +그러나 웹사이트를 만들게 되면서 힘든 시간도 많았지만, 그 짜증나는 시간을 버틸수 있는 즐거운 시간들이 너무 많았다.
>비록 웹사이트를 만들면서 힘든 시간도 많았지만, 짜증 나는 시간을 버틸 수 있게 해준 즐거운 시간들이 너무 많았다.

이렇게 수정하면 명료하게 전달하고자하는 바를 전달 할 수 있겠네요🙂

확인해보시고 마음에 든다면 수정해보아요.

2020-04-02 14:18 UTC, toneyparky commented on README.md
> +2월, 우테코를 시작이 다가오기 시작했다. 기대 반 걱정 반의 마음을 가지고 시작을 했었다.
> 2월, 우테코의 시작이 다가오기 시작했다. 기대 반 걱정 반의 마음을 가지고 시작했었다.

약간의 수정으로 더 깔끔한 문장이 될 수 있겠네요..!

의도한 바가 잘 전달 되도록 수정해봤는데 확인부탁드려요😄

2020-04-02 14:18 UTC, toneyparky commented on README.md
> +과거에는 항상 나는 결과를 중요시 했다. 결과만 나오면 된다는 생각을 가지면서 프로그래밍 공부를 했고, 웹 프로젝트를 진행했었다.
> 과거의 나는 항상 결과를 중요시 했다. 결과만 나오면 된다는 생각으로 프로그래밍 공부를 했고, 웹 프로젝트를 진행했었다.

문장을 다듬어봤어요 😁

첫 문장은 어색하다고 느낀 부분을 수정해봤고 둘 째 문장에서는 조금 간결해지도록 수정해봤습니다.

제 의견일 뿐이니 럿고가 확인해보시 마음대로 수정여부를...!

2020-04-02 14:18 UTC, toneyparky commented on README.md
> +내가 부족한 것이 무엇인지 정리하고, 부족한 것을 채워 나가는 계획을 짜서 조급함을 가지지 않고 천천히 해 나갈 생각이다.
꾸준하게 기록해봐요..!

필요하다고 느낄 때 시도하면 원동력이 쉽게 꺼지지 않을거에요☺️

응원합니다!!

2020-04-02 14:22 UTC, ksy90101 commented on README.md
> +그러나 그 길을 점점 걷다 보니 점점 나와 맞지 않는 길이라고 생각하고, 다시 방황의 시간이 찾아왔다.
피드백 감사합니다~

2020-04-02 14:22 UTC, ksy90101 commented on README.md
> +그래서 프로그래밍에 대해서 몇 일을 찾아보고, 계획을 세우기 시작했다.
넵! 수정했어요~

2020-04-02 14:23 UTC, ksy90101 commented on README.md
> +그러나 웹사이트를 만들게 되면서 힘든 시간도 많았지만, 그 짜증나는 시간을 버틸수 있는 즐거운 시간들이 너무 많았다.
피드백 반영했습니다~ 감사합니다~

2020-04-02 14:23 UTC, ksy90101 commented on README.md
> +2월, 우테코를 시작이 다가오기 시작했다. 기대 반 걱정 반의 마음을 가지고 시작을 했었다.
반영했어요~ 감사합니다!

2020-04-02 14:24 UTC, ksy90101 commented on README.md
> +내가 부족한 것이 무엇인지 정리하고, 부족한 것을 채워 나가는 계획을 짜서 조급함을 가지지 않고 천천히 해 나갈 생각이다.
넵! 토니처럼 일기 쓰는 습관도 같이 가져야 할꺼 같아요~!

2020-04-02 14:44 UTC, Hamliet reviewed
안녕하세요! 라흐입니다. 글쓰기 미션으로 처음 인사드리네요 ㅎㅎ
과거와 현재 미래로 문단을 나누어 느낌점을 작성하신 것이 좋았습니다.
몇 가지 코멘트 남겼으니 확인 부탁드릴게요! ^^

2020-04-02 14:44 UTC, Hamliet commented on README.md
> +군대 제대 후 새로운 길을 찾아다니면서 새로운 길을 향해 달려 나갔다.
`군대 제대 후 새로운 길을 찾았고 새로운 길을 향해 달려 나갔다.` 가 조금더 자연스러울 것 같아요!

2020-04-02 14:44 UTC, Hamliet commented on README.md
> +고등학교 시절 컴퓨터과를 다니면서 컴퓨터 지식을 배워나갔지만, 성인이 되고 나서는 나만의 환상이 깨지게 되고, 컴퓨터에 대한 흥미를 잃게 됐다.
어떤 환상이었는지 궁금하네요 ㅎㅎ

2020-04-02 14:44 UTC, Hamliet commented on README.md
> +전혀 코드에 대한 생각을 하지 않았다. 결과물만 생각했다.
저도 마찬가지였죠 ㅎㅎ 동작만 하면 되지!라는 생각

2020-04-02 14:44 UTC, Hamliet commented on README.md
> +남은 기간동안 더 많은 크루들과 코치님들과 리뷰어분들과 더 많은 `잡답`을 나눠보고 싶다.
많은 잡담 기대할게요! ㅎㅎㅎ

2020-04-02 14:44 UTC, Hamliet commented on README.md
> +최근에 준 코치님과 면담을 하면서 다른 사람들의 말에 휘둘리게 되면서 조급합이 많이 생기게 되고 다른 사람들은 이미 알고 있는 지식이지만 나는 모르는 지식들을 공부하고 싶은 마음에 계획 조급해 지고
`지식들을 공부하고 싶은 마음에 계획 조급해 지고` 이 부분 문장이 어색 한 것 같아요! `계획`을 빼거나
`계획을 세웠지만 마음은 조금해지고` 로 바꿔보는건 어떨까요?

2020-04-02 14:45 UTC, sonypark reviewed
럿고 글 참 진솔하게 잘 쓰셨네요.
개발 공부한지 6개월 밖에 안 되셨다니.. 정말 대단하네요.
성장가능성이 무궁무진 하신것 같아 앞으로가 더 기대됩니다.
같이 열심히 성장해봐요! 화이팅!!

2020-04-02 14:45 UTC, sonypark commented on README.md
> +교육을 들으면서 팀 프로젝트를 진행하게 되었는데 내가 제안한 아이디어가 채택이 되어서 주도적으로 웹사이트를 만들게 되었다.
다음과 같이 수정하면 더 자연스러울 것 같아요!
```
채택이 되어서 -> 채택 되어서
```

2020-04-02 14:45 UTC, sonypark commented on README.md
> +최근에 준 코치님과 면담을 하면서 다른 사람들의 말에 휘둘리게 되면서 조급합이 많이 생기게 되고 다른 사람들은 이미 알고 있는 지식이지만 나는 모르는 지식들을 공부하고 싶은 마음에 계획 조급해 지고
오타가 보이네요 :)
```
조급합 -> 조급함
```

2020-04-02 14:45 UTC, sonypark commented on README.md
> +첫 수업을 들었을 때 프로그래밍 언어를 자바로 시작했고 웹 프로젝트를 경험했지만, 내가 생각한 프로그래밍의 대한 지식과는 아예 달랐다.
오타 수정 후 문장을 조금 다듬어 보는 건 어떨까요? :)
간단한 예시 추가했으니 참고부탁드려요!
```
내가 생각한 프로그래밍의 대한 지식과는 아예 달랐다.
-> 내가 생각한 프로그래밍에 대한 지식과는 아예 달랐다.
-> 내가 생각한 프로그래밍 지식과는 아예 달랐다.
```

2020-04-02 14:45 UTC, sonypark commented on README.md
> +하루하루 제대로 지내지 못하는 것 같다는 질문을 한 적이 있는데, 코치님의 답변은 리스트를 정리하고 우선순위를 정해놓고 계획을 짜는 것이 중요하다는 답변을 주셨다.
저도 럿고와 같이 번아웃 증상이 왔었어요(아직도 극복중)
알고 싶은 건 많고 공부해야할 건 산더미인데 현실은 미션 따라가기 급급했기 때문에.
럿고 글을 통해 저도 우선순위를 정해서 하나씩 차근차근 쌓아가야겠다고 다짐하게 되네요.
좋은 글 감사합니다

2020-04-02 14:46 UTC, ksy90101 commented on README.md
> +군대 제대 후 새로운 길을 찾아다니면서 새로운 길을 향해 달려 나갔다.
그렇네요! 감사합니다!

2020-04-02 14:47 UTC, ksy90101 commented on README.md
> +최근에 준 코치님과 면담을 하면서 다른 사람들의 말에 휘둘리게 되면서 조급합이 많이 생기게 되고 다른 사람들은 이미 알고 있는 지식이지만 나는 모르는 지식들을 공부하고 싶은 마음에 계획 조급해 지고
헉 오타가 있네요 ㅎㅎ 글쓰기도 조급했나 봅니다 ㅠㅠ 수정할께요!

2020-04-02 14:50 UTC, ksy90101 commented on README.md
> +고등학교 시절 컴퓨터과를 다니면서 컴퓨터 지식을 배워나갔지만, 성인이 되고 나서는 나만의 환상이 깨지게 되고, 컴퓨터에 대한 흥미를 잃게 됐다.
그에 관련된 내용을 조금 추가해봤습니다~

2020-04-02 14:52 UTC, ksy90101 commented on README.md
> +최근에 준 코치님과 면담을 하면서 다른 사람들의 말에 휘둘리게 되면서 조급합이 많이 생기게 되고 다른 사람들은 이미 알고 있는 지식이지만 나는 모르는 지식들을 공부하고 싶은 마음에 계획 조급해 지고
아직 조급함을 못버린거 같네요 ㅠㅠ 수정했습니다~

2020-04-02 14:52 UTC, ksy90101 commented on README.md
> +첫 수업을 들었을 때 프로그래밍 언어를 자바로 시작했고 웹 프로젝트를 경험했지만, 내가 생각한 프로그래밍의 대한 지식과는 아예 달랐다.
수정했습니다~

2020-04-02 19:33 UTC, c-yeonwoo requested changes
럿고 안녕하세요 ㅎㅎ
충분히 계획도 잘세우고 하시는 것 같던데 나름대로 고민이 있었군요.
저는 요새 좀 힘든데 번아웃 극복기 좀 참고해야겠습니다! :)

그리고 럿고의 진지한 마음을 좀 더 알 수 있게 된 글인 것 같아 좋았습니다 💯

2020-04-02 19:33 UTC, yeonnseok commented on README.md
> +군대 제대 후 새로운 길을 찾았고 새로운 길을 향해 달려 나갔다.
일부러 의도하신건지 모르겠지만 그게 아니라면 
`새로운`이 두 번 나오는 것보다 뒤에 나오는 새로운 길 대신 `그 길`이 더 자연스러울 것 같아요 
참고만해주세요 :)

2020-04-02 19:33 UTC, yeonnseok commented on README.md
> +계획을 세우던 중, `국비교육`이라는 제도를 알게 되었고, 교육에서 `자바`라는 언어를 배우기 시작했고, 웹 사이트를 제작하는 법을 배우게 되었다.
쉼표를 많이 쓰기보다, 문장을 분할한다면 더 가독성이 좋아질 것 같아요 👍

2020-04-02 19:33 UTC, yeonnseok commented on README.md
> +하루하루 제대로 지내지 못하는 것 같다는 질문을 한 적이 있는데, 코치님의 답변은 리스트를 정리하고 우선순위를 정해놓고 계획을 짜는 것이 중요하다는 답변을 주셨다.
저는 요새 번아웃인 것 같아요  ;( ㅠㅠ
다같이 힘내요 우리

2020-04-02 19:33 UTC, yeonnseok commented on README.md
> +내가 부족한 것이 무엇인지 정리하고, 부족한 것을 채워 나가는 계획을 짜서 조급함을 가지지 않고 천천히 해 나갈 생각이다.
럿고도 블로그의 세계로 들어오세요 :)

2020-04-02 19:33 UTC, yeonnseok commented on README.md
> +다른 사람들은 이미 많은 기본 지식들이 있는 것 같은데, 나는 처음 듣는 단어들이 너무 많았고,들어봤다고 해서 그 단어들을 설명할 수도 없는 상황이였다.
```suggestion
다른 사람들은 이미 많은 기본 지식이 있는 것 같았다. 그에 비해 나에겐 생소한 개념들이 많았고, 한 두번 들어봤다고 하더라도 그 개념들을 제대로 설명하는 것은 쉽지 않았다.
```
원래대로 
`개념` -> `단어`로 쓰셔도되고  띄어쓰기와 단문만 수정하고 내용은 참고만 하셔도 좋을 것 같네요~

2020-04-02 22:38 UTC, toneyparky approved these changes
럿고! 제가 제안한 부분에 대해 수정이 잘 되어서 approve할게요..!

럿고의 글을 읽으며 럿고에 대해 알게 되었네요😉

우리 모두 각자의 고민이 있지만 크루들이 함께기에 잘 이겨낼 수 있다고 생각해요~

한주 남은 레벨 1 잘 마무리하고 방학때 힐링해보죠☺️
 
다음에 식사나 반주 함께 하며 더 이야기해요🍻

글쓰기 미션 수고했습니다!

2020-04-03 02:45 UTC, c-yeonwoo approved these changes

2020-04-03 04:48 UTC, ksy90101 commented on README.md
> +계획을 세우던 중, `국비교육`이라는 제도를 알게 되었고, 교육에서 `자바`라는 언어를 배우기 시작했고, 웹 사이트를 제작하는 법을 배우게 되었다.
수정했습니다!

2020-04-03 04:48 UTC, ksy90101 commented on README.md
> +군대 제대 후 새로운 길을 찾았고 새로운 길을 향해 달려 나갔다.
수정했습니다!

2020-04-03 04:49 UTC, ksy90101 commented on README.md
> +다른 사람들은 이미 많은 기본 지식들이 있는 것 같은데, 나는 처음 듣는 단어들이 너무 많았고,들어봤다고 해서 그 단어들을 설명할 수도 없는 상황이였다.
꼼꼼히 지적해주셨네요! 감사합니다~

2020-04-03 04:53 UTC, sonypark approved these changes
럿고 글 수정된 것 확인했습니다.
문장이 많이 자연스러워진 것 같아요!
머지하겠습니다:)
남은 체스 미션도 화이팅!

2020-04-03 05:58 UTC, Hamliet approved these changes

2020-06-10 01:07 UTC, merged