[레벨1 - 기록] 무늬 미션 제출합니다.
woowacourse/woowa-writing-2 pull request #6
Opened 2020-03-28 06:43 UTC by JinJuMoon

안녕하세요, 무늬입니다. 😄 
우아한테크코스 글쓰기 과정의 첫 미션이네요.
잘부탁드립니다!

2020-03-30 13:03 UTC, dks301 reviewed
안녕하세요 무늬 :)
객체 지향적인 글 잘봤습니다 👍 
무늬의 생각이 잘 들어간 글인 것 같아요. 
몇가지 코멘트 확인해주세요.

2020-03-30 13:03 UTC, dks301 commented on README.md
> +OOP에 따르면 객체는 어떤 책임을 질 것 인지를 명확히 하고, 그 객체의 책임이 아니면 분리해야 한다. 나는 위에서 말했던 일련의 목표들을 이루어야 할 책임이 나에게 있다고 생각했다. 하지만 돌이켜보면 나에게 과분하거나 타인에게 강요 받은 책임도 많다. 현재 이것 저것 덜어내고 남은 나의 진짜 책임은 우아한테크코스를 무사히 마치는 것이다. 베스트셀러인
OOP 설계 원칙을 말하는 건가요?
그리고 이 문단도 두 문단으로 나누는 건 어떨까요??

2020-03-30 13:03 UTC, dks301 commented on README.md
> +우아한테크코스에 참여하면서 자의반 타의반으로 내가 세웠던 목표들은 줄줄이 나가 떨어졌다. 당장 미션만 하기도 바쁜데 다른 걸 신경 쓸 겨를이 없었다. 심지어 방청소도 일주일 넘게 못했다.(어제는 했당) 그런데, 신기하게도 나는 되려 요즘 아주 살 만하다. 나에게 가장 중요한 것이 뭔지 고민하고, 결정하고, 그것만 죽어라 팠다. 그 과정에서 진짜 좋은 건지
`했당`???????????????
의도 한 것 같은데 비문을 써도 되는지 모르겠네요

2020-04-01 13:57 UTC, lxxjn0 requested changes
무늬, 글 재밌게 읽었어요!!

우리가 레벨 1에서 배운 내용을 실제 무늬의 삶에 접목하여 이야기를 풀어나간 것이 정말 재미있었어요.
그리고 내용이 너무 진솔하고 공감이 가서 더 와닿았던 것 같네요!!

띄어쓰기 부분을 많이 체크해둬서 생각보다 갯수가 많아졌네요 ㅜㅡㅜ
확인하시고 수정 부탁드릴게요!!

2020-04-01 13:57 UTC, lxxjn0 commented on README.md
> +우아한테크코스를 시작하고 한달이 조금 넘었다. 레벨1 과정의 대부분은 객체지향 프로그래밍을 학습하는 것이다. 덕분에 더이상 객체, 책임, 리팩토링이라는 단어들이 낯설지는 않다. 이와 더불어 나에게 또 다른 변화가 생겼다. 바로 일상생활과 사고방식이 객체지향적으로 바뀌고 있다는 것이다.
```suggestion
우아한테크코스를 시작하고 한 달이 조금 넘었다. 레벨1 과정의 대부분은 객체지향 프로그래밍을 학습하는 것이다. 덕분에 더 이상 내겐 객체, 책임, 리팩토링이라는 단어들이 낯설지 않다. 이와 더불어 나에게 또 다른 변화가 생겼다. 바로 일상생활과 사고방식이 객체지향적으로 바뀌고 있다는 것이다.
```

띄어쓰기 부분 체크해 두었습니다.
그리고 `나에게 또 다른 변화`를 말하기 이전에 나에 대한 변화를 명시해 주는 것도 좋을 것 같아요!!
앞에 등장한 문장이 변화된 점이란 것을 알 순 있지만 '나에겐 ~~~한 변화가 있었다. 이와 더불어 나에겐 또 다른 변화가 생겼다.' 처럼 쓰는 것도 괜찮을 것 같아요.

하지만 `나에겐`이라는 단어가 반복되어 나오는 느낌이라 조금 어색하기도 하네요 ㅎㅎ..
무늬가 그냥 참고해보면 좋지 않을까 싶어서 남겨둬요 :)

2020-04-01 13:57 UTC, lxxjn0 commented on README.md
> +### 의존성 제거
무늬의 일상과 모습을 우리가 지금 배우고 있는 과정들에 접목한 점이 정말 좋았어요!!
이에 따른 내용들도 너무 과하지 않고 적절하고 공감이 되어서 보기 좋았어요 👍

2020-04-01 13:57 UTC, lxxjn0 commented on README.md
> +과거 나의 행복은 너무 많은 것들에 결합되어 있었다. 금전적 여유, 만족스러운 사회적 평판, 항상 높게 유지되는 생산성, 꾸준한 자기관리 등. 끝도 없는 목표들 중 하나라도 부족하면 행복하지 않았다. 그렇게 행복은 끝없는 미래로 미룬 채, 목표들을 완벽히 해내지 못하는 내 자신을 채찍질했다.
```suggestion
과거 나의 행복은 너무 많은 것들에 결합되어 있었다. 금전적 여유, 만족스러운 사회적 평판, 항상 높게 유지되는 생산성, 꾸준한 자기관리 등. 끝없이 많은 목표들 중 하나라도 부족하면 행복하지 않았다. 그렇게 행복은 끝없는 미래로 미룬 채, 목표들을 완벽히 해내지 못하는 내 자신을 채찍질했다.
```

목표의 양이 많은 느낌이라 `수없이 많은`이라고 써보는 건 어떨까 싶어서 코멘트 남겨요!!

뒤에 `끝없는 미래`가 나와서 `끝없이 많은`에서 `수없이 많은`으로 고쳐봤어요!!

2020-04-01 13:57 UTC, lxxjn0 commented on README.md
> +우아한테크코스에 참여하면서 자의반 타의반으로 내가 세웠던 목표들은 줄줄이 나가 떨어졌다. 당장 미션만 하기도 바쁜데 다른 걸 신경 쓸 겨를이 없었다. 심지어 방청소도 일주일 넘게 못했다.(어제는 했당) 그런데, 신기하게도 나는 되려 요즘 아주 살 만하다. 나에게 가장 중요한 것이 뭔지 고민하고, 결정하고, 그것만 죽어라 팠다. 그 과정에서 진짜 좋은 건지
```suggestion
우아한테크코스에 참여하면서 자의 반 타의 반으로 내가 세웠던 목표들은 줄줄이 나가 떨어졌다. 당장 미션만 하기도 바쁜데 다른 걸 신경 쓸 겨를이 없었다. 심지어 방청소도 일주일 넘게 못했다. 그런데, 신기하게도 나는 되려 요즘 아주 살 만하다. 나에게 가장 중요한 것이 뭔지 고민하고, 결정하고, 그것만 죽어라 팠다. 그 과정에서 진짜 좋은 건지도 모른 채 일단 줄줄이 매달아 놓았던 의존성들이 모두 제거되고, 나에게 가치있는 것들에만 집중하면서 응집도는 높아졌다.
```

띄어쓰기 수정해봤어요. 그리고 시카가 언급했던 부분은 저도 같은 의견이라 추가로 남겨두지 않았어요.

2020-04-01 13:57 UTC, lxxjn0 commented on README.md
> +예전에는 투두리스트로 가득했던 나의 인생이 거대한 숙제처럼 느껴지기도 했다. '언제쯤 이 많은 숙제들을 다하고 웃을 수 있을까' 생각하다보면 주름이 자글자글한 할머니가 된 나의 모습이 떠오르곤 했다. 하지만 지금은 아주 작은 퀘스트들을 풀어나가는 느낌이다. 퀘스트를 마치고 주어진 보상은 내 생각보다 훨씬 달콤했다.
```suggestion
예전에는 투두리스트로 가득했던 나의 인생이 거대한 숙제처럼 느껴지기도 했다. '언제쯤 이 많은 숙제들을 다하고 웃을 수 있을까' 생각하다 보면 주름이 자글자글한 할머니가 된 나의 모습이 떠오르곤 했다. 그러나 지금은 아주 작은 퀘스트들을 풀어나가는 느낌이다. 퀘스트를 마치고 주어진 보상은 내 생각보다 훨씬 달콤했다.
```

띄어쓰기 수정해뒀어요!!
`하지만`을 `그러나`로 수정하는 건 어떨까요? 큰 차이는 없어 보이지만 전 읽히기에 `그러나`가 더 자연스러워 보여서 추천해보았어요 :)

https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=25509
해당 링크를 한 번 참고해봐도 좋을 것 같아요!!

2020-04-01 13:57 UTC, lxxjn0 commented on README.md
> +OOP에 따르면 객체는 어떤 책임을 질 것 인지를 명확히 하고, 그 객체의 책임이 아니면 분리해야 한다. 나는 위에서 말했던 일련의 목표들을 이루어야 할 책임이 나에게 있다고 생각했다. 하지만 돌이켜보면 나에게 과분하거나 타인에게 강요 받은 책임도 많다. 현재 이것 저것 덜어내고 남은 나의 진짜 책임은 우아한테크코스를 무사히 마치는 것이다. 베스트셀러인
```suggestion
OOP에 따르면 객체는 어떤 책임을 질 것 인지를 명확히 하고, 그 객체의 책임이 아니면 분리해야 한다. 나는 위에서 말했던 일련의 목표들을 이루어야 할 책임이 나에게 있다고 생각했다. 하지만 돌이켜보면 나에게 과분하거나 타인에게 강요받은 책임도 많다. 현재 이것저것 덜어내고 남은 나의 진짜 책임은 우아한테크코스를 무사히 마치는 것이다. 

베스트셀러인 '미움 받을 용기'에서도 자신의 과제와 타인의 과제를 분리하라고 한다. 그리고 과제의 주인은 그 선택이 가져온 결과를 최종적으로 받아들이는 사람이라고 말한다. 우아한테크코스를 무사히 마친 결과를 최종적으로 받아들이는 사람은 명백히 '나'다. 주어진 책임을 잘 수행하는 객체가 되어야지.
```

띄어쓰기 부분 체크해뒀어요!!

문단을 나누는 것은 시카와 동일한 의견이에요 :)
그리고 마지막 문장에서 `나`를 강조해 보는 것도 좋을 것 같아요.

2020-04-01 13:57 UTC, lxxjn0 commented on README.md
> + 더 놀라운 것은 막상 무수히 많은 투두리스트를 삭제해도, 나에게 아무 일도 일어나지 않는다는 것이다. 이전에는 잠시라도 쉬어 가면 영원히 뒤쳐질 것 같아 두려웠다. 하지만 투두리스트가 1개일 때와 10개일 때, 30개일 때의 내 일상은 그리 다르지 않았다. 어쩌면 그동안 나는 실체가 없는 경쟁자들을 따라잡기 위해 그렇게도 부단히 노력한 건 아닐까. 허구
```suggestion
객체의 불필요한 의존성이 제거되고 꼭 필요한 책임만 남으면, 아주 자연스럽게 객체는 자율성을 갖게 된다. 그래서 나도 아주 자유로워졌다. 쓸데없는 목표들을 덜어내고 나니, 나에게는 생각보다 많은 시간이 있었다.

 그런데, 더 놀라운 것은 막상 무수히 많은 투두리스트를 삭제해도, 나에게 아무 일도 일어나지 않는다는 것이다. 이전에는 잠시라도 쉬어 가면 영원히 뒤쳐질 것 같아 두려웠다. 하지만 투두리스트가 1개일 때와 10개일 때, 30개일 때의 내 일상은 그리 다르지 않았다. 어쩌면 나는 그동안 실체가 없는 경쟁자들을 따라잡기 위해 그렇게도 부단히 노력한 건 아닐까. 허구의 경쟁에 소비하던 시간들이 이제는 오롯이 나를 위한 시간이 되었다.
```

비슷한 내용이지만 포커싱 되는 주제가 변경되는 느낌이라 `그런데`를 추가하는 것도 괜찮아 보이네요!!!

`어쩌면 그동안 나는`을 `어쩌면 나는 그동안`으로 한번 바꿔봤는데, 이 부분은 무늬의 마음에 드는 방식으로 사용하시면 될 것 같아요 :)

2020-04-01 13:57 UTC, lxxjn0 commented on README.md
> +우아한테크코스를 한 뒤 나에게 생긴 변화들을 글로 풀어내다 보니, 새삼 이 과정에 참여하게 된 것이 감사하다. 나는 이 과정을 통해서 나만의 작은 행복을 찾아가고 있다. 그리고 나의 행복이 내 소중한 사람들에게도 조금씩 전해지고 있다. 따뜻한 일상과 소소한 행복을 찾을 수 있도록 엄청난 양의 미션을 매주 선사해주는 우아한테크코스에게 감사드린다. 앞으로도
```suggestion
우아한테크코스를 한 뒤 나에게 생긴 변화들을 글로 풀어내다 보니, 새삼 이 과정에 참여하게 된 것이 감사하다. 나는 이 과정을 통해서 나만의 작은 행복을 찾아가고 있다. 그리고 나의 행복이 내 소중한 사람들에게도 조금씩 전해지고 있다. 따뜻한 일상과 소소한 행복을 찾을 수 있도록 엄청난 양의 미션을 매주 선사해 주는 우아한테크코스에게 감사드린다. 앞으로도 지금처럼 군더더기 없이 작은, 그리고 행복한 객체로 살아가야지.
```

띄어쓰기 수정부탁드릴게요!!

2020-04-02 08:26 UTC, JinJuMoon commented on README.md
> +OOP에 따르면 객체는 어떤 책임을 질 것 인지를 명확히 하고, 그 객체의 책임이 아니면 분리해야 한다. 나는 위에서 말했던 일련의 목표들을 이루어야 할 책임이 나에게 있다고 생각했다. 하지만 돌이켜보면 나에게 과분하거나 타인에게 강요 받은 책임도 많다. 현재 이것 저것 덜어내고 남은 나의 진짜 책임은 우아한테크코스를 무사히 마치는 것이다. 베스트셀러인
네, 설계원칙이라고 명시하지 않아도 유추가 가능한 부분이라 간단하게 OOP로 표현했습니다. 문단은 문장의 내용이 계속 이어지는 부분이라 일부러 나누지 않았습니다. 혹시 가독성때문에 문단을 나누라고 하신걸까요? 😄

2020-04-02 08:28 UTC, JinJuMoon commented on README.md
> +우아한테크코스에 참여하면서 자의반 타의반으로 내가 세웠던 목표들은 줄줄이 나가 떨어졌다. 당장 미션만 하기도 바쁜데 다른 걸 신경 쓸 겨를이 없었다. 심지어 방청소도 일주일 넘게 못했다.(어제는 했당) 그런데, 신기하게도 나는 되려 요즘 아주 살 만하다. 나에게 가장 중요한 것이 뭔지 고민하고, 결정하고, 그것만 죽어라 팠다. 그 과정에서 진짜 좋은 건지
친근한 느낌을 주고 싶어서 사용했는데, 맥락에 맞지 않는 부분이라 삭제했습니다. 😄

2020-04-02 08:30 UTC, JinJuMoon commented on README.md
> +### 의존성 제거
감사합니다 😄

2020-04-02 08:32 UTC, JinJuMoon commented on README.md
> +우아한테크코스를 시작하고 한달이 조금 넘었다. 레벨1 과정의 대부분은 객체지향 프로그래밍을 학습하는 것이다. 덕분에 더이상 객체, 책임, 리팩토링이라는 단어들이 낯설지는 않다. 이와 더불어 나에게 또 다른 변화가 생겼다. 바로 일상생활과 사고방식이 객체지향적으로 바뀌고 있다는 것이다.
띄어쓰기 체크해주신 부분 반영했습니다. 개인적으로 단어를 반복하는 것을 싫어해서 '변화'라는 직접적인 단어를 사용하지않고 내용으로 유추할 수 있도록 했습니다. 제안해주셔서 감사합니다! 😄

2020-04-02 08:35 UTC, JinJuMoon commented on README.md
> +과거 나의 행복은 너무 많은 것들에 결합되어 있었다. 금전적 여유, 만족스러운 사회적 평판, 항상 높게 유지되는 생산성, 꾸준한 자기관리 등. 끝도 없는 목표들 중 하나라도 부족하면 행복하지 않았다. 그렇게 행복은 끝없는 미래로 미룬 채, 목표들을 완벽히 해내지 못하는 내 자신을 채찍질했다.
'수없이 많은'이라는 표현이 훨씬 좋은 것 같네요! 수정했습니다 😄

2020-04-02 08:41 UTC, JinJuMoon commented on README.md
> +예전에는 투두리스트로 가득했던 나의 인생이 거대한 숙제처럼 느껴지기도 했다. '언제쯤 이 많은 숙제들을 다하고 웃을 수 있을까' 생각하다보면 주름이 자글자글한 할머니가 된 나의 모습이 떠오르곤 했다. 하지만 지금은 아주 작은 퀘스트들을 풀어나가는 느낌이다. 퀘스트를 마치고 주어진 보상은 내 생각보다 훨씬 달콤했다.
오, 굉장히 유용한 팁이네요! 수정했습니다 👍

2020-04-02 08:42 UTC, JinJuMoon commented on README.md
> +우아한테크코스에 참여하면서 자의반 타의반으로 내가 세웠던 목표들은 줄줄이 나가 떨어졌다. 당장 미션만 하기도 바쁜데 다른 걸 신경 쓸 겨를이 없었다. 심지어 방청소도 일주일 넘게 못했다.(어제는 했당) 그런데, 신기하게도 나는 되려 요즘 아주 살 만하다. 나에게 가장 중요한 것이 뭔지 고민하고, 결정하고, 그것만 죽어라 팠다. 그 과정에서 진짜 좋은 건지
수정했어요 😄

2020-04-02 08:42 UTC, JinJuMoon commented on README.md
> +OOP에 따르면 객체는 어떤 책임을 질 것 인지를 명확히 하고, 그 객체의 책임이 아니면 분리해야 한다. 나는 위에서 말했던 일련의 목표들을 이루어야 할 책임이 나에게 있다고 생각했다. 하지만 돌이켜보면 나에게 과분하거나 타인에게 강요 받은 책임도 많다. 현재 이것 저것 덜어내고 남은 나의 진짜 책임은 우아한테크코스를 무사히 마치는 것이다. 베스트셀러인
문단을 나누어서 읽으니 훨씬 보기 좋네요. 감사합니다 😄

2020-04-02 08:44 UTC, JinJuMoon commented on README.md
> + 더 놀라운 것은 막상 무수히 많은 투두리스트를 삭제해도, 나에게 아무 일도 일어나지 않는다는 것이다. 이전에는 잠시라도 쉬어 가면 영원히 뒤쳐질 것 같아 두려웠다. 하지만 투두리스트가 1개일 때와 10개일 때, 30개일 때의 내 일상은 그리 다르지 않았다. 어쩌면 그동안 나는 실체가 없는 경쟁자들을 따라잡기 위해 그렇게도 부단히 노력한 건 아닐까. 허구
글의 흐름이 훨씬 매끄럽네요 👍 👍👍

2020-04-02 11:45 UTC, LTTTTTE approved these changes
안녕하세요 오구입니다.
투두리스트들을 모두 떨쳐낼수있는 용기 매우 멋있습니다.
자신을 객체로 비유해서 한달 생활기를 작성하셔서 재미있게 읽을수 있었습니다.
남은 우아한테크코스 생활동안에도 불필요한 의존성 없는 행복한 객체로 같이 살아봐요!

글에서 어색한 점을 찾을수 없어 Approve합니다.

2020-04-02 11:45 UTC, LTTTTTE commented on README.md
> +그런데, 더 놀라운 것은 막상 무수히 많은 투두리스트를 삭제해도, 나에게 아무 일도 일어나지 않는다는 것이다. 이전에는 잠시라도 쉬어 가면 영원히 뒤쳐질 것 같아 두려웠다. 하지만 투두리스트가 1개일 때와 10개일 때, 30개일 때의 내 일상은 그리 다르지 않았다. 어쩌면 나는 그동안 실체가 없는 경쟁자들을 따라잡기 위해 그렇게도 부단히 노력한 건 아닐까
멋있습니다! 저도 이런 깨달음을 얻고싶네요...

2020-04-02 11:45 UTC, LTTTTTE commented on README.md
> +### 책임과 분리
소제목이 인상적이네요

2020-04-02 15:22 UTC, mintjordy approved these changes
안녕하세요 무늬 :) 
객체에 비유한 생활기 재밌게 잘 읽었어요.
온전히 우테코과정에 몰입해 행복하게 성장하는 무늬의 모습이 잘 드러났던거 같아요.
별도로 피드백 드릴 내용이 없는것 같아요. 
저도 Approve 하겠습니다 👍

2020-04-02 15:22 UTC, mintjordy commented on README.md
> +우아한테크코스를 한 뒤 나에게 생긴 변화들을 글로 풀어내다 보니, 새삼 이 과정에 참여하게 된 것이 감사하다. 나는 이 과정을 통해서 나만의 작은 행복을 찾아가고 있다. 그리고 나의 행복이 내 소중한 사람들에게도 조금씩 전해지고 있다. 따뜻한 일상과 소소한 행복을 찾을 수 있도록 엄청난 양의 미션을 매주 선사해 주는 우아한테크코스에게 감사드린다. 앞으로도
지금 행복한 무늬의 모습이 진솔하게 드러나는 문장들이네요.  👏

2020-04-02 15:22 UTC, taejinseok commented on README.md
> +베스트셀러인 '미움 받을 용기'에서도 자신의 과제와 타인의 과제를 분리 하라고 한다. 그리고 과제의 주인은 그 선택이 가져온 결과를 최종적으로 받아들이는 사람이라고 말한다. 우아한테크코스를 무사히 마친 결과를 최종적으로 받아들이는 사람은 명백히 나다. 주어진 책임을 잘 수행하는 객체가 되어야지.
'우아한테크코스를 무사히 마친 결과를 최종적으로 받아들이는 사람은 명백히 나다.'   
 정말 공감되는 문장이네요!

2020-04-03 02:11 UTC, lxxjn0 approved these changes
무늬, 수정한 부분 확인했습니다!!!

기존에 글이 이미 너무 잘 써진 글이라 더 확인할 내용이 없었네요.
저도 여기와서 각자의 다른 사연을 가진 여러 사람들을 마주하는 것 같습니다. 그 중에서도 기존의 생활을, 습관을, 관성을 깨고 여기에 도전을 하러 오신 분들이 정말 대단해 보이더라구요!!!

무늬도 그 중 한 명이라고 생각이 드네요!!
남은 8개월 더 멋진 객체가 되었으면 합니다 👍 
응원할게요 :) Approve 하겠습니다!!

2020-04-03 02:37 UTC, dks301 approved these changes
안녕하세요 무늬 :)
시카입니다.

다시 한 번 읽어보았는데, 다른 분들이 리뷰를 잘해주셔서 그런지 글이 한결 깔끔하고 좋아졌네요! 💯 
두 달 동안 같이 배웠던 것과 무늬의 생각, 두 가지를 한 번에 알 수 있어서 좋았어요.

앞으로 남은 8개월 동안 경쟁 보다는 같이 성장해서  우테코 크루 객체의 책임을 질 수 있도록 해요 😄 
Approve하도록 하겠습니다.

2020-04-03 02:37 UTC, dks301 commented on README.md
> +OOP에 따르면 객체는 어떤 책임을 질 것 인지를 명확히 하고, 그 객체의 책임이 아니면 분리해야 한다. 나는 위에서 말했던 일련의 목표들을 이루어야 할 책임이 나에게 있다고 생각했다. 하지만 돌이켜보면 나에게 과분하거나 타인에게 강요 받은 책임도 많다. 현재 이것 저것 덜어내고 남은 나의 진짜 책임은 우아한테크코스를 무사히 마치는 것이다. 베스트셀러인
처음 글을 읽을때는 OOP와 OOP설계 원칙은 다르다고 생각했는데, 설명을 들으니 OOP도 괜찮은 것 같아요 👍

2020-06-10 01:16 UTC, merged