[레벨1 - 기록] 히로 글쓰기 1단계 제출합니다.
woowacourse/woowa-writing-2 pull request #7
Opened 2020-03-28 11:55 UTC by hotheadfactory

잘 부탁드립니다 :)

2020-03-30 03:48 UTC, include42 reviewed
안녕하세요 히로, 카프카입니다.

좋은 글 잘 읽었습니다.
히로가 가진 고민에 공감할 수 있었고,
우아한테크코스에서의 생활 이야기도 공감하며 읽었어요.

좋은 글이지만, 약간씩 어색하게 읽히는 곳이 있어 코멘트를 남겼습니다.
수정사항보다는 하나의 제안이나 피드백으로 생각해 주시고,
필요하다고 생각되는 부분을 정해 수정해 주세요.

2020-03-30 03:48 UTC, include42 commented on level1.md
> +라는 메일을 받았을 때 만감이 교차했다. 우선 관심있고 공부해 왔던 분야인 웹 백엔드에 대해서 전문적이고 심층적인 교육을 받을 수 있게 되어서 기뻤다.
`관심있고 공부해 왔던 분야인 웹 백엔드` 라는 부분이 잘 읽히지 않습니다. `관심있게 공부해 왔던` 으로 수정해도 좋을 것 같아요. 

그리고 `우선`이라는 말이 정확히 무엇을 수식하는지 보이지 않는데, `우선 ~~~ 되어서 기뻤다`를 `우선 ~~~된 것이 기뻤다` 로 문장을 수정하면 보다 정확한 의미를 전달할 수 있겠습니다.

2020-03-30 03:48 UTC, include42 commented on level1.md
> +한편으론 걱정이 되기도 했다. 전국의 우수한 인재들이 모인 곳에서 과연 살아남을 수 있을까? 학교에선 코드를 평가받아볼 기회가 별로 없었기에 내 위치가 어디인지도 잘 몰랐고, 성장을 위해 무엇부터 어떻게 해야 할지도 막연하기만 했다. 그렇게 학교를 휴학하고 우아한테크코스에 참여하기 위해 서울로 올라왔다.
`그렇게 학교를 휴학하고 우아한테크코스에 참여하기 위해 서울로 올라왔다`
직전까지의 내용이 정말 좋은데, 마지막 문장이 급작스럽다는 느낌을 받았습니다.

예를 들어, 
`~~막연하기만 했다. 이런 다양한 고민을 품고서, 나는 학교를 휴학하고 우아한테크코스에 참여하기 위해 서울로 올라왔다`
와 같은 식으로  앞선 내용을 정리해주면 어떨까요?
제 예시가 히로가 의도한 바와 정확히 맞을지는 모르겠지만, 마지막 문장에 대한 고민은 필요하다고 생각합니다.

2020-03-30 03:48 UTC, include42 commented on level1.md
> +우테코에 와서 처음 받은 미션은 '페어 프로그래밍'으로 진행하는 문자열 계산기와 6명 팀으로 진행하는 연극이었다. 페어 프로그래밍은 두 명이서 1대의 컴퓨터로 돌아가면서 코드를 짜는 것인데, 처음이다 보니 생각보다 손발이 잘 맞지는 않았고 의견 충돌도 있었지만 짝이 실력이 좋아서 많이 배워갈 수 있었다. 연극은 자바의 exception을 주제로 한 다섯
`문자열 계산기` -> `문자열 계산기 만들기` 가 더 정확한 의미 전달이라고 생각합니다.

`두 명이서` -> `두 명이`  이건 약간 비문이라는 느낌을 받아서...다만 친숙한 느낌을 의도했다면 유지해도 된다고 생각합니다.

`처음이다 보니 생각보다 손발이 잘 맞지는 않았고 의견 충돌도 있었지만 짝이 실력이 좋아서 많이 배워갈 수 있었다.`
 - `맞지는 않았고` -> `맞지 않았고` 가 더 깔끔하다고 생각합니다.(문장이 길어서 저런 뉘앙스들이 중첩되는 감이 있습니다.)
 - `짝이 실력이 좋아서` -> `짝의 실력이 좋아서`, 혹은 `팀원의 실력이 좋아서` `페어의 실력이 좋아서` 로 바꾸면 어떨까요?

2020-03-30 03:48 UTC, include42 commented on level1.md
> +다행히 우아한테크코스는 생각했던 것처럼 약육강식의 세계는 아니었다. 교육과정에 있어서 점수도, 등수도 없으며 경쟁보단 협력을 통해 같이 성장하는 곳이었다. 미션마다 새로운 짝을 만나며 페어 프로그래밍을 통해 배워가는 것도 많았고, Github를 통해 다른 크루들의 코드를 보거나 크루들끼리 자발적으로 모여 코드 리뷰를 하는 시간도 가져봤다. 코딩이 그 어느
`미션마다 새로운 짝을 만나며 페어 프로그래밍을 통해 배워가는 것도 많았고`
두 문장(미션마다 새로운 짝을 만나며 / 페어 프로그래밍을 통해 배워가는 것도 많았고)이 합쳐진 것인가요?
만약 의미를 하나로 전달하고 싶다면
`미션마다 만난 새로운 짝과 페어 프로그래밍을 하며 배워가는 것도 많았고`
라고 써도 무관하리라 생각합니다.

2020-03-30 03:48 UTC, include42 commented on level1.md
> +즐거움도 잠시, 우리나라를 강타한 코로나19 전염병으로 인해 우아한형제들이 재택근무 체제로 전환하면서 우테코도 2주간의 재택 학습 및 휴식을 갖게 되었다. 학습에 대한 열정으로 불타는 상태에서 찾아온 휴식기가 아쉬웠지만 책을 잔뜩 빌려가서 나름 할 수 있는 것을 집에서 해보았다. 이 또한 지나가리라 생각하면서.
`학습에 대한 열정으로 불타는 상태에서 찾아온 휴식기가 아쉬웠지만`
개인적인 의견으로, 이 문장이 복잡해서 잘 안 읽혔어요.

`학습에 대한 열정이 불타고 있던 만큼, 갑작스레 찾아온 휴식기가 아쉬웠지만`
으로 바꿔보면 어떨까요? 이 부분은 히로가 가진 의도에 따라 선택하면 되겠습니다.

2020-03-30 03:48 UTC, include42 commented on level1.md
> +본격적으로 다른 데 쳐다보기보다 어제의 나와 경쟁하기로 했다. 일단 <자바의 정석> 부터 완독하고, MVC 패턴, enum, 람다, 함수형 인터페이스 등 애매하게 알고 있거나 잘못 알고 있던 개념들에 대해 이론을 확실히 찾아보고, 이미 미션이 끝난 코드들도 리팩토링하거나 처음부터 다시 짜 보면서 감을 잡기 시작했다. 가장 큰 약점 중 하나라고 생각한 용어
`본격적으로 다른 데 쳐다보기보다 어제의 나와 경쟁하기로 했다`
의미가 정확히 전달되지 않는다고 생각합니다.
`본격적으로`라는 말의 의미를 다시 고려해 주시고,
`다른 데 쳐다보기보다`를 `남과 비교하기보다` 로 수정하면 좋겠습니다.

2020-03-30 03:48 UTC, include42 commented on level1.md
> +HTML 미션을 진행하면서 다른 크루들에게 칭찬을 들었다. 자바로 들은 칭찬은 아니었지만 칭찬으로 큰 힘을 얻은 것 같아 좋았고, 자만하기보단 앞으로 더욱 나아가기 위한 추진력으로 삼기로 했다.
`자바로 들은 칭찬은 아니었지만 칭찬으로 큰 힘을 얻은 것 같아 좋았고`
`칭찬으로 큰 힘을 얻은 것 같아`는 `칭찬으로 힘을 얻어` 혹은 `칭찬으로 자신감을 얻어` 등으로 변경이 가능하다고 생각합니다.
칭찬을 듣고 힘을 얻지 않았으리라는 가정은 이상하잖아요, 좀 더 확신이 있는 게 좋다고 생각해요.

2020-03-31 00:44 UTC, ordinCode commented on level1.md
> +우테코에 와서 처음 받은 미션은 '페어 프로그래밍'으로 진행하는 문자열 계산기와 6명 팀으로 진행하는 연극이었다. 페어 프로그래밍은 두 명이서 1대의 컴퓨터로 돌아가면서 코드를 짜는 것인데, 처음이다 보니 생각보다 손발이 잘 맞지는 않았고 의견 충돌도 있었지만 짝이 실력이 좋아서 많이 배워갈 수 있었다. 연극은 자바의 exception을 주제로 한 다섯
~~~인데 ~~했다. 라는 구조가 반복되는데 조금 수정하여 변화를 주면 어떨까요?

2020-03-31 03:40 UTC, include42 approved these changes
안녕하세요 히로, 카프카입니다.
부족한 피드백 적극적으로 반영해줘서 고맙습니다.
수정된 내용을 확인했고, 잘 쓴 글이라 더 피드백 할 내용을 찾기 어려워
여기에서 리뷰를 마무리하려고 합니다.

남과 비교하면서 생기는, 긴장과 자격지심에 대해 써 준 내용이 좋았습니다.
저도 아직 극복해나가는 중인지라, 공감하고 또한 귀담아들을 수 밖에요.
그 과정에서 자신감을 얻고 마음을 다잡는 내용은 정말 인상깊었습니다.

우리는 길게 가야 하니까요, 그만큼 더 성장할 여지가 있겠지요.
이 글조차 한때의 고민으로 여길 만큼 성장한 히로를 혹은 저를 기대하면서
리뷰를 마치겠습니다. 좋은 글 감사합니다.

2020-03-31 12:14 UTC, ordinCode commented on level1.md
> +
> 포비는 첫 오리엔테이션에서 환경을 바꾸며, 의식적인 연습을 하고, 자존감을 잃지 말며, 무엇보다 남의 실력과 비교하지 말고 어제의 나와 비교하라고 하셨다.

글의 호흡이 길고 조금은 변화를 주면서 지루함을 최소화하려고 노력한게 보이지만 조금 더 다듬는 것도 좋아보이네요
나열할 것들을 따로 빼두는건 어떨까요?
예를들면 이런식으로요.

> 포비는 매주 수업을 할때 마다 강조하는 것들이 있다.  
> 환경을 바꿀것. 
> 의식적인 연습을할것. 
> 자존감을 잃지 않을것.
> 무엇보다 남의 실력과 비교하지말고 어제의 나와 비교할 것.

2020-03-31 12:15 UTC, ordinCode approved these changes
안녕하세요 히로! 학성입니다.
우테코 생활동안 히로의 마음에 대해 알 수 있었던 글이었어요. 많이 공감되는 부분도 있어서 재미있게 읽었습니다.

코멘트 보시고 공감된다면 수정부탁드립니다.

2020-04-01 01:40 UTC, kouz95 requested changes
리뷰 작성을 해놨었는데 깃헙 리뷰를 달아본적이 없어서 pending 상태로 되어있었네요..
미안합니다ㅜ
리뷰 확인해주세요!

2020-04-01 01:40 UTC, kouz95 commented on level1.md
> +즐거움도 잠시, 우리나라를 강타한 코로나19 전염병으로 인해 우아한형제들이 재택근무 체제로 전환하면서 우테코도 2주간의 재택 학습 및 휴식을 갖게 되었다. 학습에 대한 열정으로 불타는 상태였던 만큼 갑자기 찾아온 휴식기가 아쉬웠지만 책을 잔뜩 빌려가서 나름 할 수 있는 것을 집에서 해보았다. 이 또한 지나가리라 생각하면서.
우아한형제들의 재택근무 여부 보단 우테코가 휴식을 가졌다는게 중요하다고 생각해요..!

우아한형제들이 재택근무 체제로 전환하면서 우테코도 2주간의 재택 학습 및 휴식을 갖게 되었다.
-> 우테코는 2주간의 재택 학습 및 휴식을 갖게 되었다.

라고만 말해도 괜찮을것 같아요!

2020-04-01 01:40 UTC, kouz95 commented on level1.md
> +잠시 슬럼프가 찾아왔던 적이 있었다. 나보다 잘하는 사람이 너무 많다고 느꼈고, 모르는 것이 있을 때마다 공부하고 블로그에 글을 써가며 따라잡아보려고 애썼지만 이러다가 금방 체력이 동이 날 것만 같았다. 어려운 기술서들을 빌려서 보았지만 머리만 아팠고, 갈수록 걱정이 많아지고 긴장된 내색을 보이게 되었다.
따라잡아보려고 애썼지만 이러다가 금방 ~
따라잡아보려고 애썼지만 이러다간 금방 ~
은 어떠신가요?

저는 왠지 이러다간 이라고 썼을것 같아서요!

2020-04-01 04:17 UTC, yelimkim98 reviewed
글도 너무 잘쓰시는데 공감도 되네요 :) 남과 경쟁하지 말고 어제의 나와 경쟁하라는 말이 저도 너무 좋았고 인상깊었어요!

2020-04-01 04:17 UTC, yelimkim98 commented on level1.md
> +다행히 우아한테크코스는 생각했던 것처럼 약육강식의 세계는 아니었다. 교육과정에 있어서 점수도, 등수도 없으며 경쟁보단 협력을 통해 같이 성장하는 곳이었다. 미션마다 새로운 짝을 만나 페어 프로그래밍을 하며 배워가는 것도 많았고, Github를 통해 다른 크루들의 코드를 보거나 크루들끼리 자발적으로 모여 코드 리뷰를 하는 시간도 가져봤다. 코딩이 그 어느
공감공감!! 저도 양육강식의 세계가 아닌게 너무 좋았어요...! :)

2020-04-01 04:17 UTC, yelimkim98 commented on level1.md
> +잠시 슬럼프가 찾아왔던 적이 있었다. 나보다 잘하는 사람이 너무 많다고 느꼈고, 모르는 것이 있을 때마다 공부하고 블로그에 글을 써가며 따라잡아보려고 애썼지만 이러다가 금방 체력이 동이 날 것만 같았다. 어려운 기술서들을 빌려서 보았지만 머리만 아팠고, 갈수록 걱정이 많아지고 긴장된 내색을 보이게 되었다.
우테코에 오기 전의 일인가요?? 온 후의 일인가요?? 아니면 두 시기에 걸쳐서 있었던 일인가요??

2020-04-02 05:14 UTC, yelimkim98 approved these changes
공감되는 부분도 많았고 재밋게 잘 읽었습니다! :)

2020-04-03 04:29 UTC, kouz95 reviewed
리뷰 반영 해주신거 확인했습니다!
늦어져서 죄송해요 ㅜㅜ

히로의 고민을 들어볼수 있어서 좋았어요.
정말로 열심히 해왔고, 또한 욕심이 있는 사람이라고 느껴졌습니다.
열심히 하는 모습 보여주셔서 항상 좋은 영향을 받고 있습니다.

좋은글 감사드려요 😊

2020-04-03 04:32 UTC, kouz95 approved these changes
리뷰 반영 해주신거 확인했습니다!
늦어져서 죄송해요 ㅜㅜ

히로의 고민을 들어볼수 있어서 좋았어요.
정말로 열심히 해왔고, 또한 욕심이 있는 사람이라고 느껴졌습니다.
열심히 하는 모습 보여주셔서 항상 좋은 영향을 받고 있습니다.

좋은글 감사드려요 😊

2020-04-23 04:49 UTC, woowahanCU approved these changes

2020-04-23 04:49 UTC, merged