[소니] 레벨 2 - 성장 글쓰기 미션 제출합니다.
woowacourse/woowa-writing-2 pull request #73
Opened 2020-06-12 08:24 UTC by sonypark

안녕하세요. 글쓰기 리뷰어로 만나게 되었네요. 반갑습니다!
글은 [여기](https://github.com/sonypark/woowa-writing-2/blob/sonypark/%5B%EB%A0%88%EB%B2%A82-%EC%84%B1%EC%9E%A5%5D%ED%95%99%EC%8A%B5%EC%97%90%20%EB%8C%80%ED%95%9C%20%ED%83%9C%EB%8F%84.md)에서 읽으시면 됩니다.
리뷰 부탁드립니다. 감사합니다. 😊

2020-06-12 14:21 UTC, Ramen6315 reviewed
안녕하세요 소니!

이전의 공부 방법과 우테코에서 변화한 공부 방법에 대한 변화를 예시를 통해 써주셔서 글읽기가 좋았어요!

공부 방법이 바뀌면 흥미가 떨어지기 마련인데, 그렇지 않고 더 많은 흥미가 생겨서 다행이에요!

계속 해서 개발자로서 많은 성장 이루시길 바랄게요!

그리고 맞춤법 검사를 안하신거같아요ㅜㅜ
http://speller.cs.pusan.ac.kr/

맞춤법 검사를 제공하는 사이트인데 한번 확인해주시면 좋을거같아요!

Approve는 다른 크루 피드백을 포함해서 수정하신 내용을 확인하고 approve 할게요!

2020-06-12 15:56 UTC, joseph415 requested changes
안녕하세요 쏘니 :) 서브웨이 입니다.
우테코에서 학습하는 태도를 배우고 있다는 부분이 많이 공감이 되네요 :)
계속해서 성장하는 소니의 모습을 보니 수료를 했을 때 크게 성장해 있을 소니의 모습이 기대가 됩니다👍

글을 읽을 때 막히는 부분없이 잘 읽혀지고 
이전의 자신과 비교와 대조를 잘 사용해셔서 글쓰기 기술에 대해서는 피드백 드릴게 없는거 같아서 
맞춤법 검사기 한번 돌려봤는데 고쳐야 할 부분을 발견해서
이 부분 피드백 드려요!

고생하셨습니다 :)

2020-06-12 15:56 UTC, joseph415 commented on [레벨2-성장]학습에 대한 태도.md
> +개발을 처음 시작할 때는 그냥 되는 게 신기했다. 내가 짠 코드가 돌아가는 게 신기했고, 책과 강의를 보고 따라친 코드가 그대로 동작하는 게 신기했다. 그 당시 나에겐 코드가 돌아가는 게 중요했다. 어떻게 돌아가는지는 중요치 않았다. 그렇게 신나게 토이 프로젝트 몇 개를 만들고 스스로 뿌듯해 했다. 이런 공부 방법이 잘못되었다는 걸 알게 된 건 한 스타트
```suggestion
개발을 처음 시작할 때는 그냥 되는 게 신기했다. 내가 짠 코드가 돌아가는 게 신기했고, 책과 강의를 보고 따라친 코드가 그대로 동작하는 게 신기했다. 그 당시 나에겐 코드가 돌아가는 게 중요했다. 어떻게 돌아가는지는 중요치 않았다. 그렇게 신나게 토이 프로젝트 몇 개를 만들고 스스로 뿌듯해했다. 이런 공부 방법이 잘못되었다는 걸 알게 된 건 한 스타트업 면접을 보고 난 후였다. 운 좋게 서류 합격이 된 후 면접을 보게 되었고 거기서 내 민낯이 드러났다.
```

2020-06-12 15:56 UTC, joseph415 commented on [레벨2-성장]학습에 대한 태도.md
> +개발을 하면서 깊이 생각해보지 않고 지나친 것들이었다. 그냥 책에서 하라는 대로 했고, 문제가 생기면 스택오버플로우 답변을 참고해 해결했다. 그렇게 되는가보다 하고 넘어갔던 것들에 대해 질문을 받은 나는 제대로 답변할 수 없었다. 면접이 끝나고서야 알았다. 화면에 보이는 화려한 기능보다 그 기능이 어떻게 돌아가는지 아는게 더 중요하다는 것을.
```suggestion
개발을 하면서 깊이 생각해보지 않고 지나친 것들이었다. 그냥 책에서 하라는 대로 했고, 문제가 생기면 스택오버플로우 답변을 참고해 해결했다. 그렇게 되는가 보다 하고 넘어갔던 것들에 대해 질문을 받은 나는 제대로 답변할 수 없었다. 면접이 끝나고서야 알았다. 화면에 보이는 화려한 기능보다 그 기능이 어떻게 돌아가는지 아는 게 더 중요하다는 것을.
```

2020-06-12 15:56 UTC, joseph415 commented on [레벨2-성장]학습에 대한 태도.md
> +우테코에 들어와서는 개발 공부를 하는 태도가 달라졌다. 코드가 돌아가는 것보다 왜 돌아가는지가 더 궁금하다. **이전에는 '왜 안 되지?'라는 말을 많이 했다면, 이제는 '왜 되지?'라는 말울 많이 한다.** 이전에는 일단 되면 되나 보다 하고 넘어갔다. 원하는 기능이 있으면 검색한 코드를 복사 붙여넣기 했고, 코드가 돌아가면 좋아했다. 왜 되는지보단 일
```suggestion
우테코에 들어와서는 개발 공부를 하는 태도가 달라졌다. 코드가 돌아가는 것보다 왜 돌아가는지가 더 궁금하다. **이전에는 '왜 안 되지?'라는 말을 많이 했다면, 이제는 '왜 되지?'라는 말을 많이 한다.** 이전에는 일단 되면 되나 보다 하고 넘어갔다. 원하는 기능이 있으면 검색한 코드를 복사 붙여넣기 했고, 코드가 돌아가면 좋아했다. 왜 되는지보단 일단 되는 게 중요했다. 그런데 이제는 해당 기능이 어떻게 동작하는지가 더 궁금하다. 책이나 블로그에서 하라는 대로 하면 되는 건 알겠는데, 왜 되는지가 궁금하다.
```

2020-06-12 15:56 UTC, joseph415 commented on [레벨2-성장]학습에 대한 태도.md
> +- **SpringBoot**의 수 많은 **어노테이션**이 자동으로 무언가를 해준다는데, 어떤걸 자동으로 해주는 건지 어노테이션 별 차이점은 무엇인지가 궁금하다. 테스트 코드에서 `@WebMvcTest`에서는 안 되던게 `@SpringBootTest`로 바꾸니까 되네? 왜..?
```suggestion
- **SpringBoot**의 수많은 **어노테이션**이 자동으로 무언가를 해준다는데, 어떤걸 자동으로 해주는 건지 어노테이션 별 차이점은 무엇인지가 궁금하다. 테스트 코드에서 `@WebMvcTest`에서는 안 되던 게 `@SpringBootTest`로 바꾸니까 되네? 왜..?
```

2020-06-12 15:56 UTC, joseph415 commented on [레벨2-성장]학습에 대한 태도.md
> +- **VO(Value Object)** 값을 비교하는 테스트코드를 돌렸는데 실패한다. `equals()`와 `hashcode()`를 오버라이딩 해주니 테스트가 성공한다. 왜..? `equals()`만 해줘도 성공한다. 그럼 `hashcode()`는 왜 같이 정의해주지? 이전 같았으면 그냥 같이 해주라니까 그런가보다 하고 넘어갔을텐데, 이제는 그렇게 넘어
```suggestion
- **VO(Value Object)** 값을 비교하는 테스트코드를 돌렸는데 실패한다. `equals()`와 `hashcode()`를 오버라이딩 해주니 테스트가 성공한다. 왜..? `equals()`만 해줘도 성공한다. 그럼 `hashcode()`는 왜 같이 정의해주지? 이전 같았으면 그냥 같이해주라니까 그런가 보다 하고 넘어갔을 텐데, 이제는 그렇게 넘어가려니 너무 찜찜하다.
```

2020-06-12 15:56 UTC, joseph415 commented on [레벨2-성장]학습에 대한 태도.md
> +- `git reset -—hard` 는 위험하니 조심해서 써야 한다고 한다. 왜? 복구 할 수 없다고? 아 그렇구나.. 응? 검색해보니 복구 할 수 있다는데? 그게 어떻게 가능한거지? **git**이 데이터를 저장하는 방식이 궁금하다.
```suggestion
- `git reset -—hard` 는 위험하니 조심해서 써야 한다고 한다. 왜? 복구 할 수 없다고? 아 그렇구나.. 응? 검색해보니 복구할 수 있다는데? 그게 어떻게 가능한 거지? **git**이 데이터를 저장하는 방식이 궁금하다.
```

2020-06-12 15:56 UTC, joseph415 commented on [레벨2-성장]학습에 대한 태도.md
> +우테코 교육도 당장 돌아가는 코드를 짜기 보단, 시간이 좀 더 걸리더라도 읽기 쉽고, 유지 보수가 용이한 코드를 짜도록 유도한다. 그래서인지 크루들 간 대화 주제도 특정 기술에 대한 이야기보다 도메인 구조나 기능의 원리 (ex. DB 테이블의 구조, 스프링 인터셉터의 원리 등)에 대한 토론이 더 많다.
```suggestion
우테코 교육도 당장 돌아가는 코드를 짜기보단, 시간이 좀 더 걸리더라도 읽기 쉽고, 유지 보수가 용이한 코드를 짜도록 유도한다. 그래서인지 크루들 간 대화 주제도 특정 기술에 대한 이야기보다 도메인 구조나 기능의 원리 (ex. DB 테이블의 구조, 스프링 인터셉터의 원리 등)에 대한 토론이 더 많다.
```

2020-06-13 02:18 UTC, sonypark commented on [레벨2-성장]학습에 대한 태도.md
> +개발을 하면서 깊이 생각해보지 않고 지나친 것들이었다. 그냥 책에서 하라는 대로 했고, 문제가 생기면 스택오버플로우 답변을 참고해 해결했다. 그렇게 되는가보다 하고 넘어갔던 것들에 대해 질문을 받은 나는 제대로 답변할 수 없었다. 면접이 끝나고서야 알았다. 화면에 보이는 화려한 기능보다 그 기능이 어떻게 돌아가는지 아는게 더 중요하다는 것을.
헉.. 제가 마지막에 맞춤법 검사 돌리고 푸시를 안 했었네요..😅 지적해주신 것 중 캐치하지 못한 부분도 있어서 모두 고쳤습니다! 감사합니다!

2020-06-13 02:18 UTC, sonypark commented on [레벨2-성장]학습에 대한 태도.md
> +우테코에 들어와서는 개발 공부를 하는 태도가 달라졌다. 코드가 돌아가는 것보다 왜 돌아가는지가 더 궁금하다. **이전에는 '왜 안 되지?'라는 말을 많이 했다면, 이제는 '왜 되지?'라는 말울 많이 한다.** 이전에는 일단 되면 되나 보다 하고 넘어갔다. 원하는 기능이 있으면 검색한 코드를 복사 붙여넣기 했고, 코드가 돌아가면 좋아했다. 왜 되는지보단 일
😱

2020-06-13 02:19 UTC, sonypark commented on [레벨2-성장]학습에 대한 태도.md
> +- **SpringBoot**의 수 많은 **어노테이션**이 자동으로 무언가를 해준다는데, 어떤걸 자동으로 해주는 건지 어노테이션 별 차이점은 무엇인지가 궁금하다. 테스트 코드에서 `@WebMvcTest`에서는 안 되던게 `@SpringBootTest`로 바꾸니까 되네? 왜..?
😮

2020-06-13 02:19 UTC, sonypark commented on [레벨2-성장]학습에 대한 태도.md
> +- **VO(Value Object)** 값을 비교하는 테스트코드를 돌렸는데 실패한다. `equals()`와 `hashcode()`를 오버라이딩 해주니 테스트가 성공한다. 왜..? `equals()`만 해줘도 성공한다. 그럼 `hashcode()`는 왜 같이 정의해주지? 이전 같았으면 그냥 같이 해주라니까 그런가보다 하고 넘어갔을텐데, 이제는 그렇게 넘어
😳

2020-06-13 02:19 UTC, sonypark commented on [레벨2-성장]학습에 대한 태도.md
> +- `git reset -—hard` 는 위험하니 조심해서 써야 한다고 한다. 왜? 복구 할 수 없다고? 아 그렇구나.. 응? 검색해보니 복구 할 수 있다는데? 그게 어떻게 가능한거지? **git**이 데이터를 저장하는 방식이 궁금하다.
😦

2020-06-13 02:19 UTC, sonypark commented on [레벨2-성장]학습에 대한 태도.md
> +우테코 교육도 당장 돌아가는 코드를 짜기 보단, 시간이 좀 더 걸리더라도 읽기 쉽고, 유지 보수가 용이한 코드를 짜도록 유도한다. 그래서인지 크루들 간 대화 주제도 특정 기술에 대한 이야기보다 도메인 구조나 기능의 원리 (ex. DB 테이블의 구조, 스프링 인터셉터의 원리 등)에 대한 토론이 더 많다.
🥵

2020-06-13 07:10 UTC, hwanghe159 approved these changes
안녕하세요 소니~!
저도 우테코를 하면서 "왜?" 라는 질문을 전보단 많이 하게 됐는데
소니만큼은 아니었던 것 같아요. 더 호기심을 가져보도록 노력해봐야 겠어요! 
글이 너무 깔끔해서 피드백 할 부분이 보이질 않네요,, 바로 Approve하겠습니다!

2020-06-13 19:31 UTC, Hamliet approved these changes
안녕하세요 소니! 라흐입니다 ㅎㅎ
레벨1 글쓰기 미션때도 느꼈지만 공감되고 울림이 있는 글을 잘 쓰시는 것 같아요.
자신이 느낀 것들을 글로 오롯이 표현하는 능력이 좋으신 것 같네요!
잘 읽었습니다. 이만 Approve 할게요!

2020-06-13 19:31 UTC, Hamliet commented on [레벨2-성장]학습에 대한 태도.md
> +무작정 돌아가는 코드를 만들 때는 무언가 배우는 것 같으면서도 항상 불안했다. 기능의 사용법을 공부해서 쓰긴 했는데 동작하는 원리에 대해서는 모르고 사용했기 때문이다. 이제는 기능의 사용법을 익히는 동시에 그 뒤에서 일어나는 동작 방식에 대해 공부하려고 노력한다. 시간은 두 배 이상 걸리지만 그만큼 기능에 대한 이해도 더 깊어지는 것 같다. **우테코에서
"우테코에서 기술보다 기술을 학습하는 태도를 배우고 있다." 라는 문장이 많이 공감되네요 ㅎㅎ

2020-06-15 09:36 UTC, Ramen6315 approved these changes
소니!

수정 하신 글 을  다시 한번 글을 읽어봤는데 

우테코 이전과 이후의 공부 방법에 대한 변화가 다시금 확실 하게 느껴지고 다른 크루들에게도 도움이 될 글인거같습니다!

기술사용자를 넘어 개발자로서 많은 발전 이루시길 바랄게요!

approve 하겠습니다!

레벨 2까지 고생 많으셨습니다.

2020-06-15 12:58 UTC, joseph415 approved these changes
리뷰 잘 적용하셨네요 :) 고생하셨습니다.
approve 하겠습니다!

2020-08-24 09:02 UTC, woowahan-pjs approved these changes
레벨 3 글쓰기를 위해 Merge 할게요! 👍

2020-08-24 09:03 UTC, merged