[제이] 레벨 2 - 성장 글쓰기 미션 제출합니다.
woowacourse/woowa-writing-2 pull request #93
Opened 2020-06-14 09:54 UTC by jjj0611

리뷰 기대하겠습니다 😄

2020-06-14 10:27 UTC, begaonnuri requested changes
제이 안녕하세요!

사진과 개발을 병치해서 풀어나간 점이 인상적이네요!
전 사진에 무지해서 그런지 잘 와닿지는 않았습니다. 😅

글을 읽으면서 '아 이래서 제이가 이렇게 행동했었구나' 어렴풋이 짐작할 수 있게 되었네요.
몇가지 변경사항 남겼습니다. 확인해주세요!

2020-06-14 10:27 UTC, begaonnuri commented on leve2-성장.md
> +> 사진에 관해 학습하기 가장 좋은 시점은 자신이 찍어야 할 사진이 있을 때이다.
여기선 `관해`보단 `대해`가 더 적절한 것 같아요.

> 사진에 대해 학습하기 가장 좋은 시점

혹은

> 사진과 관련된 학습을 하는 가장 좋은 시점

으로 변경해보는건 어떨까요?

2020-06-14 10:27 UTC, begaonnuri commented on leve2-성장.md
> +처음 사진을 찍기 시작하면 사진의 역사나 카메라의 구조, 셔터 스피드, 조리개, ISO 등에 대해 고민하는 것은 좋지 않다. 일단 찍는 것이 중요하다. 구도나 대상을 생각하면서 사진을 찍다 보면 목마름이 찾아온다. "사람을 좀 더 부각해서 찍고 싶은데?", "사진에 잔상이 남지 않으려면 어떻게 하지?", "밤하늘의 별은 왜 이렇게 어둡게 찍히지?" 그저
> 사진을 찍기 시작하면 ~~. 일단 찍는 것이 중요하다.

이 부분이 의도는 알겠지만 부자연스러운것 같아요.
무엇을 하기 위해 중요한 것인지가 빠져있어서 그런것 같은데,

> 일단 많이 찍어 보는 것이 중요하다.

혹은

> 사진 찍는 것이 익숙해지기 위해선 일단 많이 찍어 보는 것이 중요하다.

와 비슷한 문장으로 `목적`을 넣어서 변경해보는건 어떨까요?

2020-06-14 10:27 UTC, begaonnuri commented on leve2-성장.md
> +프로그래밍을 공부하는 것도 마찬가지라 생각한다. 일단 필요한 기능들을 구현해 보는 즐거움을 맛보는 것이 중요하다. 그런 경험치들이 하나 둘 씩 쌓이며 궁금한 부분이 생길 때, 그때 학습하는 것이 효과적이다. 1부터 10까지 정해진 커리큘럼을 따라가는 것도 좋은 학습법이지만, 프로그래밍 세계에 완전히 적합하진 않다. 나에게 필요한 부분을 필요한 때에 학습하
무엇에 대한 궁금한 부분인지 넣어주는 것이 더 자연스러울 것 같아요.

> 경험치들이 하나 둘 씩 쌓이며 구현하다가 궁금한 부분이 생길 때

와 같은 문장으로 바꿔보는것은 어떨까요?

2020-06-14 10:27 UTC, begaonnuri commented on leve2-성장.md
> +> 빌 게이츠는 한 인터뷰에서 '_슈퍼 스마트(supersmart)_'라는 단어를 사용했는데, 그 의미를 코드를 작성한 뒤 6개월이 지난 시점에도 자신의 코드를 설명할 수 있는 것이라 설명했다.
문단의 내용과 인용구가 조금 동떨어져있는 것 같아요.

한 섹션의 시작을 인용으로 시작하는 형식을 맞추기 위해서라면 다른 인용구로 대체하고,
그게 아니라면 굳이 없어도 될 것 같아요.

2020-06-14 10:27 UTC, begaonnuri commented on leve2-성장.md
> +프로그래밍 세계에 발을 들이며 '왜?'라는 질문을 자주 던지는 내 특성이 강점으로 활용될 수 있다는 생각이 강하게 들었다. 태생적(?)으로 이 질문을 많이 던지는 탓에 어렸을 적(정말 어렸을 적임에도 생생하게 기억난다.) 한 어른에게 "왜라는 질문 좀 그만해"라는 핀잔을 받았던 기억이 난다. 그때의 나의 대답은 역시 "왜?"였다.
버릇없는 녀석이였겠네요😄

2020-06-14 10:27 UTC, begaonnuri commented on leve2-성장.md
> +우테코에 와서 확신하게 된 공부법 중 하나가 '정답을 완성해가는 공부법'이다. 하나의 방법만 고집하는 것이 아니라 결론을 통합해나가는 것. 그 과정에서 장단점을 고민하고 본인이 내린 결론의 근거를 찾아 나가는 것이다. 마치 셔터 스피드와 조리개 사이를 조율하고, ISO라는 축이 하나 생기고, 조명이라는 변수가 들어가면서 내가 설정한 것에 딱 맞는 사진이
> '내 코드엔 분명한 이유가 있어야 한다.'

미션 속의 미션을 해보는 것도 좋겠네요😄

2020-06-14 17:21 UTC, yebink approved these changes
안녕하세요 제이! 글 잘 읽었습니다. 💯 
담백하고 좋네요.
분량이 조금 더 길었으면 하는 아쉬움이 살짝 남지만!
전체적으로 비유법을 잘 사용하신 것 같아 어프루브 목걸이 드립니다.
수고하셨어요!

2020-06-14 17:21 UTC, YebinK commented on leve2-성장.md
> +처음 사진을 찍기 시작하면 사진의 역사나 카메라의 구조, 셔터 스피드, 조리개, ISO 등에 대해 고민하는 것은 좋지 않다. 일단 찍는 것이 중요하다. 구도나 대상을 생각하면서 사진을 찍다 보면 목마름이 찾아온다. "사람을 좀 더 부각해서 찍고 싶은데?", "사진에 잔상이 남지 않으려면 어떻게 하지?", "밤하늘의 별은 왜 이렇게 어둡게 찍히지?" 그저
오호라... 비유법을 쓰셨군요!
💯

2020-06-14 17:21 UTC, YebinK commented on leve2-성장.md
> +프로그래밍 세계에 발을 들이며 '왜?'라는 질문을 자주 던지는 내 특성이 강점으로 활용될 수 있다는 생각이 강하게 들었다. 태생적(?)으로 이 질문을 많이 던지는 탓에 어렸을 적(정말 어렸을 적임에도 생생하게 기억난다.) 한 어른에게 "왜라는 질문 좀 그만해"라는 핀잔을 받았던 기억이 난다. 그때의 나의 대답은 역시 "왜?"였다.
@begaonnuri 
`버릇없는 녀석이였겠네요😄`
-> `버릇없는 녀석이었겠네요😄`

2020-06-14 17:21 UTC, YebinK commented on leve2-성장.md
> +프로그래밍 세계에 발을 들이며 '왜?'라는 질문을 자주 던지는 내 특성이 강점으로 활용될 수 있다는 생각이 강하게 들었다. 태생적(?)으로 이 질문을 많이 던지는 탓에 어렸을 적(정말 어렸을 적임에도 생생하게 기억난다.) 한 어른에게 "왜라는 질문 좀 그만해"라는 핀잔을 받았던 기억이 난다. 그때의 나의 대답은 역시 "왜?"였다.
귀여운 꼬마 제이가 상상되네요.

2020-06-14 17:21 UTC, YebinK commented on leve2-성장.md
> +우테코 크루들이 많이 하는 말 중 하나가 "어차피 코치들은 정답을 말하지 않잖아"이다. 코치들의 그런 태도가 나에게는 명확한 메시지로 다가왔다. `정답은 없어요!` 하지만 그렇게 말하는 코치들이 씩 하고 웃는 모습을 보면 분명 정답이 존재한다. `그들만의 정답이`
`그들만의 정답이` 뒤에 뭐가 더 있는건가요?
궁금해요!

2020-06-14 17:21 UTC, YebinK commented on leve2-성장.md
> +> 빌 게이츠는 한 인터뷰에서 '_슈퍼 스마트(supersmart)_'라는 단어를 사용했는데, 그 의미를 코드를 작성한 뒤 6개월이 지난 시점에도 자신의 코드를 설명할 수 있는 것이라 설명했다.
동의합니다. 평소에 제이가 많이 하는 말로 보아 꼭 넣고 싶어 하는 것 같네요!
그렇다면 앞뒤에 연결고리를 추가해주면 좋을 것 같아요. :)

2020-06-14 17:21 UTC, YebinK commented on leve2-성장.md
> +지금까지 이야기한 학습법들은 '함께'해야 더 빛을 발한다. 누군가를 설득하는 근거를 찾는 학습법도, 아는 것에 대해 공유하는 학습법도 다른 사람과 '함께'할 때 시너지가 더 크다. 우테코에서 찾은 가장 확실한 학습법은 '동일한 목표를 가진 사람들과 지식을 공유하며 함께 성장하는 것이다.' 때로는 다른 크루들과 토론을 하며 나의 근거를 견고하게 하고, 서로
> 그 과정을 통해 아는 것과 모르는 것의 경계가 분명해지고, 모르는 것을 아는 것으로 바꾸어 가는 과정.
👍

2020-06-15 09:42 UTC, giantim approved these changes
제이 안녕하세요 라빈입니다!

인텔리제이가 되기 위해 열심히 학습했었던 제이의 모습이 잘 담긴 글이네요!
사진을 찍은 경험에 빗대어서 본인의 효과적인 공부법을 설명하신 부분이 재미있네요 :)
언제나 왜 라는 질문을 즐겨하고 다른 사람들의 질문에도 막힘없이 자신의 생각을 말하는 
제이의 모습이 잘 담겨서 읽기 좋았습니다.

저는 글에 대해서 딱히 어색한 부분은 없었고 레벨 2 글쓰기 미션 진행하시느라 고생 많으셨습니다 :)

2020-06-15 09:42 UTC, giantim commented on leve2-성장.md
> +모르는 부분이 질문으로 들어왔을 땐 일단 내가 아는 것까진 얘기한다. 그리고 역으로 내가 그 사람을 물고 늘어진다. "뭐가 문제야? 어떤 게 안돼? 아 그래? 이렇게 해볼까?" 이러다 보면 혼자서는 하지 못했을 곳을 탐색하게 된다. 이때 '지'와 '무지'의 경계가 드러나는데 이 과정에서 내가 무엇을 더 공부해야 할지 보이는 시점이 온다.
왜? 를 통해서 자신의 부족한 부분을 채워나가는 습관이 정말 좋은것 같아요

2020-06-15 09:42 UTC, giantim commented on leve2-성장.md
> +우테코 크루들이 많이 하는 말 중 하나가 "어차피 코치들은 정답을 말하지 않잖아"이다. 코치들의 그런 태도가 나에게는 명확한 메시지로 다가왔다. `정답은 없어요!` 하지만 그렇게 말하는 코치들이 씩 하고 웃는 모습을 보면 분명 정답이 존재한다. `그들만의 정답이`
우테코에서 자신만의 정답을 만들어 가도록 지도해줄때 저는 처음에 힘들었지만 점점 무슨 뜻인지 이해가 되고 이 과정을 통해서 많은 발전을 하는 것 같습니다 :)

2020-06-15 11:46 UTC, jjj0611 commented on leve2-성장.md
> +> 사진에 관해 학습하기 가장 좋은 시점은 자신이 찍어야 할 사진이 있을 때이다.
저도 대해가 조금 더 와 닿는다고 생각했는데요.
부산대 맞춤법 검사기를 돌려보니 '대해'와 '관해' 모두 영어적 표현인데,
'대해'는 'against'의 의미와 비슷하고 '관해'는 'about'의 의미와 비슷하다고 하더라구요!
about의 의미를 더 살리고자 '관해'라고 적었습니다!

2020-06-15 11:48 UTC, jjj0611 commented on leve2-성장.md
> +처음 사진을 찍기 시작하면 사진의 역사나 카메라의 구조, 셔터 스피드, 조리개, ISO 등에 대해 고민하는 것은 좋지 않다. 일단 찍는 것이 중요하다. 구도나 대상을 생각하면서 사진을 찍다 보면 목마름이 찾아온다. "사람을 좀 더 부각해서 찍고 싶은데?", "사진에 잔상이 남지 않으려면 어떻게 하지?", "밤하늘의 별은 왜 이렇게 어둡게 찍히지?" 그저
익숙해지기 위해서 사진을 많이 찍어보라는 것보단, 사진을 처음 찍는 시기에 어떤 것부터 할건지에 더 초점을 둔 말인데 부자연스럽나요???
사진에 익숙해지기 위해서라기보다 많이 찍는 경험치가 쌓였을 때 사진에 관해 궁금해지는 시기가 온다는 것을 이야기 하고 싶었는데 와 닿지가 않았나보네요! 고민해보겠습니다~

2020-06-15 11:49 UTC, jjj0611 commented on leve2-성장.md
> +> 빌 게이츠는 한 인터뷰에서 '_슈퍼 스마트(supersmart)_'라는 단어를 사용했는데, 그 의미를 코드를 작성한 뒤 6개월이 지난 시점에도 자신의 코드를 설명할 수 있는 것이라 설명했다.
6개월이 지난 시점에도 자신의 코드를 설명할 수 있다는 것은
처음 코드를 작성하는 순간 아무런 이유 없이 지나가지 않았다는 것을 의미하고 싶었어요!
연결 고리를 좀 더 추가해주어야겠군요 🤔

2020-06-15 11:51 UTC, jjj0611 commented on leve2-성장.md
> +우테코에 와서 확신하게 된 공부법 중 하나가 '정답을 완성해가는 공부법'이다. 하나의 방법만 고집하는 것이 아니라 결론을 통합해나가는 것. 그 과정에서 장단점을 고민하고 본인이 내린 결론의 근거를 찾아 나가는 것이다. 마치 셔터 스피드와 조리개 사이를 조율하고, ISO라는 축이 하나 생기고, 조명이라는 변수가 들어가면서 내가 설정한 것에 딱 맞는 사진이
저 말은 이미 하고 있다는건데...
터틀 제 글에 관심이 없나봐요 😭

2020-06-15 11:52 UTC, jjj0611 commented on leve2-성장.md
> +우테코 크루들이 많이 하는 말 중 하나가 "어차피 코치들은 정답을 말하지 않잖아"이다. 코치들의 그런 태도가 나에게는 명확한 메시지로 다가왔다. `정답은 없어요!` 하지만 그렇게 말하는 코치들이 씩 하고 웃는 모습을 보면 분명 정답이 존재한다. `그들만의 정답이`
아녀 없어요!
코치들이 그들만의 정답이 있었다는 것과
그래서 본인의 정답을 완성해가는 공부법을 이은 건데
저만 🌉(다리)가 보이나요?!

2020-06-15 11:53 UTC, jjj0611 commented on leve2-성장.md
> +모르는 부분이 질문으로 들어왔을 땐 일단 내가 아는 것까진 얘기한다. 그리고 역으로 내가 그 사람을 물고 늘어진다. "뭐가 문제야? 어떤 게 안돼? 아 그래? 이렇게 해볼까?" 이러다 보면 혼자서는 하지 못했을 곳을 탐색하게 된다. 이때 '지'와 '무지'의 경계가 드러나는데 이 과정에서 내가 무엇을 더 공부해야 할지 보이는 시점이 온다.
라빈도 저에게 왜라는 질문을 많이 던져주어서 항상 고마워요 😄

2020-06-15 11:53 UTC, jjj0611 commented on leve2-성장.md
> +우테코 크루들이 많이 하는 말 중 하나가 "어차피 코치들은 정답을 말하지 않잖아"이다. 코치들의 그런 태도가 나에게는 명확한 메시지로 다가왔다. `정답은 없어요!` 하지만 그렇게 말하는 코치들이 씩 하고 웃는 모습을 보면 분명 정답이 존재한다. `그들만의 정답이`
저도 그렇게 생각해요!
답이 주어지면 더 편할거라 생각했는데 답이 주어지는 것보다 답을 찾아나가는게 더 값지더라구요!
함께 더 발전해 나가요~

2020-06-16 02:02 UTC, woonjangahn approved these changes
안녕하세요, 제이! 요구사항에 맞게 잘 구현해주셨어요 💯 💯 💯 
다른 크루들이 좋은 피드백을 많이 남겨서 저도 짧은 피드백 몇 개만 남겼으니 선택적으로 반영해주세요!
글에서도 사진에 대한 경험을 가지고 프로그래밍 학습 과정을 설명해주셨는데요, 즐겁게 읽을 수 있었습니다 ^^

우테코에서 제이를 만난 것은 큰 행운이예요 ㅎㅎ 코딩 경험이 월등히 많고 재능도 노력도 출중한 제이에게서 정말 많은 것들을 배우고 있습니다! 지금까지 그래왔듯 앞으로도 잘 부탁드리고, 함께 성장할 수 있었으면 좋겠네요 :)

이만 Approve 하겠습니다. 고생하셨습니다!

2020-06-16 02:02 UTC, woonjangahn commented on leve2-성장.md
> +처음 사진을 찍기 시작하면 사진의 역사나 카메라의 구조, 셔터 스피드, 조리개, ISO 등에 대해 고민하는 것은 좋지 않다. 일단 찍는 것이 중요하다. 구도나 대상을 생각하면서 사진을 찍다 보면 목마름이 찾아온다. "사람을 좀 더 부각해서 찍고 싶은데?", "사진에 잔상이 남지 않으려면 어떻게 하지?", "밤하늘의 별은 왜 이렇게 어둡게 찍히지?" 그저
> 그저 눈앞 대상을 담던 카메라로 더 멋진 세상을 담고자 하는 욕구가 들었을 때, 사진에 관해 공부하기 좋은 시기가 된다.

멋진 말이네요 :)

2020-06-16 02:02 UTC, woonjangahn commented on leve2-성장.md
> +프로그래밍을 공부하는 것도 마찬가지라 생각한다. 일단 필요한 기능들을 구현해 보는 즐거움을 맛보는 것이 중요하다. 그런 경험치들이 하나 둘 씩 쌓이며 궁금한 부분이 생길 때, 그때 학습하는 것이 효과적이다. 1부터 10까지 정해진 커리큘럼을 따라가는 것도 좋은 학습법이지만, 프로그래밍 세계에 완전히 적합하진 않다. 나에게 필요한 부분을 필요한 때에 학습하
```suggestion
프로그래밍을 공부하는 것도 마찬가지다. 일단 필요한 기능들을 구현하며 즐거움을 맛보는 것이 중요하다. 경험치들이 하나 둘 쌓이며 궁금한 부분이 생길 때, 그때 학습하는 것이 효과적이다. 1부터 10까지 정해진 커리큘럼을 따라가는 것도 좋은 학습법이지만, 프로그래밍 세계에 완전히 적합하진 않다. 필요한 부분을 필요한 때에 학습하는 것이 가장 좋다.
```

미사여구를 줄일 수 있을 것 같아요.

2020-06-16 02:02 UTC, woonjangahn commented on leve2-성장.md
> +프로그래밍 세계에 발을 들이며 '왜?'라는 질문을 자주 던지는 내 특성이 강점으로 활용될 수 있다는 생각이 강하게 들었다. 태생적(?)으로 이 질문을 많이 던지는 탓에 어렸을 적(정말 어렸을 적임에도 생생하게 기억난다.) 한 어른에게 "왜라는 질문 좀 그만해"라는 핀잔을 받았던 기억이 난다. 그때의 나의 대답은 역시 "왜?"였다.
제이에게 제일 많이 배운 좋은 버릇이네요 제겐 :)

2020-06-16 02:02 UTC, woonjangahn commented on leve2-성장.md
> +우테코에 와서 확신하게 된 공부법 중 하나가 '정답을 완성해가는 공부법'이다. 하나의 방법만 고집하는 것이 아니라 결론을 통합해나가는 것. 그 과정에서 장단점을 고민하고 본인이 내린 결론의 근거를 찾아 나가는 것이다. 마치 셔터 스피드와 조리개 사이를 조율하고, ISO라는 축이 하나 생기고, 조명이라는 변수가 들어가면서 내가 설정한 것에 딱 맞는 사진이
```suggestion
우테코에서 확신하게 된 공부법 중 하나가 '정답을 완성해가는 공부법'이다. 하나의 방법만 고집하지 않고 결론을 통합해나가는 것. 그 과정에서 장단점을 고민하고 스스로 결론의 근거를 찾는 것이다. 마치 셔터 스피드와 조리개 사이를 조율하고, ISO라는 축이 하나 생기고, 조명이라는 변수가 들어가면서 내가 설정한 것에 딱 맞는 사진이 나오는 것과 같다. 분명한 근거가 있는 사진이다. 프로그래밍을 학습하면서도 근거를 확고히 하고 있다. '내 코드엔 분명한 이유가 있어야 한다.'
```

2020-08-24 09:05 UTC, woowahan-pjs approved these changes
레벨 3 글쓰기를 위해 Merge 할게요! 👍

2020-08-24 09:05 UTC, merged